### ISSUE TITLE
Sharing e-mail bug

### ISSUE THREAD

**Issue by csola48** [QuiteRSS/quiterss#1000]
Fresh install 0.18.6 => "Megosztás" > "Email"
Sends this:

'http://quiterss.org/en/article/1153%0A%0AQuiteRSS2 developing is
started!%0AThe application will be completely rewrited.%0AUI will be
redesigned. Special thanks to Bozhevarsky Dmitry.%0AWebkit engine of
internal browser will be replaced by Chromium.%0AThere will be special
release without internal browser.%0AThe appliction release date is
undefined.%0AFrom now update for current v0-version will fix critical
bugs only.%0A"

Instead of this:
"http://quiterss.org/en/article/1153"

Pls. help me!
It is necessary to remove the previous version? (0.18.3+dfsg-1)

**Comment by Funcy-dcm** [comment]
Everything is working fine for me
What is your OS?

**Comment by csola48** [comment]
1)
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
Linux csola48 4.8.0-58-generic #63~16.04.1-Ubuntu SMP
Mon Jun 26 17:59:49 UTC 2017 i686 i686 i686 GNU/Linux
2) 
Thunderbird Version 52.1.1 (32 bit)

**Comment by csola48** [comment]
The 0.18.3+dfsg-1 worked for me too gently... :(

**Comment by Funcy-dcm** [comment]
Unfortunately, I could not verify on Linux. But in windows 8.1 and Thunderbird 35 - works well.

**Comment by Funcy-dcm** [comment]
I repeated the problem (on linux), I will try to fix it

**Comment by Funcy-dcm** [comment]
fix: 1ef97c5479f4c14b380ffef1e36f15a9954d517e

**Comment by csola48** [comment]
Thx !
