### ISSUE TITLE
Qt & Feed Status "server replied: (299)" Issue

### ISSUE THREAD

**Issue by JLChamberlain** [QuiteRSS/quiterss#1001]
At the moment I have 65+ Feeds for Nyaa.si in QuiteRSS but everytime I start the program up a good number of the feeds bring up the status "server replied: (299)", I have reported this issue to the Nyaa GitHub page & they have said it's not their issue but with the Qt in QuiteRSS. I was wondering if you could explain why this is happening & if you could fix it. I even set QuiteRSS to retry multiple times on failure but some feeds still give the server error.

Nyaa GitHub Issue Post: https://github.com/nyaadevs/nyaa/issues/256

**Comment by Funcy-dcm** [comment]
As soon as I have time, I will try to understand this problem

**Comment by Funcy-dcm** [comment]
You can send the file debug.log
You can increase the setting: Menu-Tools-Options-Network connections-Number of requests
But in any case, this server error, I can make exceptions for errors with code 299, but this is not correct. The server must not return errors at all.

**Comment by JLChamberlain** [comment]
How do I get the debug.log?, also I already have QuiteRSS to set to 10 for number of retries but the status problem still appears.

**Comment by Funcy-dcm** [comment]
Menu - Help - About - Information
Indeed, this is the maximum )

**Comment by JLChamberlain** [comment]
Here:
[Debug Log.txt](https://github.com/QuiteRSS/quiterss/files/1173099/Debug.Log.txt)

**Comment by TheAMM** [comment]
We did some prodding ourselves and it would seem like QuiteRSS does not handle [HTTP 429](https://httpstatuses.com/429)s aka ratelimits.
Qt's networking throws back an error, QuiteRSS doesn't have specific handling for it and formats it as `server replied: (299)`.

**Comment by Arylide** [comment]
The rate limiting employed is relatively fair at several requests per second, I recommend you optimize your software to not launch all feed grabs at the same moment if they are for the same domain. Perhaps execute one wait 1-2 seconds, launch another?

**Comment by Funcy-dcm** [comment]
@Arylide Thanks for the advice.
@JLChamberlain You need : Menu-Tools-Options-Network connections-Number of requests 1 or 2, Number of retries 5

**Comment by JLChamberlain** [comment]
I have requests set to 10 & retries set to 10 when I gave you the debug.log

**Comment by Funcy-dcm** [comment]
Number of requests: **1 or 2**

**Comment by Funcy-dcm** [comment]
@JLChamberlain Did it work for you?

**Comment by JLChamberlain** [comment]
At the moment yes.
