### ISSUE TITLE
Feature Request - Add More Sharing Options

### ISSUE THREAD

**Issue by marathone** [QuiteRSS/quiterss#1002]
Thanks for an excellent RSS feed reader. IMHO it's the best I've seen thus far! (° ͜ʖ °)

Would it be possible to allow the user to add more sharing options in addition to the hard coded ones? Missing for me is Reddit & Instapaper to name two.

**Comment by Funcy-dcm** [comment]
This will be implemented in QuiteRSS2

**Comment by marathone** [comment]
Any timeframe for when that release will be available?

**Comment by Funcy-dcm** [comment]
I have to rethink a lot, I think a minimum of six months
Although instapaper I can quickly implement possible in the current version.

**Comment by marathone** [comment]
Thanks for implementing this so quickly!
