### ISSUE TITLE
Crashes when you switch the layout(Newspaper/Classic) if it is in a open tab

### ISSUE THREAD

**Issue by rgamici** [QuiteRSS/quiterss#1004]
Accidentally, I clicked on the button to change the layout between Newspaper and Classic mode while I was reading a tab open on the internal browser and the program crashed.
I tried again and the problem persisted. I also tried changing between each mode (from Classic to Newspaper and vice versa) and it crashed both ways.

I'm using version 0.18.6 (20.06.2017) on a Debian system.

**Comment by Funcy-dcm** [comment]
I repeated the problem - I will soon fix it
