### ISSUE TITLE
When changing tabs, the news list is filtered again and the showed position changes

### ISSUE THREAD

**Issue by rgamici** [QuiteRSS/quiterss#1005]
Layout mode: Newspaper
Filter News: Show only unread (may happen with other filter options)

Steps to reproduce:
1. Mark some news as read on the feed.
2. Open a news in a new tab and switch to it.
3. Switch back to the main tab (or close the opened tab).

It should display the news list as I left, but instead it changes its positions, moving down the view to some other news. 
As far I could check, it refreshes the news list and hides some news that were marked as read, which result in the different news being shown on the screen. This became a problem when reading feeds with long items as it jumps to a different text position, even to other items. And also more critically if the news that was being read disappears because of the list is refreshed.

I'm using QuiteRSS 0.18.6 on Debian with LXDE.

**Comment by Funcy-dcm** [comment]
Unfortunately, I can not implement a better work option
