### ISSUE TITLE
doesn't update all of feeds

### ISSUE THREAD

**Issue by tonypachino** [QuiteRSS/quiterss#1008]
i have lot of feeds and when i click update all feeds button QuiteRSS doesn't update all feeds but leave some of them as they are and you can see x sign on feed icon

**Comment by Funcy-dcm** [comment]
Send screenshots

**Comment by tonypachino** [comment]
![1](https://user-images.githubusercontent.com/11837409/29332491-7d3406e6-8200-11e7-9436-5a5055232465.png)
Sometimes QuiteRSS updates those with x sign but sometimes not, especially now when i have a base with lot of feeds

**Comment by Katarn** [comment]
This may be because YouTube bans for a while with a large number of requests. I think so. I also observe this behavior for myself.

**Comment by Funcy-dcm** [comment]
Set the "Number of requests" option to 1 or 2 (Menu - Tools - Options - Network Connections)

**Comment by tonypachino** [comment]
i don't know, sometimes feeds are updated, for example first time i click update all feeds, they won't update all and when i click second time they almost all update...
