### ISSUE TITLE
embedded browser crashes on youtube play

### ISSUE THREAD

**Issue by tonypachino** [QuiteRSS/quiterss#1009]
probably you (developer) already know that problem, i just want to tell you that i hope that you will fix this in upcoming versions because embedded browser is great option so that user doesn't have to jump from QuiteRss to external web browser.

Thank you for such a wonderfull software

**Comment by Funcy-dcm** [comment]
This is a problem kernel webkit. 
https://quiterss.org/en/node/1153
#756

**Comment by tonypachino** [comment]
"There will be special release without internal browser"
does this mean that won't be embedded browser anymore?

**Comment by Funcy-dcm** [comment]
Two versions, including without a browser.

**Comment by rat** [comment]
I have this problem, when I click on the YouTube player my quiteRSS close
