### ISSUE TITLE
QuiteRSS window stays on top

### ISSUE THREAD

**Issue by Ike39** [QuiteRSS/quiterss#1010]
For 3 days now my version 0.18.6 window sits on top of everything else and I can't Alt-tab to any another application's window.

If I minimise QuiteRss's window then I can work on other things, but then it does not appear in the Alt-tab list and I have to restart it.

Does anyone else have this aberrant behaviour, please?

**Comment by Funcy-dcm** [comment]
F10 or Menu - View - Stay on top

**Comment by Ike39** [comment]
Doh!  Partial solution as I have found that I must have hit F10 and it was in stay on top mode.  However when I clear that, although I can then Alt-tab to other windows, if I minimise QuiteRSS it still does not minimise but shuts down.

So a problem still remains.  Any solutions, please?

**Comment by Funcy-dcm** [comment]
Menu - Tools - Options - System tray

**Comment by Ike39** [comment]
Funcy-dcm

Thank you for that second reply which has enabled me to solve the problem.  How that setting came into being is a mystery to me, however, as I have never, in several years of using QuiteRSS, been into the system tray menu.

Heigh Ho, it is fixed now, and thank you again for your assistance.
