### ISSUE TITLE
Приоритет [100/100] - Неэффективное использование памяти

### ISSUE THREAD

**Issue by D1mon** [QuiteRSS/quiterss#1013]
Программа неэффективно использует память. По ходу вообще не реализовано ни какого инструмента по очистки памяти.
При прочтении непрочитанной записи rss память увеличивается и при прочтении 220 непрочитанных записей память занимает 2.15 Gb!!! А при нажатии "Пометить прочтенными"(Mark Read) очистки никакой не происходит. Что в итоге может привести к зависанию (в моем случаи очень сильного притормаживания системы).
![quiterss](https://user-images.githubusercontent.com/3872485/29742460-561a42ce-8a88-11e7-9b91-3257c210514f.png)
OS: Manjaro
QuireRss: 0.18.6-1

**Comment by Funcy-dcm** [comment]
В первую очередь мы создавали программу для себя, а для наших целей она потребляет не больше 150 Mb. Всё зависит от того как вы её используете. 

Используете ли вы встроенный браузер? Какой размер файла feeds.db? Включена ли опция "Хранить БД в памяти"
Можете сделать видео как пользуетесь программой, чтобы понять порядок действий.

**Comment by D1mon** [comment]
Используете ли вы встроенный браузер = нет
feeds.db = 9Mb
Хранить БД в памяти = нет

При запуске программа занимает 130Mb ram.
У меня ~15-20 рассылок и 1000 непрочитанных новостей.
При включении рассылки с большим кол-вом неприч. новостей память только увеличивается.
Вывод: чем больше непрочитанных новостей тем больше потребляется память, но не освобождается. Поэтому чтобы просмотреть все 1000, мне придется 3-5 раза перезапустить программу (в этом случаи память освобождается).
Еще я не сказал что не работает "Automatically mark identical news as read" из-за чего у меня 10-20% одних и тех же новостей (дубликаты).

Вот ссылка для примера:
http://feed.exileed.com/vk/feed/manacost

**Comment by Funcy-dcm** [comment]
К сожалению, у меня ссылка эта не работает.
Картинок много в ленте. Всё-таки с видео было бы понятнее.

> Еще я не сказал что не работает "Automatically mark identical news as read" из-за чего у меня 10-20% одних и тех же новостей (дубликаты).

Эта опция работает только для новой новости с таким же заголовком как в другой ленте

**Comment by D1mon** [comment]
Да забыл сказать как нужно использовать прогу.
Открываю прогу нажимаю проверить обновления рассылок потом закрываю и так несколько раз (утром, вечером) и несколько дней. Потом читаю.

Поэтому эта опция должна работать, но не работает. У есть подозрение что проблема в самих подписках. Поэтому и скинул ссылку. У меня ссылка работает в проге, а браузере нет.

Есть другие подписки там нет повторов. А те которые обновляются через данный сервис содержат повторы.

**Comment by Funcy-dcm** [comment]
Картинок много в ленте?

> Поэтому эта опция должна работать, но не работает. У есть подозрение что проблема в самих подписках. Поэтому и скинул ссылку. У меня ссылка работает в проге, а браузере нет.

Нужны скиншоты с примерами одинаковых новостей

**Comment by D1mon** [comment]
Я сделаю видео и скину на почту указанную в гите. Пойдет?

**Comment by Funcy-dcm** [comment]
Да

**Comment by Funcy-dcm** [comment]
По поводу опции: как я и говорил эта опция работает только для новой новости в ленте с таким же заголовком как у новости в **ДРУГОЙ** ленте, т.е. вам нужно включить другую опцию в свойствах ленты "Автоматическое удаление дубликатов новостей"
По поводу расхода памяти: тут проблема движка webkit встроенного браузера. Он подгружает все картинки и изображения видео в память. По сути мы генерируем большую веб-страницу. Сейчас мы разрабатываем новую версию приложения, там механизм отображения макета "газета" будет переработан
