### ISSUE TITLE
One more mistake ... Linux 0.18.6 

### ISSUE THREAD

**Issue by csola48** [QuiteRSS/quiterss#1014]
The sharing> e-mail menu option does not work perfectly yet.
After the correction, the text to be sent next to the URL to be sent is also closely linked to the short text under the URL and therefore indicates a fault on the buyer's side when opening.
Sample:
===
http://www.atv.hu/belfold/20170901-riasztast-adtak-ki-a-locky-zsarolovirus-miatt-magyarorszagon%0A%0ARiasztást adott ki a Kormányzati Eseménykezelő Központ a Locky nevű zsarolóvírus
új változatának megjelenése és terjedése miatt.
===

"...%0A%0ARiasztást" is the end of the URL!

but! 
"...orszagon%0A" is the end of the URL and
"Riasz..." and R start the text 

I'm sorry, but the program is so good that the little mistake can make eye contact :),
csola48

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
Thunderbird: 52.2.1 (32 bit)

**Comment by Funcy-dcm** [comment]
What version of the application?
Give a link to feed

**Comment by csola48** [comment]
https://launchpad.net/~quiterss/+archive/ubuntu/quiterss

**Comment by csola48** [comment]
https://launchpad.net/~quiterss/+archive/ubuntu/quiterss

**Comment by csola48** [comment]
I'm sorry for the mistake, I put the wrong ...

**Comment by Funcy-dcm** [comment]
Give a link to feed

**Comment by csola48** [comment]
Sorry, I do not understand the question ... What "feed" should I give you access / link? 

quiterss | 0.18.6-0ubuntu1~xenial | Andrey Palkin (2017-06-26)
https://launchpad.net/~quiterss/+archive/ubuntu/quiterss

**Comment by Funcy-dcm** [comment]
For example, https://quiterss.org/ru/rss.xml
News title: QuiteRSS2

**Comment by csola48** [comment]
Do you think so?
For example: http://magyaridok.hu/feed/

**Comment by Funcy-dcm** [comment]
Wait for version 0.18.8. There everything works

**Comment by csola48** [comment]
Thx...
