### ISSUE TITLE
New version 0.18.8 is much slower starting up on Windows 7 x64

### ISSUE THREAD

**Issue by antboy** [QuiteRSS/quiterss#1015]
Version 0.18.8 (24.08.2017), Revision 3742

New version 0.18.8 is much slower starting up on Windows 7 x64 - it used to be quite quick.

**Comment by Funcy-dcm** [comment]
Check for version 0.18.4 with your files feeds.db and quiterss.ini
Most likely it will work the same way. In versions 0.18.5-0.18.6 there was an error

**Comment by antboy** [comment]
Thanks for quick response.  All is good now.
I backed up the feeds.db, quiterss.ini, & backup directory, deleted everything then re-installed 0.18.8, then added back the files above.  Nice & fast again.
Great product.
