### ISSUE TITLE
Some feeds show emply content although I can see content i browser

### ISSUE THREAD

**Issue by BabakFarshchian** [QuiteRSS/quiterss#1018]
These are a couple of the feeds that show empty content in QuiteRSS while they have content when I look at them in a browser:

http://www.emeraldinsight.com/action/showFeed?type=etoc&feed=rss&jc=josm
http://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=jsra&type=etoc&feed=rss

**Comment by Glebelg2** [comment]
I confirm this issue also with this feed :
http://pubsonline.informs.org/action/showFeed?type=etoc&feed=rss&jc=mnsc
since all of them use the same format...maybe a more general issue?
Thanks

**Comment by Funcy-dcm** [comment]
I will try to solve this problem

**Comment by Glebelg2** [comment]
That would be awesome, thanks! I discovered this rss reader a few weeks ago and it's fantastic to follow and classify research papers!

**Comment by BabakFarshchian** [comment]
Thanks a lot! I found another example of the same type

http://pubsonline.informs.org/action/showFeed?type=etoc&feed=rss&jc=isre

**Comment by Glebelg2** [comment]
Excellent news, many thanks!!
Looking forward getting the update in Debian.
