### ISSUE TITLE
Следующая непрочитанная новость + горячие клавиши дали сбой

### ISSUE THREAD

**Issue by Vladimir-Vl** [QuiteRSS/quiterss#1019]
Здравствуйте!

Обновил версию 0.18.4 сразу на 0.18.8 на одном ПК.
На другом начисто установил 0.18.8 и подложил ей ini-файл и базу данных с первого ПК.

1.
Изначально активно окно списка новостей. Активна лента не имеющая непрочитанных новостей.
Если нажать кнопку следующая непрочитанная новость на панели списка новостей, то программа перейдёт с следующей непрочитанной новости в другой ленте и эта непрочитанная новость станет выделенной. Но если это действие выполнить через горячие клавиши (привязал Ctrl + PgDn), то переход произойдёт, но новость при этом не выделяется и дальнейшее управление  этой новостью с клавиатуры затрудняется. Аналогично и с предыдущей непрочитанной новостью.
В версии 0.18.4 таких проблем не было.

2. 
Я думал размер базы данных зависит от количества лент и новостей.
Но почистив все новости (около 4 тыс.) и оставив всего 8 лент новостей (было около 30) база данных уже несколько дней занимает 56 МБ. Разве она не должна была уменьшаться?

С уважением, Владимир.

**Comment by Katarn** [comment]
По второму вопросу - используйте Инструменты > Очистка. И там нижние две галки.
