### ISSUE TITLE
Конвертер Вконтакте(VK) и др. в RSS

### ISSUE THREAD

**Issue by D1mon** [QuiteRSS/quiterss#1020]
Привет. Появилась идея добавить в программу возможность конвертации группы ВК (и др. сетей) в программу.
Например: мы вставляем ссылку https:/vk.com/<group | id> она парсится и в проге показывается как обычная RSS. Конвертер сетей в RSS.

**Comment by Katarn** [comment]
http://feed.exileed.com/

**Comment by D1mon** [comment]
@Katarn спасибо конечно. Но вы думаете что я не знаю про этот сайт? Раньше работал нормально, сейчас потихоньку перестают работать фиды. Поэтому я и предлагаю сделать это в программе, чтобы работало без всяких костылей.

**Comment by Katarn** [comment]
@D1mon да просто неправильно это - тащить в приложение поддержку API/парсеров для кучи сервисов. Если только плагинами, но такой архитектуры в приложении сейчас нет, насколько я знаю. А когда их будет много - станет вообще сложно за всеми следить.

А вашу проблему можно решить простыми PHP-скриптами. К примеру:
https://github.com/esironal/vk-rss-feed
https://github.com/RSS-Bridge/rss-bridge (тут вообще несколько десятков сервисов)
Может, можно найти более удачные реализации. Устанавливаете на локальный комп, либо на арендуемый сервер, если нужно получать фиды на нескольких компах.
