### ISSUE TITLE
QuiteRSS won't launch

### ISSUE THREAD

**Issue by itsxaos** [QuiteRSS/quiterss#1022]
QuiteRSS quits during the launch process.
Error message in console:

> *** Error in `quiterss': free(): invalid pointer: 0x00007f93db9d33c0 ***
> [1]    5630 abort (core dumped)  quiterss

Same error if I launch it without ~/.config/QuiteRss/QuiteRss.ini
Let me know if you need anything else

**Comment by mac-linux-free** [comment]
same to me here
I'm on manjaro

**Comment by mac-linux-free** [comment]
found the error...oracle jre 9
installed jre 9 openjdk and quiterss starts again

**Comment by itsxaos** [comment]
I'm on arch, so I was hoping that would fix it for me too, but I still get the same error.

**Comment by mac-linux-free** [comment]
manjaro is quite similar to arch.
what does: archlinux-java status
tell you?

**Comment by itsxaos** [comment]
Available Java environments:
  java-8-openjdk/jre (default)
  java-9-jdk
  java-9-openjdk
 
I tried it with each of these just now and it didn't help. Do I have to reboot inbetween switching?

**Comment by mac-linux-free** [comment]
mine is:
archlinux-java status
Available Java environments:
  java-8-openjdk
  java-9-openjdk (default)

also delete the .cache/quiterss dir

**Comment by itsxaos** [comment]
Cache directory deleted and rebooted, still get the same error even on java-9-openjdk.

**Comment by mac-linux-free** [comment]
oh i also did this here:

https://bbs.archlinux.org/viewtopic.php?id=223069

**Comment by itsxaos** [comment]
Well thanks for the help @mac-linux-free but that didn't fix it for me either sadly, I still get the same error.

**Comment by Funcy-dcm** [comment]
Unfortunately, I can not repeat this error
