### ISSUE TITLE
How to deal with recompilation of QuiteRRS (database flushing ?)

### ISSUE THREAD

**Issue by darcosion** [QuiteRSS/quiterss#1027]
Hello.

I've recompiled QuiteRSS with Qt in release and when I do a "sudo make install", it made disappear my database.
Has it been deleted? If not, the database is recoverable ?

**Comment by darcosion** [comment]
With a search, i found a database here : `.cache/QuiteRss/QuiteRss`named "data7".
That seem to contain feed for my websites.

How i can extract or recovering this data ?

**Comment by darcosion** [comment]
Well, my old QuiteRSS his again here, so i found how to start him and extract the database in the GUI. Problem solved.
I think automatic backups could be useful to protect against upgrade losing.

**Comment by Katarn** [comment]
See the contents of ~/.local/share/data/QuiteRss/QuiteRss/backup/ path

**Comment by darcosion** [comment]
Thanks, I understand why my old QuiteRSS had again the database. :)
