### ISSUE TITLE
Problem with QuiteRSS

### ISSUE THREAD

**Issue by ID14** [QuiteRSS/quiterss#1030]
Hello,
I have problems with QuiteRSS for MacOS Sierra and High Sierra.
I have 24 sources with updates every 30 seconds and apart from that I do not receive updates every 30 seconds, but the popup almost never comes out. Then when I run from one source to another, it often freezes for 1-2 minutes and then returns to work. I rarely have to close it with Activity Monitor. With Windows 10 everything is perfect, no problem.

My iMac has these characteristics:

iMac Mid 2011

I7 2600 3.4GHz processor
Ram 4GB 1333MHz
SSD Samsung 840 EVO 256GB

How can I solve?

Thank you,
Best regards.

**Comment by Funcy-dcm** [comment]
Unfortunately, I do not have a working PC with Mac OS
