### ISSUE TITLE
Quiterss Crash on downloading feed.

### ISSUE THREAD

**Issue by vadimlitvinenko87** [QuiteRSS/quiterss#1031]
When new feed analysed and news came. News splashed in tray, after that Quiterss crashing and tray icon close. I using filter for news (~100 words in different lines). Using it with Reddit RSS (r/FreeGamesOnSteam).

[debug.log](https://github.com/QuiteRSS/quiterss/files/1540758/debug.log)
Windows7 x64
i5-3570 ~4.0GHz
8GB DDR3

**Comment by Funcy-dcm** [comment]
Does this error always occur?
You can give your database and settings file

**Comment by vadimlitvinenko87** [comment]
Последнее время не вылетает, видимо проблема имеет непостоянный характер.

2018-04-11 23:26 GMT+06:00 Shilyaev Egor <notifications@github.com>:

**Comment by Funcy-dcm** [comment]
Надеюсь, что это больше не повторится
