### ISSUE TITLE
Memory Leak - Version  18.9

### ISSUE THREAD

**Issue by The1Magoo** [QuiteRSS/quiterss#1032]
Hi..
Latest version has a really bad memory leak, grabs all available RAM within a few minutes.

System details:
Version 0.18.9 (01.12.2017)
Revision git-3750-14215b2
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.1
DISTRIB_CODENAME=serena
DISTRIB_DESCRIPTION="Linux Mint 18.1 Serena"
NAME="Linux Mint"
VERSION="18.1 (Serena)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.1"
VERSION_ID="18.1"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=serena
UBUNTU_CODENAME=xenial

Happy to investigate with you, let me know what you need..

Cheers,
Magoo

**Comment by Funcy-dcm** [comment]
Everything works well for me

**Comment by The1Magoo** [comment]
Thanks for the response.

Are you using Linux also?

**Comment by Funcy-dcm** [comment]
I'm using Windows. I apologize for not responding so long
Try the application without the configuration file and the database.
