### ISSUE TITLE
lockup with snopes stories

### ISSUE THREAD

**Issue by Elmarts** [QuiteRSS/quiterss#1034]
links in http://www.snopes.com/rss e.g. https://www.snopes.com/trump-rolls-back-rules-protecting-elderly/ lock up the program when opened in a tab or in the preview window, but open correctly in the external browser.

**Comment by Funcy-dcm** [comment]
What version of application?
Everything works well for me

**Comment by Elmarts** [comment]
Thank you for the reply, and Happy new Year

Version 0.18.9 (01.12.2017) Revision git-3750-14215b2

Includes: Qt-4.8.7, SQLite-3.11.0, WebKit-537.21
