### ISSUE TITLE
Improper page display in built-in browser

### ISSUE THREAD

**Issue by PrzemekRyk** [QuiteRSS/quiterss#1035]
Hi all,

I've noticed quite strange (for me) behavior while using built-in browser. What is wrong? For example some part of articles are displayed with italic style. Check this site for example [http://teklak.pl/2018/pierwszy-rok-z-filipem/](url) in regular browser (Chrome, Firefox). In QuiteRSS it looks like this [http://s5.ifotos.pl/img/2018-01-1_qxqrapx.png](url).

Is there any chance to correct this error?

I'm using QuiteRSS 0.18.9 portable.

Best Regards,
Przemek

**Comment by Katarn** [comment]
1. Do you use custom CSS in QuiteRSS?
2. Try to see how the site looks on the empty QuiteRSS profile.

On my system site looks good.

**Comment by PrzemekRyk** [comment]
1. No - I don't ([http://s5.ifotos.pl/img/2018-01-1_qxqrahr.png](url), [http://s10.ifotos.pl/img/2018-01-1_qxqrahx.png](url))
2. The same story. :( [http://s5.ifotos.pl/img/2018-01-1_qxqrarn.png](url)

**Comment by Katarn** [comment]
By the way, I managed to reproduce the problem.

Most likely you will need to wait for the release of QuiteRSS 2, but you can try adding the link `fonts.googleapis.com` to Adblock plugin. This can affect other sites (non-standard fonts from Google servers will stop loading), but in my opinion, sites do not look worse, and downloading becomes faster.

**Comment by PrzemekRyk** [comment]
Well - I'll wait. :)

By the way - how did you managed to reproduce this problem?

And thanks for the workaround. :)

**Comment by Katarn** [comment]
I found that above address, was added of me to AdBlock a long time ago. I just turned it off and re-check feed again.

You are welcome. If you think that the problem is exhausted - close the ticket.

**Comment by PrzemekRyk** [comment]
Well - just one question about Adblock rules. Because I'm just a little bit confused if I understand the syntax correctly. Or what I do wrong. What I want to achieve? To block stuff from fonts.googleapis.com only on specified pages. I thought that:
fonts.googleapis.com^$domain=teklak.pl
Should be enough, but it seems, that there's something wrong. :(

Could you please help mi with that?

**Comment by Katarn** [comment]
I also tried to set up a lot of time, eventually added just a domain for all sites.
