### ISSUE TITLE
Срабатывание сигнатур антивируса Kaspersky

### ISSUE THREAD

**Issue by alex-pobeditel-2004** [QuiteRSS/quiterss#1036]
Привет!  
Для информации: Kaspersky Endpoint Security 10 (Windows 10) раз в несколько дней стабильно кидает quiterss.exe в карантин. Я где-то полгода назад уже отправлял какую-то из старых версий им на проверку - они сказали, что всё ок и они исправятся - некоторое время всё было спокойно, но видимо с выходом новых версий программы продолжается то же самое :)  
Возможно, разработчики могут догадываться, какой код может казаться антивирусу подозрительным? Не знаю, как в Kaspersky с белыми списками, и можно ли как-то обеспечить QuiteRSS светлое будущее в них, но решил сообщить.  
  
![image](https://user-images.githubusercontent.com/14791483/34977754-cd0fb26c-faac-11e7-8c4d-aa19a996b7a9.png)

**Comment by Funcy-dcm** [comment]
Спасибо, что сообщили, к сожалению у Kaspersky с многими приложениями написанными на Qt такая проблема. Даже не знаю, что именно не нравится их антивирусу.
