### ISSUE TITLE
Ошибка сертификата SSL замораживает программу

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#1038]
Время от времени, где-то раз в месяц, у меня всплывает окно с "ошибкой сертификата SSL" (фотку см. [здесь](https://i.imgur.com/KU1sira.png)), которое полностью замораживает QuiteRSS. Из-за этого окна ленты на заднем фоне больше не обновляются. Только если вручную его убрать, то тогда можно дальше пользоваться программой.

Есть ли решение этой проблемы?

Пользуюсь версией 0.18.9 (01.12.2017), ревизия git-3750-14215b2 на Ubuntu 17.10.
Включает: Qt-4.8.7, SQLite-3.19.3, WebKit-537.21

**Comment by Funcy-dcm** [comment]
К сожалению, иначе не сделать. Пока в ручную не будет убран диалог с ошибкой.
