### ISSUE TITLE
QuiteRSS hangs and crashes when loading videos from feeds

### ISSUE THREAD

**Issue by masterrite** [QuiteRSS/quiterss#1044]
When loading videos from the feeds, QuiteRSS hangs and the video plays on. I'm using 0.18.9 on Windows 10 version 1709, using Intel i7-6700HQ and Nvidia 970m. Also using K-lite codec pack to handle all the decoding.

Is there any ways to not autoplay the videos?

**Comment by Funcy-dcm** [comment]
Try version: https://yadi.sk/d/-mL1zh4gMHXwt

**Comment by masterrite** [comment]
This works. The videos don't autoload now. The program also doesn't crash any more, either. Thanks!
