### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ken1943** [QuiteRSS/quiterss#1045]
Faulting application name: QuiteRSS.exe, version: 0.18.9.3750, time stamp: 0x0307de10
Faulting module name: msvcrt.dll, version: 7.0.16299.125, time stamp: 0x692918b7
Exception code: 0xc0000005
Fault offset: 0x00087f7a
Faulting process id: 0x2508
Faulting application start time: 0x01d3b22f94dce04c
Faulting application path: C:\Program Files (x86)\QuiteRSS\QuiteRSS.exe
Faulting module path: C:\WINDOWS\System32\msvcrt.dll
Report Id: c663fe50-0ccf-4166-893a-3cd83ec988fc
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Funcy-dcm** [comment]
Send video

**Comment by ken1943** [comment]
It is no longer available. This not the only error I have gotten. I get them, msvcrt.dll, just downloading news.

**Comment by Funcy-dcm** [comment]
duplicate #1051
