### ISSUE TITLE
Tired of this error at least twice a week

### ISSUE THREAD

**Issue by ken1943** [QuiteRSS/quiterss#1051]
Windows 10 Pro / 1709 keep getting this error reading, getting new news or just sitting doing nothing
Really a big pain

Faulting application name: QUITERSS.EXE, version: 0.18.9.3750, time stamp: 0x0307de10
Faulting module name: msvcrt.dll, version: 7.0.16299.125, time stamp: 0x692918b7
Exception code: 0xc0000005
Fault offset: 0x00087f7a
Faulting process id: 0x2738
Faulting application start time: 0x01d3ccd104937925
Faulting application path: C:\PROGRAM FILES (X86)\QUITERSS\QUITERSS.EXE
Faulting module path: C:\WINDOWS\System32\msvcrt.dll
Report Id: a9f4f2fd-7984-4059-872f-936515813bb9
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Funcy-dcm** [comment]
Try version: https://yadi.sk/d/-mL1zh4gMHXwt
