### ISSUE TITLE
Change settings for all feeds in a folder bug

### ISSUE THREAD

**Issue by akontsevich** [QuiteRSS/quiterss#1052]
When I try to change all feeds auto-update settings I right-click on a folder->Properties (Ctrl-E), **unset** `Automatically update every` checkbox and press ok. 

**Result:** `Automatically update every` checkbox unchecked for all feeds Properties (Ctrl-E) dialogs in that folder.

If I do reverse operation right-click on a folder, **set** `Automatically update every` checkbox and press ok. 

**Result:** `Automatically update every` checkbox **still** unchecked for all feeds Properties (Ctrl-E) dialogs in that folder.

**Comment by Funcy-dcm** [comment]
This is done specially

**Comment by akontsevich** [comment]
Bad feature, inconvenient!

**Comment by akontsevich** [comment]
Could You add such feature to enable/disable all feeds in a folder, please? I have tens of feeds in folder and it is very inconvenient to go to Properties for each feed and enable it.
