### ISSUE TITLE
Feature request: sort News Filters by column

### ISSUE THREAD

**Issue by tslabs** [QuiteRSS/quiterss#1053]
Press on the column title in 'News Filters' dialog window to sort filters by their values ('name' for example).
Reason: when number of filters grows it's not easy to find a particular filter to edit or delete it.

**Comment by Funcy-dcm** [comment]
Unfortunately, you can not sort the filters, because from their order is the work of the program.

**Comment by tslabs** [comment]
I propose to add a column with ordeal numbers for each filter and use sorting for only visual convenience.

**Comment by tslabs** [comment]
I propose to add order number for each item and use sorting for only visual convenience,
