### ISSUE TITLE
The issuer certificate of a locally lookup certificate could not be found

### ISSUE THREAD

**Issue by zmni** [QuiteRSS/quiterss#1054]
Windows 8.1
QuiteRSS 0.18.10 Portable

![quiterss](https://user-images.githubusercontent.com/841523/39040417-6be43e50-44b1-11e8-9950-2c901e3829e7.jpg)

So I just imported my opml from inoreader and above error showed up. Is it ok to make an exeption or no?

**Comment by Funcy-dcm** [comment]
This is normal
