### ISSUE TITLE
Feature Request: reopen last open tabs on restart

### ISSUE THREAD

**Issue by BGMcoder** [QuiteRSS/quiterss#1055]
Whenever we quit out of QuiteRSS, any open tabs get closed.  I would like an option to keep them open when we open the program again.  Sometimes I need a tab to stay open for quite awhile as I use it for reference.

Also, if there is an application crash, then any open tabs are lost, as well.  Maybe QuiteRSS could save them along with which feeds are read?

**Comment by Funcy-dcm** [comment]
duplicate #892
