### ISSUE TITLE
Youtube's feeds handling

### ISSUE THREAD

**Issue by RachidTagzen** [QuiteRSS/quiterss#1059]
Youtube has changed the structure of their feeds.
So, nearly 2 years ago they removed the news's thumbnail, and recently I notice that they made return this feature by adding this fields: 

```
<media:group>
   <media:title> </media:title>
   <media:content url="" type="" width="" height=""/>
   <media:thumbnail url="" width="" height=""/>
   <media:description>
```

**A Sample feed**: https://www.youtube.com/feeds/videos.xml?user=youtube

The problem is that QuiteRSS doesn't handle this new change.
Thanks.

![image](https://user-images.githubusercontent.com/25085777/39311334-8dbe182c-4964-11e8-93d7-d39614d512bc.png)

**Comment by Katarn** [comment]
It is non-standard RSS feed format. Try to use https://github.com/kevinpapst/freshrss-youtube

**Comment by RachidTagzen** [comment]
Thanks, but i hope that QuiteRSS can handle this non-standard format automatically, or at least add a new feature that let us to handle this manually.

**Comment by Funcy-dcm** [comment]
What is your OS?

**Comment by RachidTagzen** [comment]
I'm using both of Linux Mint 18.3 and windows 10.

**Comment by Funcy-dcm** [comment]
Portable: https://yadi.sk/d/-mL1zh4gMHXwt (test)

**Comment by RachidTagzen** [comment]
﻿The Youtube fix works fine until now.
But with this release the Arabic news appear ugly:
- some mixed titles (containing Arabic, Latin & Digits characters) are not fine.
- almost all Arabic news' descriptions are not fine.

I think that this is caused by: [Link](https://github.com/QuiteRSS/quiterss/commit/385ad201a5221c698f493e1d7979c64b3ab14f9c)

**NB:** All previous stable versions work fine, except this test version.

Thank you.

------------------------------------------------------------------------------------------------
![1 bad](https://user-images.githubusercontent.com/25085777/39873652-7664e3ae-5463-11e8-8abb-98f34df606ed.png)
------------------------------------------------------------------------------------------------
![1 good](https://user-images.githubusercontent.com/25085777/39873653-768cdcc4-5463-11e8-826e-6137a1dcac06.png)
------------------------------------------------------------------------------------------------
![2 bad](https://user-images.githubusercontent.com/25085777/39873654-76b4d6a2-5463-11e8-94ef-4cace444817e.png)
------------------------------------------------------------------------------------------------
![2 good](https://user-images.githubusercontent.com/25085777/39873655-76da18d6-5463-11e8-8052-303e033efc7a.png)
------------------------------------------------------------------------------------------------
![3 bad](https://user-images.githubusercontent.com/25085777/39873656-7710ab44-5463-11e8-9a6b-fcf2d4df256f.png)
------------------------------------------------------------------------------------------------
![3 good](https://user-images.githubusercontent.com/25085777/39873658-779873d0-5463-11e8-8749-12383015ece5.png)

**Comment by Funcy-dcm** [comment]
A link to feed is required.
Try: https://yadi.sk/d/CDLeurF_3HhwLv

**Comment by RachidTagzen** [comment]
This time the Arabic was fixed and works fine like previous releases.
If I note a problem with this in the future I'll inform you.

The feed in screenshots below is:     [**Link**](http://www.tech-wd.com/wd/feed/)

Thank you.

**Comment by Funcy-dcm** [comment]
In newer versions, the application will not work well. Because this is an embedded browser problem.

**Comment by RachidTagzen** [comment]
Is there a solution to handle the arabic sites, because they are ugly with the new embedded browser in the lastest QuiteRSS 0.18.12.

Thanks.

**Comment by Funcy-dcm** [comment]
@lmofallis I have a version of QuiteRSS 0.18.12, everything is fine.
Send screenshots

**Comment by RachidTagzen** [comment]
I work with **Linux Mint** most of time (currently 19), and **Windows 10** sometimes.
When I tested QuiteRSS 0.18.12 in Windows everything works fine. But in Linux the Arabic pages are badly rendered (perhaps all other RTL languages too).

NB: I have Qt 5.11.1 installed in my Linux, so I don't know if it can be the cause (perhaps it changes the webkit libraries).

Thank you.

------------------------------------------------------------------------------------------------
![3 bad](https://user-images.githubusercontent.com/25085777/39873656-7710ab44-5463-11e8-9a6b-fcf2d4df256f.png)
------------------------------------------------------------------------------------------------
![3 good](https://user-images.githubusercontent.com/25085777/39873658-779873d0-5463-11e8-8749-12383015ece5.png)

**Comment by Funcy-dcm** [comment]
Unfortunately, this problem is Webkit

**Comment by RachidTagzen** [comment]
Ok.
You have mentioned elsewhere that you will replace webkit by chromium in the new QuiteRSS2.
So, Is there a possibility to make this change in next QuiteRSS 0.18.x as a test?

Thank you.

**Comment by azmeuk** [comment]
> It is non-standard RSS feed format. Try to use https://github.com/kevinpapst/freshrss-youtube

I know time has passed and time has passed, but for the record, this is not non-standard RSS format. Is is described in the [Media-RSS specification](http://www.rssboard.org/media-rss).

**Comment by Katarn** [comment]
@azmeuk thanks, I will know now. :)
