### ISSUE TITLE
an option to set all rss layout right to left

### ISSUE THREAD

**Issue by hamidhtc** [QuiteRSS/quiterss#1062]
i changed my language to Persian,
but still the layout is left to right.
this is annoying
so i'm going to set layout right to left
but there is a problem, i have too many rss, IF i want set each rss layout right to left
it takes too much time!

[Untitled Project.zip](https://github.com/QuiteRSS/quiterss/files/1955030/Untitled.Project.zip)

**Comment by Funcy-dcm** [comment]
I understood you
