### ISSUE TITLE
problem right panel display Version 0.18.3 (26.01.2016)

### ISSUE THREAD

**Issue by raimanet** [QuiteRSS/quiterss#1063]
hi,
since a few weeks it is no longer possible to have a correct right panel after updating or purifying the flows present. in attachments 3 copies of screens 01, 02, 03.
01 after update or purification
02 after stop then restart quiterss
03 after update columns display
the system runs on Ubuntu 16.04 LTS in 64 bits
I do not see where the problem of systematic posting lies.
is there a solution ?
thank you.
greetings.
![affichage 01 2018-04-29 09-48-56](https://user-images.githubusercontent.com/38830669/39404488-7840e510-4b94-11e8-9b8a-90853b58ddc9.png)
![affichage 02 2018-04-29 09-49-46](https://user-images.githubusercontent.com/38830669/39404489-78737eee-4b94-11e8-9da9-c9dec47551b1.png)
![affichage 03 2018-04-29 09-50-20](https://user-images.githubusercontent.com/38830669/39404490-7897297a-4b94-11e8-91c1-e80a925b33ba.png)

**Comment by Funcy-dcm** [comment]
Use the latest version
