### ISSUE TITLE
after quiterss update 0.18.3 to 0.18.9

### ISSUE THREAD

**Issue by raimanet** [QuiteRSS/quiterss#1064]
Hello
after doing this update I see that the filters, labels and feeds before have all disappeared! except error the update has swept all my personal information. my question is: how to recover and reinstall these 3 posts 1-filters, 2-labels, 3-stream.
Thanks for your help.
cordially.
os: ubuntu 16.04 LTS 64-bit version

**Comment by Funcy-dcm** [comment]
Find files feeds.db and QuiteRss.ini. Copy them in new path: Help - About - Information
