### ISSUE TITLE
after update version quiterss 0.18.3 -> 0.18.9

### ISSUE THREAD

**Issue by raimanet** [QuiteRSS/quiterss#1065]
Hello
the data transfer (backup 2 files) has been done with the new version. there are 2 problems to solve:
1- the starry streams in property are well resumed but without the star!
2-the filters do not follow at all ...
is it possible not to close the question as long as this report has not been solved please?
thanks and cordial greetings.
Raimanet.

**Comment by Funcy-dcm** [comment]
You must find the files on the system. After updating the paths have been changed. This is the singularity of Qt, we did not change anything.
