### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by TotalCaesar659** [QuiteRSS/quiterss#1066]
Hello, could you update QuiteRSS version in Ubuntu PPA (https://launchpad.net/~quiterss/+archive/ubuntu/quiterss) to 0.18.10 and add Ubuntu 18.04 "Bionic Beaver" support?

**Comment by Funcy-dcm** [comment]
You need to write a package builder - https://launchpad.net/~quiterss/+archive/ubuntu/quiterss
