### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by vadimlitvinenko87** [QuiteRSS/quiterss#1067]
last version has no sound alert with wav file

**Comment by Funcy-dcm** [comment]
What revision?

**Comment by vadimlitvinenko87** [comment]
0.18.10 rev 3761

**Comment by vadimlitvinenko87** [comment]
выбираю файл формата wav, применяю, но звук не воспроизводится программой. Пробовал разные файлы в том числе родные от винды и толку нет. В ранних версиях всё было нормально. Переустановка не помогла.

**Comment by Funcy-dcm** [comment]
Можете прислать файл лога. Путь к нему можно посмотреть в "Помощь - О программе - Информация"

**Comment by vadimlitvinenko87** [comment]
https://drive.google.com/open?id=1MJmdZvxkxb8rODZ68vFX9C3Q_Aw-sVnY

**Comment by vadimlitvinenko87** [comment]
видимо это и есть ошибка

13.05.2018 09:07:08.249 WARNING: DirectShowPlayerService::doRender: Unresolved error code 80040266
13.05.2018 09:07:08.250 CRITICAL: "Error Media: 1 - "
13.05.2018 09:15:00.166 WARNING: DirectShowPlayerService::doRender: Unresolved error code 80040266
13.05.2018 09:15:00.241 CRITICAL: "Error Media: 1 - "
13.05.2018 12:17:52.268 WARNING: DirectShowPlayerService::doRender: Unresolved error code 80040266
13.05.2018 12:17:52.269 CRITICAL: "Error Media: 1 - "
13.05.2018 12:17:52.277 WARNING: DirectShowPlayerService::doRender: Unresolved error code 80040266
13.05.2018 12:17:52.277 CRITICAL: "Error Media: 1 - "

**Comment by vadimlitvinenko87** [comment]
Вопрос решен, переустановил кодеки на звук, теперь всё нормально работает. Извините за беспокойство.
