### ISSUE TITLE
Does not save when used with Qt 5.11

### ISSUE THREAD

**Issue by cfeck** [QuiteRSS/quiterss#1068]
Since updating to Qt 5.11 RC1, QuiteRSS no longer saves the "read" state of articles. When I read all of them, then exit the application, on next start they are again shown bold as "unread".

I did not recompile QuiteRSS yet.

This might be a Qt bug, but before reporting there, maybe you can confirm the issue is not in QuiteRSS.

**Comment by cfeck** [comment]
After disabling "Store DB in memory" it saves the state, so the issue is only with the save-DB-on-exit path.

**Comment by Funcy-dcm** [comment]
https://github.com/QuiteRSS/quiterss/blob/master/INSTALL

**Comment by cfeck** [comment]
Should the link tell me to use Qt 5.4? I have been using it with Qt 5.10.1 previously, and it worked fine.

**Comment by Funcy-dcm** [comment]
> I have been using it with Qt 5.10.1 previously, and it worked fine.

You just got lucky
