### ISSUE TITLE
Cloudflare blocks feed update

### ISSUE THREAD

**Issue by kwalk123** [QuiteRSS/quiterss#1076]
One of my five feeds stopped updating and I suspect Cloudflare is the cause.  After noticing the feed was giving error 403 in QuiteRSS, I tried it manually in a browser and saw that Cloudflare services were recently added to the site.  Cloudflare intercepts the feed request, displays a loading page, and then delivers the feed after determining it is a valid request.  This seems to result in an initial 403 response to QuiteRSS.

It would be greatly appreciated and useful if someone could figure out how to get QuiteRSS to work around Cloudflare's feed disruption.  They seem to be growing in popularity, and I doubt we can convince web site owners to get rid of them or not use them on their feed URLs if that is an option.

- QuiteRSS version 0.18.11 (31.05.2018) Revision 3785 on Windows Pro 10 build 1809.

- Feed URL: http://[See below]/category/tv-shows/feed/

- Update Status from QuiteRSS: Error downloading http://[See below]/category/tv-shows/feed/ - server replied: Service Temporarily Unavailable (403)

Note: The feed's host and domain is 2ddl.io -- I edited this post so they don't show as clickable links.

**Comment by rastislavcore** [comment]
Same issue. Please fix

**Comment by user9321w** [comment]
Hi, same issue here and now its permanent issue on ALL sites with cloudflare.

I suggest an option in the global settings to change User Agent string with timer to wait for cloudflare check, more info here: https://stackoverflow.com/questions/11886711/curl-cant-fetch-rss-from-website-because-of-cloudflare

Please can do something about this?

**Comment by genodeftest** [comment]
This looks like a bug in cloudflare, there is nothing QuiteRSS is doing wrong as far as I know. Have you tried contacting cloudflare instead?

**Comment by kwalk123** [comment]
@user9321w , that page looks promising if QuiteRSS has means to implement one of the suggestions.  It might be better as a feed property rather than global setting, or maybe Cloudflare can be automatically detected without need for a setting.  If your feed property for the site protected by Cloudflare has JavaScript disabled, see if enabling it works.  I just realized mine is globally disabled, and Cloudflare requires JavaScript enabled (at least in a browser).  The fix may be as simple as users enabling JavaScript for feeds protected by Cloudflare.  Of course, if you are like me, you avoid JavaScript wherever possible. :)

Unfortunately (and fortunately), I can't test this because I contacted the site that implemented Cloudflare to take their RSS feeds out of Cloudflare's scope, and they quickly figured out how to do that.

@genodeftest , it isn't a bug in Cloudflare nor is QuiteRSS doing anything wrong.  Cloudflare's means of protecting a site is to block access attempts from automated agents that could be used in a denial of service attack.  If QuiteRSS does not behave like a browser, Cloudflare will block it.  In fact, my current hypothesis I hope someone can test is to enable JavaScript in their feed property -- I think this might fix it.  Or possibly use the embedded browser (although I hope I don't have to use that).

**Comment by user9321w** [comment]
@kwalk123 hi,  i have tested it with java script enabled on a specific feed and no result.

The only way Quiterss fix this is like you said as well, if they make setting in quiterss as a feed property to be able to change the agent string and maybe a timer to wait for cloudflare to detect before sending request.

**Comment by Sonophoto** [comment]
RSS appears to be under attack. RSS makes an end run around content control systems (so called "social media") and allows independent viewpoints to be accessed without gate-keeping by controllers.

You, of course, are free to call this nonsense but please be aware of this article:

https://www.zdnet.com/article/end-nears-for-rss-firefox-64-to-drop-built-in-support-for-rss-atom-feeds-says-mozilla/

The claim is that these feeds are no longer popular. Strangely, myself and many others don't agree and we use RSS everyday...

**Comment by user9321w** [comment]
@Sonophoto that is bad news in the long run. Do you think many websites will stop supporting RSS?

@kwalk123 I managed to change the feed to an onion site feed which works and routing all feeds through TOR for now.  But this isnt a bulletproof solution for all feeds though.

**Comment by wowuser6** [comment]
You need the cookies "__cfduid", "cf_clearance" and the user-agent string of the browser which generated the cookie.

You can try this yourself by, for example

1. Visit offending url.
2. Open Console, goto Network tab and refresh
3. Inspect headers of files until you find a Cloudflare cookie
4. curl -b "Cookie: __cfduid=d788f...; cf_clearance=9d2b..." -A "Mozilla/5.0 (W..." https://website.com/feed/

I'm not a Qt programmer however a possible solution could be to

1. Inspect 403 to find if it is Cloudflare related.
2. Either, open url in background, get cookie, or render in new window, get user input, cookie and close.
3. Re-request content with cookie and user-agent

**Comment by genodeftest** [comment]
@kwalk123 : Cloudflare is breaking RSS. RSS is not meant to be fetched by a web browser but by some other software, be it a RSS Reader GUI or a search engine crawler. Both don't usually behave like web browsers.

**Comment by kwalk123** [comment]
So true, @genodeftest !  Cloudflare also breaks our ability to browse untrusted and even trusted sites with script blockers.  Sites that otherwise load fine with JavaScript blocked suddenly won't load at all because of Cloudflare.  I appreciate their protection of sites against DDoS, but they need a better method since theirs clearly breaks things.

**Comment by badpenguin** [comment]
is there a way to change the user agent? If i open the link via browser it works instead via quiterss i get 403

**Comment by kwalk123** [comment]
Not that I have seen in the options and config file, @badpenguin.  Others have requested this feature in the forum.

**Comment by topotech** [comment]
Anyone know where in the code the requests are done? I'm quite bussy to find it myself, but maybe I can do a dirty hack as a temporary fix.

**Comment by Funcy-dcm** [comment]
I will try to deal with this problem. I need a working link

**Comment by paradoxicallist** [comment]
@Funcy-dcm : https://notepad-plus-plus.org/index.xml

Not Cloudfare related, I believe, but having issues as well:
https://chromereleases.googleblog.com/feeds/posts/default
or
https://chromereleases.googleblog.com/

**Comment by Funcy-dcm** [comment]
@MrX-at-GitHub What is your OS?

**Comment by paradoxicallist** [comment]
Windows 8.1 x64 EN w/latest Security Monthly Quality Rollup

**Comment by Funcy-dcm** [comment]
Test version: http://yadi.sk/d/-mL1zh4gMHXwt
Link https://notepad-plus-plus.org/index.xml - work

**Comment by paradoxicallist** [comment]
> Link https://notepad-plus-plus.org/index.xml - work

I don't know why notepad++ website is not showing a cloudfare check in my browser today, perhaps it was a public ip address issue days back like if they blacklisted it for some reason, dunno.

Anyway your test version is working fine so far, as usual with your previous releases.

**Comment by sojusnik** [comment]
У меня даже с версией 0.19.2 (26.11.2019) на Ubuntu 19.04 проблемы с этой лентой: https://www.voltairenet.org/spip.php?page=backend&id_secteur=1110&lang=ru

Favicon ленты в QuiteRSS тоже не обновляет.
