### ISSUE TITLE
Core dumps

### ISSUE THREAD

**Issue by SaltedBacon** [QuiteRSS/quiterss#1081]
(quiterss:18455): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(quiterss:18455): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(quiterss:18455): GLib-GObject-CRITICAL **: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(quiterss:18455): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(quiterss:18455): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(quiterss:18455): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(quiterss:18455): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(quiterss:18455): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplay'

(quiterss:18455): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(quiterss:18455): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(quiterss:18455): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(quiterss:18455): GLib-GObject-CRITICAL **: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

[1]+  Segmentation fault      (core dumped) quiterss

Version 0.18.11 (31.05.2018)
Revision git-3787-d93621e

QuiteRSS is a open-source cross-platform RSS/Atom news reader
Includes: Qt-5.9.1, SQLite-3.19.3, WebKit-538.1

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"

**Comment by Funcy-dcm** [comment]
Unfortunately, with linux we can not help
