### ISSUE TITLE
0.18.11 does not save feeds state

### ISSUE THREAD

**Issue by akontsevich** [QuiteRSS/quiterss#1083]
On exit v0.18.11 does not save feeds state and recent loaded news and start to load them again on new start, so have tens unread news on every start which I had read many times.

**Comment by Katarn** [comment]
Maybe it's incorrect feed? Without news guid, for example.

**Comment by akontsevich** [comment]
I just know all worked for month, nothing changed, no new feeds, this bug just started yesterday.

**Comment by Funcy-dcm** [comment]
Send screenshot "Help - about -information" and "help - about - version"

**Comment by akontsevich** [comment]
```
Version 
0.18.11.0 31.05.2018

Application directory: 
/usr/bin
Resource directory: 
/usr/share/quiterss
Data directory: 
~/.local/share/QuiteRss/QuiteRss
Backup directory: 
~/.local/share/QuiteRss/QuiteRss/backup

Database file: 
~/.local/share/QuiteRss/QuiteRss/feeds.db
Settings file: 
~/.config/QuiteRss/QuiteRss.ini
Log file: 
~/.local/share/QuiteRss/QuiteRss/debug.log

```

**Comment by Funcy-dcm** [comment]
Qt version? OS?

**Comment by akontsevich** [comment]
Includes: Qt-5.11.0, SQLite-3.23.1, WebKit-602.1
OS: Linux openSUSE Tumbleweed

**Comment by Funcy-dcm** [comment]
Qt version <= 5.4

**Comment by akontsevich** [comment]
>Qt version <= 5.4

???!!! 11 > 4 :-)

**Comment by Funcy-dcm** [comment]
https://github.com/QuiteRSS/quiterss/blob/master/INSTALL

**Comment by akontsevich** [comment]
Hmm... That is very strange while 5.9 is LTS for now and 5.4 very old and obsolete.

**Comment by Funcy-dcm** [comment]
#1075
