### ISSUE TITLE
Add "Hacker News" as a share option

### ISSUE THREAD

**Issue by mikece** [QuiteRSS/quiterss#1084]
Please add "Hacker News" as a share option. Their API is outlined here:

https://github.com/HackerNews/API

**Comment by Funcy-dcm** [comment]
Unfortunately, I could not figure out their API

**Comment by mikece** [comment]
There's an open source Chrome add-on that does this; perhaps @adamalbrecht could help?
https://github.com/adamalbrecht/hacker-news-for-chrome

**Comment by mikece** [comment]
Below is what the code looks like in JS; I would do a PR for the C version but I don't know C. The essential thing is you're making a GET request that look like this:

`http://news.ycombinator.com/submitlink?u={URL}&t={TITLE}`

The JavaScript code from https://github.com/adamalbrecht/hacker-news-for-chrome/blob/master/core.js:

//Submit the current tab
function submitCurrentTab() {
  chrome.windows.getCurrent(function(win){
    chrome.tabs.getSelected(win.id, function(tab){
      var submit_url = "http://news.ycombinator.com/submitlink?u=" + encodeURIComponent(tab.url) + "&t=" + encodeURIComponent(tab.title);
      openUrl(submit_url, true);
    });
  });

**Comment by Funcy-dcm** [comment]
I already found, thanks. It seems everything is clear
