### ISSUE TITLE
Tumblr RSS feeds do not update after privacy policy warning implementation.

### ISSUE THREAD

**Issue by hemidragon** [QuiteRSS/quiterss#1092]
It's been nearly two months, and there's no info across the net about this issue at all.

Tried everything the QuiteRSS software can possibly do to work around the issue.

Tried the log-in trick mentioned in [https://github.com/QuiteRSS/quiterss/issues/1069](url) but the internal QRSS browser does not work with Tumblr's login screen (input field is a 1px slit, other buttons blank, input appears as a button, pressing Enter after pasting email in the slit seemingly refreshes the page instead).

Thank you for any info.

**Comment by Funcy-dcm** [comment]
Dublicate #1069
