### ISSUE TITLE
Okuma Kolaylığı

### ISSUE THREAD

**Issue by 5mesut5** [QuiteRSS/quiterss#1094]
Öncelikle bu mükemmel program için teşekkürler, emeğinize sağlık.
Daha iyi bir program için fikrim ise Haberleri tıklamadan okuma olduğunda okundu sayılmadığı için sürekli shift tuşu ile başlıkları seçerek okundu olarak işaretlemek gerekiyor, RSS başlıklarından aşağıya doğru okuma yapıldığında kalınan yerde sağ tık menüsüne **_buraya kadar okundu say_** seçeneği eklenebilirse harika olur. Teşekkürler, iyi çalışmalar

**Comment by Funcy-dcm** [comment]
Unfortunately, we can not do this. Use hotkey or context menu of news list
