### ISSUE TITLE
after latest release update, notifications sound is played repeatedly

### ISSUE THREAD

**Issue by mailinglists35** [QuiteRSS/quiterss#1096]
when i get a popup with let's say 15 news items, i get the notifications sound played 15 times.
this has not happened before update, and before the update i only got one time play for each popup, no matter how many items were in the popup

**Comment by Funcy-dcm** [comment]
What is your OS? Send screenshot "Help - About"

**Comment by mailinglists35** [comment]
win10 april 2018, https://i.imgur.com/fiBOx6N.png

**Comment by Funcy-dcm** [comment]
Send debug.log file

**Comment by mailinglists35** [comment]
[debug.log](https://github.com/QuiteRSS/quiterss/files/2232576/debug.log)

**Comment by FrancoisCardinaud** [comment]
Any news on this issue?

**Comment by Funcy-dcm** [comment]
Try the latest version
