### ISSUE TITLE
Quitrss 18.12 Getting Lots of QRRS Not Responding

### ISSUE THREAD

**Issue by dave47** [QuiteRSS/quiterss#1103]

**Comment by dave47** [comment]
lots of qrss not responding

**Comment by Robby-** [comment]
Such report, much useful. Wow.

**Comment by dave47** [comment]
Seems to be related to how many program updates are in a feed

**Comment by dave47** [comment]
windows 7 settting performance option visual effects to minimizing number of effects seems to resolve the issue.
![visual effects](https://user-images.githubusercontent.com/18049384/43675784-9ee36632-97b3-11e8-841e-a8215495d474.png)
