### ISSUE TITLE
Build fails: Project ERROR: Package sqlite3 not found

### ISSUE THREAD

**Issue by entrity** [QuiteRSS/quiterss#1109]
I've followed the instructions in `INSTALL` for both version 0.16.2 (from github) and 0.18.12 (from [webpage](https://quiterss.org/en/download)). When I run `qmake ...`, I get the following output:

```
Project MESSAGE: VCS revision: 0
Project ERROR: Package sqlite3 not found
```

This strikes me as odd, since the sqlite3 sources are in the project in the `3rdparty` directory.

**Comment by genodeftest** [comment]
Maybe you still need to install SQlite (+devel headers) to your operating system?

**Comment by entrity** [comment]
@genodeftest : that makes sense. I've moved on and am using another solution at this time, so I'll terminate this thread here.
