### ISSUE TITLE
What the hell is ganalytics.h?

### ISSUE THREAD

**Issue by Ola-Ponny** [QuiteRSS/quiterss#1111]
I just noticed this in the source code (after first seeing a suspicious variable name in the backup file):

https://github.com/QuiteRSS/quiterss/blob/ad0acb4fa7b2f67008f9eda85900c94fea3efb44/3rdparty/ganalytics/ganalytics.h

It literally says: "send google tracking data"

WHAT?! Is QuiteRSS sending data from my computer to Google without telling me? If this is true... I have no words. I've been deceived for all this time?

**Comment by Ola-Ponny** [comment]
"only includes some user identification information"

The fact that it's done AT ALL makes me immediately start to look for an alternative to this spyware. Thanks for sending "some" of my private data to this fucking evil corporation that I've done everything to avoid for many years... All the time QuiteRSS was doing it without telling me, pretending to be on my side... Absolutely sickening.

**Comment by Katarn** [comment]
@Ola-Ponny, have a drink of validol. What prevented you all these years to see in the application settings in the GENERAL section?

**Comment by Ola-Ponny** [comment]
I'd rather not drink any drugs, no. It's NOT up to the user to prevent the software from spying on them. This is absolutely perverse.

**Comment by Katarn** [comment]
We know your name, hahaha! >:-D
Analytics is not spying. Is just analytics. Just relax.

**Comment by Funcy-dcm** [comment]
What is included in the analytics:
- _userAgent
-  _userLanguage
- _screenResolution
- _appName
- _appVersion

**Comment by genodeftest** [comment]
> I know your name, hahaha! >:-D
> Analytics is not spying. Is just analytics. Just relax.

That depends on your definition of privacy. The "new" (2016) EU regulation (GDPR) does not allow to share this data without explicit user consent because it gives data to a third party. Together with the IP address, these pieces of data may be enough to uniquely identify a user. The data is given to Google who provide the analytics server.

**Comment by Katarn** [comment]
GDPR refers only to commercial companies doing business in the EU. QuiteRSS is non-commercial project and its developers are not in the EU. But even in this case, they agreed to add a warning dialog in the next version: https://github.com/QuiteRSS/quiterss2/issues/3#issuecomment-406988093

This issue is only about your personal inattention. You and fix it. :)

**Comment by genodeftest** [comment]
> GDPR refers only to commercial companies doing business in the EU.

That is incorrect. GDPR applies to any organization, commercial or non-commercial. This includes organizations such as NGOs, foundations or sports clubs.

> QuiteRSS is non-commercial project and its developers are not in the EU.

> GDPR applies to where the software or service is being used, not to where it is being provided.

**Comment by Katarn** [comment]
> That is incorrect. GDPR applies to any organization, commercial or non-commercial. This includes organizations such as NGOs, foundations or sports clubs.

QuiteRSS is not registered as organization. No legal person to be brought to justice.

> No, the GDPR applies to where the software or service is being used, not to where it is being provided.

This is true, but again, there is no legal person to be brought to justice. Who should be fined?

> I do not understand. What do you mean?

You blamed the developers of the application for deliberately spying on users, but its source code is open, there is no specially tangled code in it, and even the analytics file is called a ganalytics.h, not jfhdjgd.cpp (for example). In the app settings (in the general section - the most important settings!) there is an checkbox that can be disabled. And text on it is not misleading.

You blamed the developers for spying on you for years without informing you about it (referring to the GDPR, which was adopted only a few months ago, after the last major update of the application, which, by the way, has almost stopped of development).

This ticket is only about one thing - you are inattentive yourself. You need to work more on your attention. When the problem will be resolved, you can safely to request of @Funcy-dcm for it to set a status to fixed. :)
