### ISSUE TITLE
Under a GNOME/Wayland session, QuiteRSS cannot start with Qt 5.11

### ISSUE THREAD

**Issue by genodeftest** [QuiteRSS/quiterss#1112]
## Steps to reproduce:
1. Log in to a GNOME/Wayland session.
2. Start QuiteRSS

## What happens:
Immediate crash on startup. See the [downstream bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1630184) for a [full backtrace](https://bugzilla.redhat.com/attachment.cgi?id=1484256).

## What should happen:
No crash

## Installed software version information (Fedora 28):
qt5-qtbase-5.11.1-7.fc28.x86_64
qtsingleapplication-qt5-2.6.1-32.fc28.x86_64
quiterss-0.18.12-1.fc28.x86_64 (Custom build from source, just enabled Qt5)
gnome-shell-3.28.3-1.fc28.x86_64

## Additional information:
This crash does not happen with Qt versions below 5.11.

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1630184

On a GNOME/Xorg session, QuiteRSS starts fine.

**Comment by genodeftest** [comment]
In the backtrace, when having a look into `LogFile::msgHandler()` (src/application/logfile.cpp:40, frame 5 in the backtrace), QuiteRSS tries to log a message to the log file. At this point, `MainApplication::checkDir()` (src/application/mainapplication.cpp:174) has not been called. As a result, the data directory has not been initialized and `mainApp->dataDir()` is invalid in `LogFile::msgHandler()`.  The code does not catch this case and thus causes invalid memory access causing a SEGV.

The crash only happens on Qt 5.11 because that added logging to platform integration detection in `QGuiApplicationPrivate::createPlatformIntegration()` (src/gui/kernel/qguiapplication.cpp:1285) per [this commit](https://code.qt.io/cgit/qt/qtbase.git/commit/src/gui/kernel/qguiapplication.cpp?h=5.11.2&id=36d2ef5af9875afd9d398f5e37102194040cb1d9).

**Comment by genodeftest** [comment]
Real fix:
* Make sure to initialize the logging subsystem before instantiating `MainApplication`.

Possible workarounds:
* Explicitly specify `QT_QPA_DEFAULT_PLATFORM_NAME` at build time.
* Use a Xorg session instead
* Unset `XDG_SESSION_TYPE` as this will prevent Qt 5.11 platform detection in `QGuiApplicationPrivate::createPlatformIntegration()`, automatically falling back to X11 backend. This may or may not have side effects, I have not checked that.

Problem with the first workaround:
QuiteRSS now crashes on a second place when logging `QSocketNotifier: Can only be used with threads started with QThread`, also before `mainApp->dataDir()` has been initialized. This also happens only on Wayland.

**Comment by Funcy-dcm** [comment]
Read INSTALL: https://github.com/QuiteRSS/quiterss/blob/master/INSTALL

**Comment by genodeftest** [comment]
> Read INSTALL: https://github.com/QuiteRSS/quiterss/blob/master/INSTALL

I don't know exactly why I should read that document. If you want to tell me that Qt 5.11 is not supported: Qt 5.4 is out of support for more than 1 year. Even Ubuntu 16.04LTS ships a more recent version of Qt.

**Comment by genodeftest** [comment]
Can you please fix this crasher bug?

**Comment by berrange** [comment]
This bug means quiterss is dead out of the box in any modern distros that are using Wayland, which is not giving a good impression to users :-(

If it isn't easy to fix the root cause under Wayland, then at least set it to force use of X11 at build time or runtime so that it doesn't immediately crash in normal usage.

**Comment by Funcy-dcm** [comment]
fix: 708603daf5ee2b097150f2945d1749bf98c3a0bb
