### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by dave47** [QuiteRSS/quiterss#1121]
I get this many times.

Faulting application name: QuiteRSS.exe, version: 0.18.12.3794, time stamp: 0x00000000
Faulting module name: Qt5Network.dll, version: 5.4.2.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00040215
Faulting process id: 0x840
Faulting application start time: 0x01d47518daf94658
Faulting application path: C:\Program Files (x86)\QuiteRSS\QuiteRSS.exe
Faulting module path: C:\Program Files (x86)\QuiteRSS\Qt5Network.dll
Report Id: d43b8614-e123-11e8-950b-e017dcaca184

**Comment by Katarn** [comment]
Does this happen at the time of updating the feeds list or opening the news in the built-in browser?
