### ISSUE TITLE
Очистка новостей больше не работает

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#1135]
В последней версии QuiteRSS (0.18.12) автоматическая очистка новостей при завершении и мануальная (меню > инструменты > очистка) больше не работают. Пользуюсь Ubuntu 18.10.

Заранее благодарен!

**Comment by sojusnik** [comment]
Поудалял вручную около 50 000 новостей, очистил корзину, перезагрузил, но размер `feeds.db` так и не изменился. Может это как-то связанно?

**Comment by Funcy-dcm** [comment]
Путь к файлу `feeds.db` смотрели в `Помощь - О программе - Информация`?

**Comment by sojusnik** [comment]
Конечно!

Всё как положено: `~/.local/share/QuiteRss/QuiteRss/feeds.db`, см. [здесь](https://i.imgur.com/8Jk49Pq.png) и [здесь](https://i.imgur.com/eeqHW7e.png).

Не знаю как найти число всех новостей, но непрочитанных у меня 70 000. `feeds.db` как весило (до мануальной чистки), так и весит 690MB.

Замечаю, что, скорее всего после последнего обновления, QuiteRSS закрывается за секунду, хотя раньше на это уходило примерно 10-20 секунд с включенной "оптимизацией БД" в настройках.

**Comment by Funcy-dcm** [comment]
Можно скрин настроек очистки? У меня всё работает, вот  только проверил

**Comment by sojusnik** [comment]
[Пожалуйста](https://i.imgur.com/FJdFDes.png)!

**Comment by Funcy-dcm** [comment]
Опцию "Очищать удалённые" отключали?

**Comment by sojusnik** [comment]
Так в моём скрине она уже отключена.

Что с очищением "удалённых", что без — они при выключении не удаляются. Только что проверил.

**Comment by Funcy-dcm** [comment]
А точно, с включенной, попробуйте отметить новостей 50 прочитанными и закрыть, увидете, что на 2мб меньше стало. Только таких новостей чтобы они за 180 дневный период выходили

**Comment by sojusnik** [comment]
У Вас случайно "хранить БД в памяти" не включено? Если я эту опцию включаю, то очистка при завершении начинает работать! Но очистка, та которая в меню, до сих пор не работает.

**Comment by sojusnik** [comment]
> А точно, с включенной, попробуйте отметить новостей 50 прочитанными и закрыть, увидете, что на 2мб меньше стало. Только таких новостей чтобы они за 180 дневный период выходили

Работает только с БД в памяти. Но я её отключаю, поскольку занимает примерно в два раза больше RAM.

**Comment by Funcy-dcm** [comment]
Попробуйте с 0.19.2

**Comment by sojusnik** [comment]
Жду пока Андрей Палкин обновит PPA для Ubuntu. Написал ему мейл пару дней назад, но не получил ответа.

Егор, ещё раз спасибо, что Вы поддерживаете Вашу прекрасную прогу!

**Comment by sojusnik** [comment]
С 0.19.2 с и без БД в памяти очистка мануальная и при завершении опять работают!
Спасибо вам и Андрею :)
