### ISSUE TITLE
Удаление дубликатов новостей

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#1136]
Пользуюсь [лентой](https://politepol.com/feed/47828), в которой периодически (иногда хватает обновить ленту в течение 10 секунд, а иногда подождать до 10 минут) меняются URL новостей. Заголовки при этом **не меняются**. Включил "автоматическое удаление дубликатов новостей" в свойствах ленты, но старые новости при обновлении ленты не удаляются, видимо из-за нового URL.

Это так задумано? Если нет, то можно при удалении дубликатов тоже учитывать и заголовок новостей?

Наблюдается на версии 0.18.12 с Qt-5.9.5, SQLite-3.24.0, WebKit-602.1 на Ubuntu 18.10.

**Comment by sojusnik** [comment]
Если не трудно, то было бы очень удобно иметь эту функцию внутри папки. Таким образом во всех в ней находящихся лентах можно разом удалить дубликаты.

**Comment by Funcy-dcm** [comment]
При обновлении папки или ленты?

Если ссылка на новость отличается, то считается что это другая новость

**Comment by sojusnik** [comment]
> При обновлении папки или ленты?

Так точно!

> Если ссылка на новость отличается, то считается что это другая новость

Значит дубликаты только по ссылке определяются? А можно добавить в настройках чтобы тоже учитывались заголовки? Или это скорее всего приведёт к неожиданным результатам?

В любом случае, большое спасибо за отличную программу!

**Comment by Funcy-dcm** [comment]
Я так и не понял папка или лента? ))

Дубликаты определяются по названию, далее сравнивается ссылка или ИД

**Comment by sojusnik** [comment]
> Я так и не понял папка или лента? ))

:D

Вас смутило:

>> Включил "автоматическое удаление дубликатов новостей" в свойствах ленты, но старые новости при обновлении папки не удаляются, видимо из-за нового URL.

Это оЧеПяТкА :) Речь конечно же идёт о ленте. Сейчас исправлю.

**Comment by Funcy-dcm** [comment]
Теперь всё понятно, но, к сожалению, всё равно с этим вопросом не смогу помочь - как и писал выше, алгоритм менять не вижу смысла

**Comment by sojusnik** [comment]
Ясно. Всё-равно спасибо за желание помочь!
