### ISSUE TITLE
Не отображаются новости из Bing Search

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#1137]
В [Bing Search](https://www.bing.com/?cc=ru) можно получать результаты в RSS формате, если к URL добавить `&format=rss`. Но они почему-то не отображаются в QuiteRSS, хотя работают в Firefox, если например пользоваться [этим](https://addons.mozilla.org/de/firefox/addon/rsspreview/) или [этим](https://addons.mozilla.org/de/firefox/addon/feed-preview/) плагином. Плагины нужны, поскольку Firefox, по-моему, с 63 или 64 версией удалил возможность просматривать RSS фиды в самом браузере.

Для примера:

В первом поиске ищем всё за последние дни в России о "linux", пусть показывает максимум 50 результатов. Соответствующая ссылка выглядит вот так:

https://www.bing.com/search?q=linux&cc=ru&rf=1&tbs=qdr:d&count=50&format=rss

Если её добавить в QuiteRSS, то почему-то отображаются первые 10 результатов, которые соответствуют этому поиску:

https://www.bing.com/search?q=linux

Взято, видимо, [отсюда](https://i.imgur.com/b1ySy9o.png). 

А если на русском искать, то вообще никаких результатов в QuiteRSS:

https://www.bing.com/search?q=линукс&cc=ru&rf=1&tbs=qdr:d&count=50&format=rss

Но в Firefox и там и там достаточно результатов.

В начале думал, что это связанно исключительно с раскладкой — если искать латиницей (= linux), то показывает только результаты домашней страницы (см. [здесь](https://i.imgur.com/b1ySy9o.png)), а кириллицей (= линукс), то вообще не работает.

Но если поискать "quiterss", то почему-то тоже ничего не показывает в QuiteRSS, хотя в Firefox результаты отображаются:

https://www.bing.com/search?q=quiterss&cc=ru&rf=1&tbs=qdr:d&count=50&format=rss

Надеюсь на Вашу помощь!

**Comment by sojusnik** [comment]
И ещё странный нюанс:

Если в первой ссылке

https://www.bing.com/search?q=linux&cc=ru&rf=1&tbs=qdr:d&count=50&format=rss

поменять регион с России на Австрию (cc=at, вместо cc=ru)

https://www.bing.com/search?q=linux&cc=at&rf=1&tbs=qdr:d&count=50&format=rss

то почему-то появляются результаты для Австрии, если поменять обратно на Россию — никакого эффекта!

**Comment by Funcy-dcm** [comment]
Проблему вижу, надо будет поковырять на досуге

**Comment by sojusnik** [comment]
Вы уже смогли найти время, чтобы разобраться в этом вопросе?
Может как-нибудь могу помочь с моей стороны?

**Comment by sojusnik** [comment]
С версией 0.19.4 всё заработало! Вам, как всегда, огромное спасибо!
