### ISSUE TITLE
"Can't find feed URL" when feed is on dropbox

### ISSUE THREAD

**Issue by Alexus9** [QuiteRSS/quiterss#1149]
For the website that I manage I offer the feed at dropbox:
https://www.dropbox.com/s/nt67389s7lrzcs0/evbf-feed.xml?dl=1
(That’s my choice because Jimdo doesn’t support feeds.)
QuiteRSS says „Can't find feed URL!“.
I tested FeedReader, Klipfolio and Flym, they can read this feed successfully.
(QuiteRSS 0.18.12)

**Comment by Funcy-dcm** [comment]
Corrected. Expect New Version
