### ISSUE TITLE
Can't find feed URL for http://kenrockwell.com/rss.php

### ISSUE THREAD

**Issue by ScoobyDone** [QuiteRSS/quiterss#1150]
Feed is valid per 
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fkenrockwell.com%2Frss.php

tried both http and https.

Version 0.18.12 (02.07.2018)
Revision 3794
Win 7 x64

**Comment by Katarn** [comment]
`curl -vvv http://kenrockwell.com/rss.php`

```
...
<html>
<head>
<META NAME="robots" CONTENT="noindex,nofollow">
<script src="/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3">
</script>
<body>
</body></html>
```

This is not a valid feed. This page, which first checks some security protection through JS, records the result of the check in the cookie, and then reloads of himself. And only with this cookie, if it is valid, creates the contents of the feed. Contact the site administrator, tell him that he uses page protection that is not provided for in the RSS standard.

**Comment by ScoobyDone** [comment]
thanks.  good info.
