### ISSUE TITLE
Need to uninstall to reinstall

### ISSUE THREAD

**Issue by JamesQ16** [QuiteRSS/quiterss#1152]
I love this program!   It's so powerful and so easy to use!

I do have one problem now.   I was messing around with the installer and must have done something because every time it finishes populating the RSS feeds, the program automatically closes.

I tried to uninstall the program, but when I reinstall, all my feeds are there.  I try to delete the feeds, by right clicking the "My Feeds" parent and select Delete and the program will close again.  If I uninstall it, shouldn't all my feeds go away?   How can I completely uninstall this program to reinstall fresh?

 I really want to use this!  

Please Help!!

James

**Comment by Funcy-dcm** [comment]
Try version 0.19.3
