### ISSUE TITLE
Clean up not deleting old entries

### ISSUE THREAD

**Issue by Joel889** [QuiteRSS/quiterss#1155]
Old feeds entries from several years ago, don't disappear after using the cleaning wizard.
Global settings say 30 day feed retention, manual clean up also set to 30 days retention. All items are red, non are starred or tagged.

This can be observed by the default QuiteRSS feed.

**Comment by sojusnik** [comment]
Did you deactivate "keep DB in memory" (or similar) in the settings? Try to enable it, restart, and repeat the cleaning. This was mentioned [here](https://github.com/QuiteRSS/quiterss/issues/1135) before, but in Russian.

**Comment by Funcy-dcm** [comment]
Try version 0.19.2

**Comment by sojusnik** [comment]
Works again with 0.19.2!

**Comment by sojusnik** [comment]
Let's close it then?
