### ISSUE TITLE
Closing every 5 minutes

### ISSUE THREAD

**Issue by bilou47190** [QuiteRSS/quiterss#1159]
Hello,

The program closes itself without any intervention on my part. 
Version 0.18.12  version under windows 7 pro
Bilou

**Comment by genodeftest** [comment]
Without logfiles, there is nothing we can do.

Can you please try to disable all plugins?

**Comment by bilou47190** [comment]
Hello,
I don't have a plugin.
[debug.log](https://github.com/QuiteRSS/quiterss/files/3132679/debug.log)
Is this the right log file ?
Bilou

**Comment by genodeftest** [comment]
That does not look like the right file.

**Comment by bilou47190** [comment]
in which directory is the file? What's his name?

Version 
0.18.12.3794 02.07.2018

Application directory : 
C:/Program Files (x86)/QuiteRSS

Resource Directory : 
C:/Program Files (x86)/QuiteRSS

Data directory : 
C:/Users/Bilou47190/AppData/Local/QuiteRss/QuiteRss

Backup directory : 
C:/Users/Bilou47190/AppData/Local/QuiteRss/QuiteRss/backup

Database file : 
C:/Users/Bilou47190/AppData/Local/QuiteRss/QuiteRss/feeds.db

Parameter file : 
C:/Users/Bilou47190/AppData/Roaming/QuiteRss/QuiteRss.ini

Log File : 
C:/Users/Bilou47190/AppData/Local/QuiteRss/QuiteRss/debug.log

Excuse me, I'm French.

**Comment by genodeftest** [comment]
Sorry, I don't know where to find it.

**Comment by Funcy-dcm** [comment]
Try test version: http://yadi.sk/d/-mL1zh4gMHXwt
