### ISSUE TITLE
SSL certificate error with AdGuard

### ISSUE THREAD

**Issue by chinese-maintainer** [QuiteRSS/quiterss#1169]
![2019-05-20_125202](https://user-images.githubusercontent.com/33459878/58013483-58687280-7aff-11e9-8327-f1a68f719465.png)
Together with AdGuard and filtration HTTPS traffic constantly asks to add certificates to exceptions

**Comment by sojusnik** [comment]
Do you mean the built-in ad-blocker AdBlock with "AdGuard"?

Did you find a solution how to get rid of those SSL error windows?

This issue is also mentioned [here](https://github.com/QuiteRSS/quiterss/issues/1133).

**Comment by Funcy-dcm** [comment]
#1133
