### ISSUE TITLE
No notification sound

### ISSUE THREAD

**Issue by stevem6** [QuiteRSS/quiterss#1170]
Newly installed QuiteRSS 0.18.8 on Linux Mint 19.1. The notification sound doesn't play and there's no error or mention of this in debug.log

I tried useMediaPlayer=false in QuiteRss.ini [Settings] but it makes no difference. 

Grateful for any help.

**Comment by stevem6** [comment]
Delighted to say that I have solved it! Removing useMediaPlayer=false in QuiteRss.ini [Settings] gave me the error that I needed in debug.log

```
WARNING: defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
CRITICAL: "Error Media: 5 - The QMediaPlayer object does not have a valid service"
```

which I could research. Thanks to [https://stackoverflow.com/questions/47524552/qt-no-service-found-for-org-qt-project-qt-mediaplayer](https://stackoverflow.com/questions/47524552/qt-no-service-found-for-org-qt-project-qt-mediaplayer) the solution was

`sudo apt-get install libqt5multimedia5-plugins`

and restart QuiteRSS. 

Hope this helps others.

**Comment by paul1149** [comment]
Perfect. Thank y ou.
