### ISSUE TITLE
Olx.ua rss just stop working

### ISSUE THREAD

**Issue by Rockbard** [QuiteRSS/quiterss#1171]
Here is the test link https://www.olx.ua/nedvizhimost/doma/prodazha-domov/odessa/rss/?search%5Bfilter_float_price%3Ato%5D=75000&search%5Bfilter_enum_property_type_houses%5D%5B0%5D=house&search%5Bfilter_enum_property_type_houses%5D%5B1%5D=club_house&search%5Bfilter_enum_property_type_houses%5D%5B2%5D=cottage&search%5Bfilter_enum_property_type_houses%5D%5B3%5D=townhouse&search%5Bfilter_enum_property_type_houses%5D%5B4%5D=country_house&search%5Bfilter_enum_property_type_houses%5D%5B5%5D=duplex&search%5Bdistrict_id%5D=85&currency=USD

**Comment by aidaho** [comment]
They are now serving html bot-protection warning instead of RSS XML.  

I've contacted them about it, but I don't think I've gotten my message through tech support to the dev team.

**Comment by Rockbard** [comment]
Would be great if this problem could be fixed

пн, 10 июн. 2019 г., 12:01 Sergey Frolov <notifications@github.com>:

**Comment by aidaho** [comment]
> Would be great if this problem could be fixed

One can't fix that by complaining in QuiteRSS bugtracker.
You should annoy OLX tech support, just as I did.

**Comment by Rockbard** [comment]
Oh, got it. Thank you though

пн, 10 июн. 2019 г., 23:29 Sergey Frolov <notifications@github.com>:

**Comment by kjacewicz** [comment]
I had the same problem with olx.pl. They introduced User Agent checking. QuiteRss with 'User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/538.1 (KHTML, like Gecko) QuiteRSS/0.18.12 Safari/538.1' just fails. Now I'm using Fiddler to change UA.

It would be nice to have UA change option in QuiteRSS...

**Comment by aidaho** [comment]
> I had the same problem with olx.pl. They introduced User Agent
> checking. QuiteRss with 'User-Agent: Mozilla/5.0 (Windows NT 6.1)
> AppleWebKit/538.1 (KHTML, like Gecko) QuiteRSS/0.18.12 Safari/538.1'
> just fails. Now I'm using Fiddler to change UA.
> 
> It would be nice to have UA change option in QuiteRSS...
> 

Thanks for the tip.

I've tried spoofing UA through Squid and although web browser with
empty profile does receive RSS XML, QuiteRSS with same UA does not.
Seems like they might do more profiling than that.

Have you spoofed and/or removed any other headers to get it to work or
was it just UA that did the trick for you?

**Comment by Katarn** [comment]
Validate feed here: http://www.feedvalidator.org/

**Comment by aidaho** [comment]
I've got it working!

Looks like OLX marked me with a cookie. I've deleted them before doing
my previous test from the UI, but that apparently didn't work.
All I had to do is to disable saving cookies and restart QuiteRSS to
get rid of the session.

Everything works again now.

Thank you for the workaround, kjacewicz!

**Comment by Funcy-dcm** [comment]
Corrected. Expect New Version
