### ISSUE TITLE
Rutor - Таймаут запроса! 

### ISSUE THREAD

**Issue by IAmSelf** [QuiteRSS/quiterss#1172]
**QuiteRSS 0.8.12 (3794)**

http://alt.rutor.info/rss.php?full=1
Не открываются каналы.
IE - открывает
FeedDemon - открывает
RSSOwl - открывает
QuiteRSS - НЕ открывает :-(

**Comment by Funcy-dcm** [comment]
У меня всё работает. Дайте скриншот

**Comment by IAmSelf** [comment]
> У меня всё работает. Дайте скриншот

Ну, за 4 месяца на сайте, судя по всему, подправили это дело... Теперь и у меня работает
