### ISSUE TITLE
Keeps crashing when refreshing feeds

### ISSUE THREAD

**Issue by sus390** [QuiteRSS/quiterss#1175]
when run in terminal:
Segmentation fault (core dumped)

Starting program: /usr/bin/quiterss 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe4efd700 (LWP 29483)]
[New Thread 0x7fffe0a6d700 (LWP 29484)]
[New Thread 0x7fffdb14a700 (LWP 29485)]
[New Thread 0x7fffd1d64700 (LWP 29486)]
[New Thread 0x7fffd1563700 (LWP 29487)]
[New Thread 0x7fffd0d62700 (LWP 29488)]
[New Thread 0x7fffbfbb4700 (LWP 29489)]
[New Thread 0x7fffbe0cd700 (LWP 29490)]
[New Thread 0x7fffbd8cc700 (LWP 29491)]
[New Thread 0x7fffbd0cb700 (LWP 29492)]
[New Thread 0x7fff767ff700 (LWP 29493)]
[New Thread 0x7fff75ffe700 (LWP 29494)]
[New Thread 0x7fff757fd700 (LWP 29495)]
[New Thread 0x7fff74ffc700 (LWP 29496)]
[New Thread 0x7fff5ffff700 (LWP 29497)]
[New Thread 0x7fff5f7fe700 (LWP 29498)]
[New Thread 0x7fff5effd700 (LWP 29500)]
[New Thread 0x7fff5e7fc700 (LWP 29501)]
[Thread 0x7fff5effd700 (LWP 29500) exited]
[New Thread 0x7fff5effd700 (LWP 29505)]
[New Thread 0x7fff5dbf1700 (LWP 29506)]
[New Thread 0x7fff5d3f0700 (LWP 29507)]
[New Thread 0x7fff5cbef700 (LWP 29508)]
[New Thread 0x7fff3bfff700 (LWP 29509)]
[New Thread 0x7fff3b7fe700 (LWP 29510)]
[New Thread 0x7fff3affd700 (LWP 29511)]
[Thread 0x7fffd0d62700 (LWP 29488) exited]
[New Thread 0x7fffd0d62700 (LWP 29512)]
[Thread 0x7fffd0d62700 (LWP 29512) exited]
[Thread 0x7fff3affd700 (LWP 29511) exited]
[Thread 0x7fff5cbef700 (LWP 29508) exited]
[Thread 0x7fff5d3f0700 (LWP 29507) exited]
[Thread 0x7fff5dbf1700 (LWP 29506) exited]
[Thread 0x7fff5e7fc700 (LWP 29501) exited]
[New Thread 0x7fff5e7fc700 (LWP 29532)]
[New Thread 0x7fff5dbf1700 (LWP 29533)]

Thread 20 "QNetworkAccessM" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff5effd700 (LWP 29505)]
0x00007ffff30e00d4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
Quit
Error detected on fd 0
error detected on stdin
Starting program: /usr/bin/quiterss 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe4efd700 (LWP 29744)]
[New Thread 0x7fffe0a6d700 (LWP 29745)]
[New Thread 0x7fffdb14a700 (LWP 29746)]
[New Thread 0x7fffd1d64700 (LWP 29747)]
[New Thread 0x7fffd1563700 (LWP 29748)]
[New Thread 0x7fffd0d62700 (LWP 29749)]
[New Thread 0x7fffbfbb4700 (LWP 29750)]
[New Thread 0x7fffbe0cd700 (LWP 29751)]
[New Thread 0x7fffbd8cc700 (LWP 29752)]
[New Thread 0x7fffbd0cb700 (LWP 29753)]
[New Thread 0x7fff767ff700 (LWP 29754)]
[New Thread 0x7fff75ffe700 (LWP 29755)]
[New Thread 0x7fff757fd700 (LWP 29756)]
[New Thread 0x7fff74ffc700 (LWP 29757)]
[New Thread 0x7fff5ffff700 (LWP 29758)]
[New Thread 0x7fff5f7fe700 (LWP 29759)]
[New Thread 0x7fff5effd700 (LWP 29760)]
[New Thread 0x7fff5e7fc700 (LWP 29761)]

Thread 18 "QNetworkAccessM" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff5effd700 (LWP 29760)]
0x00007ffff30e00d4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#0  0x00007ffff30e00d4 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#1  0x00007ffff30deca2 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#2  0x00007ffff2736122 in QObject::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff6f2482c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff6f2c0f4 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff27069a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff270911d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff27602c3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fffece96317 in g_main_context_dispatch ()
   from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007fffece96550 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007fffece965dc in g_main_context_iteration ()
   from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff275f8ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff27049ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff252322a in QThread::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff252816d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff22646db in start_thread (arg=0x7fff5effd700)
    at pthread_create.c:463
#16 0x00007ffff19ec88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
Quit
Error detected on fd 0
error detected on stdin

**Comment by feed21** [comment]
I believe im having the same problem on Ubuntu 18.04.  Quiterss would crash every so often within the hour with no crash related errors in the debug.log file.

This started happening since the latest package updates to libqt on the 11 June when i updated.
@Funcy-dcm please can you have a look at this?

**Comment by sus390** [comment]
The problem disappeared after I switched off DoH

**Comment by sojusnik** [comment]
DoH?

**Comment by sus390** [comment]
DNS over https.

**Comment by Elmarts** [comment]
I don't have DNS over HTTPS, but QSS keeps randomly freezing.  Process lists shows it "sleeping", and I hve to kill the process from there before I can start the program again.  Mint 19.1 Mate desktop btw.

**Comment by sus390** [comment]
Maybe U could switch to another DNS which has lower latency.Qss works perfectly after I had switched to a local DNS,set longer timeout to 30s and once for number of requests and retries.

**Comment by feed21** [comment]
I have found out that this is an issue from qt5 not from QuiteRSS, a fix has been released and should be in all your repo's soon when you upgrade your distro packages.

Issue reported here: https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1833536

You may close this issue here now.
