### ISSUE TITLE
clean up not working

### ISSUE THREAD

**Issue by hamidhtc** [QuiteRSS/quiterss#1181]
why clean up tools is not working for me?

**Comment by sojusnik** [comment]
Please be more specific.

Did you deactivate "keep DB in memory" (or similar) in the settings? Try to enable it, restart, and repeat the cleaning. This was mentioned [here](https://github.com/QuiteRSS/quiterss/issues/1135) before, but in Russian.

**Comment by hamidhtc** [comment]
> Please be more specific.
> 
> Did you deactivate "keep DB in memory" (or similar) in the settings? Try to enable it, restart, and repeat the cleaning. This was mentioned [here](https://github.com/QuiteRSS/quiterss/issues/1135) before, but in Russian.
i want to keep just feeds for 2days and the older should be clean on shutdown but the clean up tools not working
this is my setting:
https://i.imgur.com/tHz7VFy.jpg
https://i.imgur.com/Lecihw9.jpg

**Comment by Jorenar** [comment]
> Did you deactivate "keep DB in memory" (or similar) in the settings?

No, I didn't at first, but tried to deactivate and activate again - nothing has changed.

------

From my observations `cleanup on shutdown`, but `Clean Up...` does not have any effect.

#### My specification
- QuiteRSS Version: 0.18.12 (02.07.2018)
- OS: 5.1.16-arch1-1-ARCH

QuiteRSS was installed through `pacman`

**Comment by sojusnik** [comment]
The only way cleaning works at the moment is, when "store DB in memory" and "enable cleanup on shutdown" are enabled.  The manual cleanup (from the app's menu) still won't work though. At least for me on Ubuntu 18.10 with QuiteRSS 0.18.12 (02.07.2018) and Qt-5.9.5, SQLite-3.24.0, WebKit-602.1.

**Comment by Funcy-dcm** [comment]
Try version 0.19.2

**Comment by sojusnik** [comment]
Works again with 0.19.2!
