### ISSUE TITLE
Problem with one feed - not all new entries appear

### ISSUE THREAD

**Issue by Owyn** [QuiteRSS/quiterss#1189]
https://mangasushi.net/feed/manga-chapters

when I delete this my feed and add it back - all 100% entries appear fine, but then after new entries get added (updated), most of them don't appear
I don't have any filters for this feed, so I don't why what the problem might be...

**Comment by Funcy-dcm** [comment]
Send screenshots

**Comment by Owyn** [comment]
Here, I hit update and the new entry isn't coming up in quiteRSS:
![изображение](https://user-images.githubusercontent.com/1309656/78508681-5c41c980-7791-11ea-96d5-fbe104b41ec8.png)

but as text I can see it if I open the feed in the browser:
![изображение](https://user-images.githubusercontent.com/1309656/78508696-88f5e100-7791-11ea-86f0-59fce2c9b409.png)

in QuiteRSS I press refresh and new entry doesn't appear:
![изображение](https://user-images.githubusercontent.com/1309656/78508710-aa56cd00-7791-11ea-8cd7-672960761468.png)

but if I delete whole feed:
![изображение](https://user-images.githubusercontent.com/1309656/78508720-b5116200-7791-11ea-9587-0268806c7b1a.png)

 and then add it again:
![изображение](https://user-images.githubusercontent.com/1309656/78508739-ce1a1300-7791-11ea-88aa-5a894ec4684b.png)

 - it appears: 
![изображение](https://user-images.githubusercontent.com/1309656/78508751-ea1db480-7791-11ea-931e-107426ddc9a0.png)


If I don't do anything with the feed for some times and just leave it as is while new entries are published - some appear but many are skipped and never appear
