### ISSUE TITLE
[FEATURE REQUEST] Per feed file storage

### ISSUE THREAD

**Issue by birdie-github** [QuiteRSS/quiterss#1199]
Currently QuiteRSS stores everything in a single SQLite3 database and I find this not really good for many reasons:

1. Once this file is damaged you may lose all your feeds
2. QuiteRSS cleanup doesn't always work, e.g. I have set to keep 30 days of feeds and upon manual inspection I've found literally hundreds of feeds from the earlier time.
3. On shutdown QuiteRSS completely rewrites this file which leads to filesystem fragmentation

It would be great if QuiteRSS had an option to enable per feed file storage. Thanks!

**Comment by Funcy-dcm** [comment]
Unfortunately this is not possible

**Comment by birdie-github** [comment]
Not possible because ... ?

Akregator does that. I see no reason why QuiteRSS cannot unless you just don't want to.

**Comment by birdie-github** [comment]
@Funcy-dcm 

Not possible because ... ?

Akregator does that. I see no reason why QuiteRSS cannot unless you just don't want to.

**Comment by birdie-github** [comment]
Should I file a bug report about QuiteRSS inability to actually clean up old news pieces?

**Comment by Funcy-dcm** [comment]
> @Funcy-dcm
> 
> Not possible because ... ?
> 
> Akregator does that. I see no reason why QuiteRSS cannot unless you just don't want to.

This is contrary to the inherent architecture and what we wanted to get as a result

**Comment by Funcy-dcm** [comment]
> Should I file a bug report about QuiteRSS inability to actually clean up old news pieces?

Try version 0.19.1
