### ISSUE TITLE
Erreur mise à jour 0.19.0

### ISSUE THREAD

**Issue by bilou47190** [QuiteRSS/quiterss#1200]
Bonjour,
Pour l'installation, j'ai le message : 
**L’ordinal 354 est introuvable dans la bibliothèque de liens dynamiques LIBEAY32.dll.** 
Bilou

**Comment by Funcy-dcm** [comment]
Send screenshots

**Comment by bilou47190** [comment]
![image](https://user-images.githubusercontent.com/37657380/68928798-3ccae580-078b-11ea-8c8c-5b63aa9b87ef.png)

**Comment by Funcy-dcm** [comment]
List dll: 
![image](https://user-images.githubusercontent.com/4505526/68929048-45ccae80-07ad-11ea-846b-9ee1473cd958.png)

Send your list

**Comment by bilou47190** [comment]
![image](https://user-images.githubusercontent.com/37657380/68930285-4dc92600-078e-11ea-8deb-5ae677a691cb.png)

**Comment by Funcy-dcm** [comment]
Is this libeay32.dll?

**Comment by bilou47190** [comment]
Yes
![image](https://user-images.githubusercontent.com/37657380/68930799-70a80a00-078f-11ea-8c65-4d5614f2106d.png)

**Comment by Funcy-dcm** [comment]
Send updater.log

**Comment by bilou47190** [comment]
The emptied version with the update
[updater.log](https://github.com/QuiteRSS/quiterss/files/3850709/updater.log)

The full version with the update
[updater - Copie.log](https://github.com/QuiteRSS/quiterss/files/3850710/updater.-.Copie.log)

**Comment by Funcy-dcm** [comment]
Do you have proxy?

**Comment by Funcy-dcm** [comment]
Dowload new installer: https://quiterss.org/files/0.19.0/QuiteRSS-0.19.0-Setup.exe

**Comment by bilou47190** [comment]
I have not a proxy, Thank for url

**Comment by bilou47190** [comment]
It's good, perfect. Thank you so much.
