### ISSUE TITLE
About v0.19.0 (Setup version)

### ISSUE THREAD

**Issue by rainkarnichi** [QuiteRSS/quiterss#1201]
OS: Windows 10 1909

Unable to update from previous version, when start application always show _could not be located in dynamic link library_ linked to Qt5MultimediaWidgets.dll & Qt5OpenGL.dll. To fix..
To install v 0.19.0, need to remove all files on previous version.

For style, qwindowsvistastyle.dll not included on QuiteRSS 0.19.0 setup version. Copy folder _styles_ from 0.19.0 portable version.

**Comment by havrancek** [comment]
i have the same problem.. win 10 1909, unable to update.. in check update there is new version, but when pressing install, no new version available is shown

**Comment by Funcy-dcm** [comment]
Try: https://quiterss.org/files/0.19.0/QuiteRSS-0.19.0-Setup.exe
