### ISSUE TITLE
Некорректная работа фильтров с кириллицей

### ISSUE THREAD

**Issue by morefilms** [QuiteRSS/quiterss#1203]
Проблема с фильтрами была актуальна и на предыдущей версии 0.18.12 и на текущей 0.19.0 сохранилась. Есть простой фильтр, например - Соответствует любому условию - Категория - не содержит - "тут любое слово кириллицей" - Выполнить следующее действие - удалить.
При ручном запуске фильтра он все корректно удаляет, но когда лента автоматом обновляется - то правило не работает. При чем не работает на всех сайтах, где записи сделаны кириллицей, т.е. на сайтах где категории на латыни - правило с категориями работает при автообновлении ленты.

**Comment by Funcy-dcm** [comment]
Дайте ссылку на ленту

**Comment by morefilms** [comment]
del

**Comment by Funcy-dcm** [comment]
У меня работает - удаление выполнилось при обновлении ленты:

![image](https://user-images.githubusercontent.com/4505526/69264413-196bc480-0be9-11ea-872a-d5e4a336230e.png)

![image](https://user-images.githubusercontent.com/4505526/69264390-0fe25c80-0be9-11ea-9073-7ac1bf420a71.png)

**Comment by Funcy-dcm** [comment]
Ещё покажите окно:

![image](https://user-images.githubusercontent.com/4505526/69264575-651e6e00-0be9-11ea-9115-4d7005bacfaa.png)

**Comment by morefilms** [comment]
del

**Comment by morefilms** [comment]
Скачал последнюю версию программы - добавил только 2 проблемные ленты с правилами - все начало работать, только начал добавлять другие свои ленты и правила - как сразу эти правила с категориями перестали обрабатываться при поступлении новых новостей

**Comment by Funcy-dcm** [comment]
Можете сделать архив БД feeds.db и выложить в облако

**Comment by morefilms** [comment]
https://yadi.sk/d/Hsn3aLfCwllRxA

**Comment by Funcy-dcm** [comment]
Исправил. Если ОС Windows - могу скинуть тестовую версию

**Comment by morefilms** [comment]
буду очень благодарен за тестовую версию

**Comment by Funcy-dcm** [comment]
http://yadi.sk/d/-mL1zh4gMHXwt
