### ISSUE TITLE
Создание пустых папок при просмотре новостей ленты

### ISSUE THREAD

**Issue by werticoff** [QuiteRSS/quiterss#1204]
Версия 0.19.0 (15.11.2019), Ревизия 3823.
При просмотре новостей из ленты http://news.tut.by/rss/index.rss в системном диске C:\ создаются папки https_news.tut.by_0 и http_news.tut.by_0. 
После просмотра новости папки не удаляются.
P.S. Ранее писал, что при просмотре новостей из вышеуказанной ленты не отображаются изображения. После обновления все стало ok.

**Comment by Funcy-dcm** [comment]
К сожалению, не могу понять из-за чего они появляются. Как вариант, можно отключить JavaScript

**Comment by werticoff** [comment]
Да ничего страшного! Это я так, для информации!
Спасибо за Вашу работу, QuiteRSS лучший!

**Comment by Funcy-dcm** [comment]
Хорошо, тогда закрываю, чтобы не висела )
