### ISSUE TITLE
Ошибка загрузки ленты

### ISSUE THREAD

**Issue by PhilippTraum** [QuiteRSS/quiterss#1205]
Добрый день.
Новостная лента российского RT не загружается (единственная из многих десятков)  https://russian.rt.com/rss
Сама лента рабочая и через feedreader/online подгружается без проблем.  Попытался создать новую пустую БД – никакого эффекта. Откат программы до более старой версии – тоже ничего не дало. (правда без полной очистки всех настроек в машине) 
Пишет – Error transferring  https://russian.rt.com/rss – server replied: Bad Request (302)
Текущая версия читалки 0.19.1 (на 0.19.0 – было тоже самое)
Проблема точно появилась 15.11. после обновления с версии 0.18.? (прошлого года, точнее не помню) ...  Машина W10 (64) / 1903

**Comment by Funcy-dcm** [comment]
Добрый!
Сейчас проверил эту ленту на последней версии - всё работает:

![image](https://user-images.githubusercontent.com/4505526/69131211-c6541d80-0ad3-11ea-886b-3f1e72d41936.png)
![image](https://user-images.githubusercontent.com/4505526/69131285-ee438100-0ad3-11ea-967c-e7d7d0eef9a9.png)
