### ISSUE TITLE
Media-RSS support

### ISSUE THREAD

**Issue by azmeuk** [QuiteRSS/quiterss#1207]
Some video platform like Youtube or [Peertube](https://joinpeertube.org/) use the [Media-RSS extension](http://www.rssboard.org/media-rss) to provide metadata about the videos. They generally do not use the whole tags available, but provide tags for the video description, the thumbnail, and the number of views.

Youtube thumbnails and description are displayed, but the carriage return in the description are ignored while the documentation states that descriptions are [plaintext by defaut](http://www.rssboard.org/media-rss#media-description).

Peertube thumbnail is not displayed.

An extract of a [Youtube feed](https://www.youtube.com/feeds/videos.xml?channel_id=UC7_gcs09iThXybpVgjHZ_7g):

```xml
  <media:group>
   <media:title>Can You Observe a Typical Universe?</media:title>
   <media:content url="https://www.youtube.com/v/q-6oU3jXAho?version=3" type="application/x-shockwave-flash" width="640" height="390"/>
   <media:thumbnail url="https://i2.ytimg.com/vi/q-6oU3jXAho/hqdefault.jpg" width="480" height="360"/>
   <media:description>Sign Up on Patreon to get access to the Space Time Discord! 
https://www.patreon.com/pbsspacetime

Check out the Space Time Merch Store
https://pbsspacetime.com/

The moment you started observing reality, you hopelessly polluted any conclusions you might make about it. The anthropic principle guarantees that you are NOT seeing the universe in most typical state. But used correctly, this highly controversial idea can be extremely powerful. So, how do you correctly use the anthropic principle?

Hosted by Matt O'Dowd
Written by Matt O'Dowd
Graphics by Leonardo Scholzer &amp; Adriano Leal
Directed by: Andrew Kornhaber
Executive Producers: Eric Brown &amp; Andrew Kornhaber 
...</media:description>
   <media:community>
    <media:starRating count="7709" average="4.92" min="1" max="5"/>
    <media:statistics views="176224"/>
   </media:community>
  </media:group>
```

How it is displayed:
![quiterss-youtube](https://user-images.githubusercontent.com/60163/69173803-ccacbe80-0b00-11ea-84ef-a815205e19ae.png)

An extract of a [Peertube feed](https://framatube.org/feeds/videos.xml?accountId=3):
```xml


<media:group>
                <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/ed5c048d-01f3-4ceb-97db-6e278de512b0-1080.torrent" isDefault="true">
                </media:content>
                <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/ed5c048d-01f3-4ceb-97db-6e278de512b0-720.torrent">
                </media:content>
                <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/ed5c048d-01f3-4ceb-97db-6e278de512b0-480.torrent">
                </media:content>
                <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/ed5c048d-01f3-4ceb-97db-6e278de512b0-360.torrent">
                </media:content>
                <media:content type="application/x-bittorrent" url="https://framatube.org/static/torrents/ed5c048d-01f3-4ceb-97db-6e278de512b0-240.torrent">
                </media:content>
                <media:rating>nonadult</media:rating>
            </media:group>
            <media:thumbnail url="https://framatube.org/static/thumbnails/ed5c048d-01f3-4ceb-97db-6e278de512b0.jpg" height="122" width="223">
            </media:thumbnail>
```
How it is displayed:
![quiterss-peertube](https://user-images.githubusercontent.com/60163/69173818-d1717280-0b00-11ea-9406-bab4c67a87ad.png)

**Comment by somedevreally** [comment]
do you think rss reader will implement Media-RSS Specification? because "tt-rss" has already said no to it and asks to build it as plugin.

**Comment by azmeuk** [comment]
akregator has started to work on Media-RSS, the dev from handy news reader and the one from selfoss said they will give it a try, feeder has implemented it, as did gfeeds, kriss_feeds, liferea, miniflux, and I proposed a pull request for nextcloud news.
Peertube has improved their feed to use more Media-RSS tags lately.
Considering all that activity in the past few months, I have good hope for this standard.

**Comment by Funcy-dcm** [comment]
Send a screenshot of how it should look

**Comment by azmeuk** [comment]
> Send a screenshot of how it should look

I already did :) Youtube feeds looks fine, except that carriage returns are not displayed. The Media-RSS specification says [they should](http://www.rssboard.org/media-rss#media-description) be displayed.

If peertube feeds could look like youtube feeds, that would be a very good start!

For instance, here is how [gfeeds](https://gitlab.gnome.org/World/gfeeds/) handles it (and displays additional information such as number of views etc.):

![Capture d’écran du 2020-04-04 11-28-28](https://user-images.githubusercontent.com/60163/78423652-23f29c00-7668-11ea-94f0-208645bcce2c.png)

**Comment by Funcy-dcm** [comment]
So good?

![image](https://user-images.githubusercontent.com/4505526/78451827-405efa80-76a1-11ea-8a44-672b1f99dda0.png)

**Comment by azmeuk** [comment]
Yes! I did not know that was already fixed!
