### ISSUE TITLE
I get blank screens in 0.19.1

### ISSUE THREAD

**Issue by havrancek** [QuiteRSS/quiterss#1208]
I click on any news headline and in a second nothing is there.. everytime i have to close qRSS and start again to see everything again, it is very frustrating
do you need anything else to solve this? thx

WIN 10 1909
![Snag_110d50a1](https://user-images.githubusercontent.com/11238411/69287160-9735cd00-0bf5-11ea-8a0c-263038c1e579.png)

**Comment by Funcy-dcm** [comment]
Send file feeds.db

**Comment by havrancek** [comment]
it is here: https://mega.nz/#!MABwSaCB!NE0Jfiomteug1r3r54vBjI61MEl5hoKPsFjLv5d9FGQ

**Comment by Funcy-dcm** [comment]
Send file quiterss.ini

**Comment by havrancek** [comment]
here is quiterss.ini

problem still persists in 0.19.2

[QuiteRss.zip](https://github.com/QuiteRSS/quiterss/files/3923170/QuiteRss.zip)

**Comment by havrancek** [comment]
any progress? it´s annoying af

**Comment by Funcy-dcm** [comment]
Try test version: http://yadi.sk/d/-mL1zh4gMHXwt
