### ISSUE TITLE
HTML5 video content not displayed correctly

### ISSUE THREAD

**Issue by triatic** [QuiteRSS/quiterss#1211]
When I load an entry with HTML5 video content it doesn't display correctly. It starts off as a small box and then shortly starts increasing automatically in size until it becomes huge.

Here's some feed data to test in QuiteRSS:

```<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
	<title type="text">Sample video</title>
	<id>https://example.com/</id>
	<updated>2019-11-22T08:20:14+00:00</updated>
	<entry>
		<title type="html">Sample video</title>
		<updated>2019-11-22T08:20:14+00:00</updated>
		<id>https://example.com/8</id>
		<author><name>Sample video</name></author>
		<content type="html">&lt;video controls&gt;&lt;source src="https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4" type="video/mp4"&gt;&lt;/video&gt;</content>
	</entry>
</feed>

**Comment by Funcy-dcm** [comment]
Send a link to the feed

**Comment by triatic** [comment]
https://sendeyo.com/up/d/0d590ca2ec

**Comment by Funcy-dcm** [comment]
Version 0.19.1 is work
![image](https://user-images.githubusercontent.com/4505526/69538427-1d5e6480-0fa4-11ea-9cfd-80f4f35ccd36.png)

**Comment by triatic** [comment]
Weird, here's what mine looks like. You can see from the scroll bars that it grew to a large size.

It's as if QuiteRSS keeps zooming the browser in, but I'm not touching anything.

![image](https://user-images.githubusercontent.com/42704418/69540695-2f79dc00-0f7f-11ea-97ce-8bb56978c4a7.png)

**Comment by Funcy-dcm** [comment]
What is your version? What is OS?

**Comment by triatic** [comment]
Windows 10 Pro 1909. Version below.

![image](https://user-images.githubusercontent.com/42704418/69566013-091f6500-0fae-11ea-8221-64c4fb70d38f.png)

**Comment by triatic** [comment]
Here's a video: https://streamable.com/q9z0n

**Comment by triatic** [comment]
I might not be the only person with this issue. Can this issue be reopened for further feedback?

**Comment by Funcy-dcm** [comment]
Try test version: http://yadi.sk/d/-mL1zh4gMHXwt

**Comment by triatic** [comment]
Thanks, the problem is fixed in the test version.
