### ISSUE TITLE
Interface icons size and line spacing increased after updating to 0.19.1

### ISSUE THREAD

**Issue by quiet23** [QuiteRSS/quiterss#1213]
Hi,

after updating to 0.19.1 size of all interface icons, toolbars and, more importantly, line spacing increased tremendously. The icons became huge, and setting their size to small in QuiteRSS settings does not help much. And as far as I can see line spacing cannot be adjusted at all.
Standard windows controls (buttons etc) in QuiteRSS interface seem to be unaffected.
The computer is running Windows 8.1 64-bit, and it has scaling set to 150% in Personalize -> Screen.
Screenshots: https://yadi.sk/i/gzMxAbCH8Lc1Cg https://yadi.sk/i/nrPXCEyEmwYWIw
In case the issue is not fixed soon can I safely fallback to 0.18.12? Will it corrupt the news database?
The only other thing I've done together with updating to 0.19.1 is installing pre-release version of Windows updates. Don't know if that could trigger the issue. All other programs work fine.

**Comment by Funcy-dcm** [comment]
You can use the portable version 0.18.12 for verification. You can copy feeds.db and quiterss.ini files to the directory

**Comment by quiet23** [comment]
0.18.12 works fine with the old database and settings, see https://yadi.sk/i/uEMSi7xKtrXxVg

**Comment by Funcy-dcm** [comment]
Send screenshots of other applications

**Comment by quiet23** [comment]
Installing 0.19.3 fixed the bug. Sorry for not keeping you updated, could not find the issue thread.
