### ISSUE TITLE
QuiteRSS 0.19.1 Install Failure

### ISSUE THREAD

**Issue by sinrig** [QuiteRSS/quiterss#1214]
OS: Windows 10 Home Version 1903 (64-bit)
When attempting to install QuiteRSS 0.19.1 (over version 0.18.12), I got the exception shown below after selecting the language (English) and pressing the "Install" button.

![QuiteRSS 0 19 1 Install Fail](https://user-images.githubusercontent.com/25424002/69481097-1258d800-0ddc-11ea-90ce-ff0c4041cbfb.png)

**Comment by Funcy-dcm** [comment]
Where did you get this version?
