### ISSUE TITLE
Bound address already in use

### ISSUE THREAD

**Issue by bollylu** [QuiteRSS/quiterss#1215]
Hi,

After updating through the automated system 0.18.12 -> 0.19.0 or 0.19.1, I constantly get the error message in the preview pane "Bound address is already in use. Failed to load url ..." QtNetwork error 99.

FYI, I'm using a proxy through port 3128 for having access to the internet.

**Comment by Funcy-dcm** [comment]
Send screenshots

**Comment by bollylu** [comment]
Hi Egor,

Sorry for the delay. I had to reinstall the update and then reproduce the error. Just a few clicks. Then …

[cid:image002.png@01D5A3C8.9BF159D0]

[cid:image006.png@01D5A3C8.9BF159D0]

One different this time (I was clicking like Hell to stress the system, not reading the content. I admit this is not normal behavior, but I wanted to reproduce)

[cid:image008.png@01D5A3C8.9BF159D0]

If this helps,

[cid:image012.jpg@01D5A3C8.9BF159D0]

BTW, otherwise your software is really nice. I was planning to do one of my own (being a programmer), but this one fits my needs and is working well, so I can work on other projects… Have a great day finding this bug (I know this is also part of the fun, if in a limited amount 😊).

Regards,
Luc

Luc Bolly

Rue Nouvelle Route, 42b - 4480 ENGIS (Belgium)
phone : +32-474-960084 - mailto: luc.bolly@sharenet.be<mailto:luc.bolly@sharenet.be>

**Comment by Funcy-dcm** [comment]
Hi, 
Unfortunately, screenshots are not displayed.

**Comment by bollylu** [comment]
Same message, again, hoping better result (first was sent from email)

Hi Egor,

Sorry for the delay. I had to reinstall the update and then reproduce the error. Just a few clicks. Then …
 
![image](https://user-images.githubusercontent.com/12231110/69918382-86951a80-1471-11ea-8acf-c779715d80ed.png)
![image](https://user-images.githubusercontent.com/12231110/69918396-aaf0f700-1471-11ea-8f6f-c9f833fdd82e.png)

One different this time (I was clicking like Hell to stress the system, not reading the content. I admit this is not normal behavior, but I wanted to reproduce)
 
![image](https://user-images.githubusercontent.com/12231110/69918417-eee3fc00-1471-11ea-83f3-3aa6077fe3ce.png)

If this helps,
![image](https://user-images.githubusercontent.com/12231110/69918419-f6a3a080-1471-11ea-85f5-7d6469593dec.png)

BTW, otherwise your software is really nice. I was planning to do one of my own (being a programmer), but this one fits my needs and is working well, so I can work on other projects… Have a great day finding this bug (I know this is also part of the fun, if in a limited amount 😊).

Regards,
Luc

**Comment by Funcy-dcm** [comment]
Try test version: https://yadi.sk/d/yBnwDp7iTsvQhg

**Comment by bollylu** [comment]
Hi,
I did some tests with your version and the message is gone, but I guess you just did a better job at catching it, without solving its root cause, because I still have pages that do not display.
When I select a header, most of the time I have the content displayed (web page from the site). But sometimes (quite often in fact), there is nothing, just a white placeholder. Clicking a second/third/... time on the header does nothing different, only randomly selecting other headers, then back to the failed one displays it.
I also have the same behavior with the version 0.18.12 that I'm still using, but here this is quite rare.
Anyway, thanks for the follow-up.
And in these dangerous days, take care.
Regards,
Luc
