### ISSUE TITLE
Version 0.19.1 install problem

### ISSUE THREAD

**Issue by Emil42** [QuiteRSS/quiterss#1216]
Hi,

I have problem with version 0.19.1 installation. Program asks for new version installation. After installation process is complete, the new version is not installed. Old version (0.19.0) is installed. And again program asks for update. And again the same. All the time. Why ?

**Comment by Funcy-dcm** [comment]
Send video

**Comment by triatic** [comment]
I had the same when updating with the built-in updater, it did not work. I had to download from the website to update.

**Comment by Emil42** [comment]
How can I grab video of this ?

**Comment by Emil42** [comment]
The same issue with version 0.19.2. I had to download the setup file from the page and install it manually.

**Comment by triatic** [comment]
Video: https://streamable.com/22y05

**Comment by Funcy-dcm** [comment]
Send file update.log

**Comment by triatic** [comment]
I cannot find `update.log`, where is it located?

**Comment by Funcy-dcm** [comment]
Help - About - Information

**Comment by triatic** [comment]
There is no `update.log` listed there, only `debug.log`.

**Comment by Funcy-dcm** [comment]
It is located in the same place

**Comment by triatic** [comment]
All I see is this.

![image](https://user-images.githubusercontent.com/42704418/69715318-f87f0400-10ff-11ea-9290-514f673828ae.png)

**Comment by Funcy-dcm** [comment]
C:\Users\x_x\AppData\Local\Temp\QuiteRSSUpdater\

**Comment by Funcy-dcm** [comment]
And look next to Quiterss.exe

**Comment by triatic** [comment]
There is no log next to `QuiteRSS.exe`.

`updater.log` in `C:\Users\x_x\AppData\Local\Temp\QuiteRSSUpdater\` does not say anything interesting.

```
27.11.2019 11:07:31.452 WARNING: Start application!
27.11.2019 11:07:31.459 DEBUG: isRunning:  false
27.11.2019 11:07:31.465 DEBUG: message:  "C:/Program Files (x86)/QuiteRSS"
27.11.2019 11:07:31.471 DEBUG: Application dir path:  "C:/Users/User/AppData/Local/Temp/QuiteRSSUpdater"

**Comment by Funcy-dcm** [comment]
Try running Updater.exe from folder QuiteRSS.exe

**Comment by Funcy-dcm** [comment]
What is OS?

**Comment by triatic** [comment]
Running Updater.exe is exactly the same as updating inside the application. It does not work.

OS is Windows 10 Pro 1909.

**Comment by Funcy-dcm** [comment]
Is there updater.log?
![image](https://user-images.githubusercontent.com/4505526/69719859-334e5f80-1133-11ea-9afa-9d45a93c259d.png)

**Comment by triatic** [comment]
No.

![image](https://user-images.githubusercontent.com/42704418/69720064-b78bed00-1109-11ea-81d6-bad6f0203606.png)

**Comment by Funcy-dcm** [comment]
Run as administrator (Updater.exe)

**Comment by triatic** [comment]
Application updates successfully when running Updater.exe as administrator.

**Comment by Emil42** [comment]
So what is conclusion ? Before it was not necessary to update program as administrator.

**Comment by Funcy-dcm** [comment]
We changed the application build system.

**Comment by Funcy-dcm** [comment]
Starting from the next version will work
