### ISSUE TITLE
Update from v0.19.0 to v0.19.2 looping

### ISSUE THREAD

**Issue by davcomNZ** [QuiteRSS/quiterss#1219]
After being notified by my QuiteRSS v0.19.0 that update v0.19.2 was available, using the built-in updater would keep notifying that the new version was available and did I want to update after it had finished downloading and unpacking 51 files. The updater kept firing up v0.19.0 instead of v0.19.2.
Fixed by visiting the quiterss.org website and downloading from there then installing over the top.

**Comment by Funcy-dcm** [comment]
Sometimes such a problem arises, but we cannot understand why

**Comment by Funcy-dcm** [comment]
duplication #1216
