### ISSUE TITLE
Version 0.19.2 

### ISSUE THREAD

**Issue by Freefire666** [QuiteRSS/quiterss#1220]
Style "Dark"
Pls fix the grey Background in the Unread Menu...this looks not so nice :/

I have Add a Picture:
https://imgur.com/3OzQgLv

Thx
QuiteRSS is the Best Reader :)Greetings :)

**Comment by Funcy-dcm** [comment]
Send full screenshots

**Comment by Freefire666** [comment]
https://imgur.com/KKOaG22
It`s Win 8.1

Greetings

**Comment by Freefire666** [comment]
i have installed a clean version and is worked !
Sry :/

**Comment by Funcy-dcm** [comment]
Choose a dark theme again

**Comment by Funcy-dcm** [comment]
:)
