### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by MichelZ** [QuiteRSS/quiterss#1221]
[debug.log](https://github.com/QuiteRSS/quiterss/files/3901089/debug.log)
Using Version 0.19.2 now (but also happened with previous versions) I get regular crashes

Faulting application name: QuiteRSS.exe, version: 0.19.2.3841, time stamp: 0x5ddd5406
Faulting module name: Qt5Core.dll, version: 5.13.2.0, time stamp: 0x5db2a9fc
Exception code: 0xc0000005
Fault offset: 0x0000e4e3
Faulting process id: 0x74f4
Faulting application start time: 0x01d5a5cf90228b98
Faulting application path: C:\Users\<myuser>\AppData\Local\Programs\QuiteRSS\QuiteRSS.exe
Faulting module path: C:\Users\<myuser>\AppData\Local\Programs\QuiteRSS\Qt5Core.dll
Report Id: 27d4563a-0e2c-4962-bdb5-9da3aa4b4d79
Faulting package full name: 
Faulting package-relative application ID:

**Comment by andrewpros** [comment]
@MichelZ U still get this? 
Im having it too, i just try couple of times and it at least always runs after some tries.
For me it is always launch crash, it tries to run but exits in task manager, never shown even gui.
Im trying to pin point it, do u have qt installed separately on the system?

**Comment by andrewpros** [comment]
@Funcy-dcm any support with this?

**Comment by Funcy-dcm** [comment]
Try test version: http://yadi.sk/d/-mL1zh4gMHXwt

**Comment by andrewpros** [comment]
@Funcy-dcm 
The last official update seem to already fixed it back then on release date, i forgot about this issue, now the app always work good.

However  i did find some related potential issues as to why it could possibly not work all the time before, interesting read https://blog.inventic.eu/2014/08/qt5-application-crashed-with-error-0xc0000005/

**Comment by Funcy-dcm** [comment]
Thank you!
