### ISSUE TITLE
Version 0.19 Upgrade

### ISSUE THREAD

**Issue by dcorkrey** [QuiteRSS/quiterss#1226]
In Windows, upgrade to 0.19.1 works fine. 0.19.2 does not upgrade.
Also in Linux (Ubuntu/Kubuntu) cannot upgrade past 0.18. I keep getting upgrade notices but does not work for Linux. When can we expect a working upgrade?

**Comment by darcosion** [comment]
I've same problems, do you had tried the command ```which quiterss``` ? 

Actually, QuiteRSS do it installation on ```/usr/share/application``` but before, it was another place.
Actually, my solution was just to delete ```/bin/quiterss``` and use ```/usr/bin/quiterss```, but it's a little bit crappy.

Regards

**Comment by Funcy-dcm** [comment]
Try version 0.19.4
