### ISSUE TITLE
18.x > 19.x upgrade: settings oops

### ISSUE THREAD

**Issue by tieugene** [QuiteRSS/quiterss#1227]
After updating 18.x (qt4) to 19.x (qt5) all settings (e.g. feed lists) reset.
It is critical bug.

**Comment by Funcy-dcm** [comment]
What is OS?

**Comment by Funcy-dcm** [comment]
This is a Qt library error. This is a Qt library error. They changed the paths to the settings files and the database in Linux

**Comment by tieugene** [comment]
Fedora 30, 31.
IMHO it is not Qt bug but feature.
But it is user's problem, not Qt developers.
Maybe this will be good idea to import old settings into new ones.
