### ISSUE TITLE
19.x settings: autoimport 18.x

### ISSUE THREAD

**Issue by tieugene** [QuiteRSS/quiterss#1228]
Automatic old settings import required.

**Comment by Funcy-dcm** [comment]
I can not determine the path to the old settings
Can you give path to new and old settings?

Now i use QStandardPaths::writableLocation(QStandardPaths::DataLocation)
Maybe you need to use this QStandardPaths :: AppDataLocation?

**Comment by Funcy-dcm** [comment]
Can you give path to new and old settings?

**Comment by Funcy-dcm** [comment]
Now i use  QStandardPaths::writableLocation(QStandardPaths::DataLocation)

Maybe you need to use this QStandardPaths :: AppDataLocation?

**Comment by tieugene** [comment]
Ok, lets go:
1. QuitRSS 18.x (qt4) data files found in ~/.local/share/data/QuiteRss/QuiteRss.
This corresponds with QDesktopServices::DataLocation.
2. QuiteRSS 19.x same files found in ~/.local/share/QuiteRss/QuiteRss.
This corresponds with QStandardPaths::DataLocation/AppDataLocation/AppLocalDataLocation (all of them are the same).
Seems good way will be to import data from qt4-related path into qt5 one.
PS. config file and caches are another questions

**Comment by tieugene** [comment]
Maybe it must be not automatic but "File - Import" menu item.
Depends on OS.

**Comment by Funcy-dcm** [comment]
I also think because users can already use the application with the new settings.
