### ISSUE TITLE
在使用Snipaste截图时会卡死

### ISSUE THREAD

**Issue by NanJishen** [QuiteRSS/quiterss#1231]
升级后，在使用 Snipaste 这个软件截图时，Quiterss 会卡死，希望尽快修复

**Comment by Funcy-dcm** [comment]
Я вас не понимаю

**Comment by NanJishen** [comment]
Sorry, I can't speak English, I'm not responding when I'm making Win10 Store App: Snipaste
&nbsp;

NanJi：
邮箱：nanji_shen@qq.com
Q Q：81489060
微信：nanjishen

 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Egor Shilyaev"<notifications@github.com&gt;; 
发送时间: 2019年12月9日(星期一) 下午5:43
收件人: "QuiteRSS/quiterss"<quiterss@noreply.github.com&gt;; 
抄送: "南极神"<nanji_shen@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [QuiteRSS/quiterss] 在使用Snipaste截图时，Quiterss会卡死 (#1231)




Я вас не понимаю
 
&mdash;
