### ISSUE TITLE
Crash with embedded video on feed

### ISSUE THREAD

**Issue by darcosion** [QuiteRSS/quiterss#1232]
Hello everyone, 

With on of my source, if have a specific feed who kill QuiteRSS.
This is the page concerned (in French) : https://vincent.bernat.ch/fr/blog/2019-auto-hebergement-videos-sous-titres

In this page, they are an embedded video an the internal browser of QuiteRSS doesn't like that.

I've tried to compile The last version of QuiteRSS (0.19.2) in debug mod, but that didn't created crash indication.

Any Idea ? 

Regards, 
Darcosion

**Comment by stingray21** [comment]
Same issue here, with feeds that have embedded videos. QuiteRSS just freezes and has to be killed and restarted

**Comment by Funcy-dcm** [comment]
What is your OS?

**Comment by darcosion** [comment]
o/ I'm on ubuntu 18.04 i386

**Comment by stingray21** [comment]
Manjaro Gnome, 3.36.0. It most often happens on the Axios feed (https://api.axios.com/feed/)

**Comment by Funcy-dcm** [comment]
Unfortunately, this problem Webkit

**Comment by stingray21** [comment]
Would it be possible to "block" the videos in the posts,  as a temporary work-around? Or replace them with a link to the video? When the QuiteRSS crashes, it doesn't save the current state, so you have to go through all the messages again and check if you already read them or not

**Comment by Funcy-dcm** [comment]
You can disable js in the feed settings

**Comment by stingray21** [comment]
Thank you, that works!
