### ISSUE TITLE
Убрать сертификаты

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#1236]
Иногда не подхожу пару дней к компьютеру на котором работает QuiteRSS и когда возвращаюсь, то периодически вижу [окно с "ошибкой сертификата SSL"](https://github.com/QuiteRSS/quiterss/issues/1038), которое не дает лентам обновляться.

Можно эту проверку сертификатов вообще убрать или отключить, чтобы ленты могли обновляться без помех?

PS: Андрей Палкин видимо забыл про ваш чудесный ридер — [PPA](https://launchpad.net/~quiterss/+archive/ubuntu/quiterss) так и не обновил :/

**Comment by sojusnik** [comment]
В очередной раз столкнулся с этой проблемой — пару дней не трогал комп и фиды не обновлялись из-за окна со сертификатами SSL. Очень нервирует :disappointed: 

Неужели никаких решений не придумать?

Уже удалял папку со сертификатами перед длительным отсутствием, но вроде это не помогает.

**Comment by Funcy-dcm** [comment]
fix: ebed2498ab48a5e5b939f4c3e680a299cbfd1f6e

**Comment by sojusnik** [comment]
Сегодня опять появилась подобная ошибка с [этой](https://www.anomalistik.de/?format=feed&type=rss) лентой, см. [здесь](https://mega.nz/file/Ht4DWDIL#Yih_DRJgYvACOPd7nBp6TTw_VHqpnOUxBTlV7euY4VI).

Пользуюсь версией 0.19.3 (29.01.2020) с Qt-5.12.5, SQLite-3.31.1, WebKit-602.1 на Ubuntu 20.04.

**Comment by Funcy-dcm** [comment]
Используйте версию 0.19.4

**Comment by sojusnik** [comment]
Исходил из того, что у меня стоит последняя версия, поскольку пользуюсь [PPA](https://launchpad.net/~quiterss/+archive/ubuntu/quiterss), а там оказывается не получилось собрать пакет для Ubuntu 20.04 (Focal). Можно об этом сообщить Андрею Палкину?
