### ISSUE TITLE
Реализация API для плагинов

### ISSUE THREAD

**Issue by evpix** [QuiteRSS/quiterss#1239]
Данному ридеру не помешала бы реализация API для плагинов.
Вот захочется что-то дополнить в ридере, а такой возможности нет(кроме как самому копаться в коде ридера и изменять что нужно).

Предлагаю такой вариант. Реализация API для языков C++, Lua или Python на выбор(что-то из этого). Для меня Lua API был бы предпочтительнее.

Почему нужны плагины?
Так для того чтобы можно было расширить функционал ридера как хочется без перекомпиляции кода ридера.

PS. Я не навязываю данную реализацию. Но стоит задуматься, что данный функционал для некоторых был бы полезен чем наоборот.

**Comment by evpix** [comment]
Я пересмотрел свой запрос на реализацию. Пока это будет только лишним и занимать дополнительное время у автора на доработку этого API.

**Comment by EvolutionPixG** [comment]
Закрываю данный issue.

**Comment by Funcy-dcm** [comment]
К сожалению, совсем сейчас нет времени на развитие, может кто-нибудь решиться реализовать
