### ISSUE TITLE
Crashing in Windows 10

### ISSUE THREAD

**Issue by matteary134** [QuiteRSS/quiterss#1241]
My QuiteRSS crashes occasionally when I click on an unread item.  Windows 10 Home, 8GB.

Faulting application name: QuiteRSS.exe, version: 0.19.2.3841, time stamp: 0x5ddd5406
Faulting module name: libadaptive_plugin.dll, version: 3.0.7.1, time stamp: 0x39c739ab
Exception code: 0x40000015
Fault offset: 0x00105397
Faulting process id: 0x3e80
Faulting application start time: 0x01d5c6fd405db6bd
Faulting application path: C:\Program Files (x86)\QuiteRSS\QuiteRSS.exe
Faulting module path: C:\Program Files (x86)\VideoLAN\VLC\plugins\demux\libadaptive_plugin.dll
Report Id: cb272dfa-5360-42ff-8e3a-1f11155c14db
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Funcy-dcm** [comment]
Try test version: http://yadi.sk/d/-mL1zh4gMHXwt

**Comment by matteary134** [comment]
Yandex Disk isn't letting me install it on Windows 10.  When I try to 
register with my mobile phone number it says "Message sending limit 
exceeded".  When I enter the CAPCHA characters it always says "You 
entered the wrong characters."  With or without a space between the two 
words.

Matt Eary
matt@eary.net
301 707 4824 mobile
301 895 5510 home

**Comment by Funcy-dcm** [comment]
Then wait for the official release
