### ISSUE TITLE
Crash QuiteRSS

### ISSUE THREAD

**Issue by 44Fove** [QuiteRSS/quiterss#1243]
Beschreibung
Name der fehlerhaften Anwendung: QuiteRSS.exe, Version: 0.19.2.3841, Zeitstempel: 0x5ddd5406
Name des fehlerhaften Moduls: ntdll.dll, Version: 10.0.14393.3241, Zeitstempel: 0x5d786bcf
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00046b93
ID des fehlerhaften Prozesses: 0x88c
Startzeit der fehlerhaften Anwendung: 0x01d5b4fe87bbd4e7
Pfad der fehlerhaften Anwendung: E:\Internet\RSS Reader\QuiteRSS\QuiteRSS.exe
Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\ntdll.dll
Berichtskennung: 76cbbd0b-189a-47e0-a4a2-6b176f643ad7
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by Funcy-dcm** [comment]
Try test version: http://yadi.sk/d/-mL1zh4gMHXwt
