### ISSUE TITLE
Adding authenticated feed UI flow broken

### ISSUE THREAD

**Issue by sleepyspider1** [QuiteRSS/quiterss#1245]
Version 0.19.2 (26.11.2019)
Revision 3841

Repro steps
1) File -> Add -> Feed
2) Type in feed url that requires authentication.
3) Click "Next"
4) After it fails to add the feed, cick the check box "Server requires authentication".
5) Type in a username and password.
6) Notice that the finish and next buttons are still grayed out. Unable to continue.

Workaround
Have to uncheck and check "Use title of feed as display name" to get finish and next buttons to not be grayed out.

**Comment by Funcy-dcm** [comment]
Send link feed
