### ISSUE TITLE
Unexpected closure and lost colors

### ISSUE THREAD

**Issue by bilou47190** [QuiteRSS/quiterss#1250]
Hello,
I have a problem with version 0.19.3 (29.01.2020) Revision 3873.
The program shuts itself down.
Loss of color. 
For example:
Font and colors: Flux with new articles, I had put yellow, it remains white. Text color of unread articles, same ....
And consumes a lot of memory (private work game).

**Comment by Funcy-dcm** [comment]
What is your OS?
