### ISSUE TITLE
Option to turn off DirectWrite in 0.19.3

### ISSUE THREAD

**Issue by Casonctin** [QuiteRSS/quiterss#1251]
Can you please add an option to turn off DirectWrite in 0.19.3. The fonts are very blurry on my monitor. GDI looks much clearer.

**Comment by Casonctin** [comment]
My only option is to downgrade back to 0.19.2.

0.19.3 hurts my eyes.

**Comment by Funcy-dcm** [comment]
Try for OS Windows: https://yadi.sk/d/-mL1zh4gMHXwt

**Comment by Casonctin** [comment]
> Try for OS Windows: https://yadi.sk/d/-mL1zh4gMHXwt

Its looks clear in this version. What was changed? 

Thank you!
