### ISSUE TITLE
no inet connection after update

### ISSUE THREAD

**Issue by Freefire666** [QuiteRSS/quiterss#1254]
no inet conection from the exe
no feed working / (github releases) 
last version all ok
i used win 8.1 and proton vpn
im going back to 0.19.2...this works fine
have a nice day

**Comment by Twolane2** [comment]
I'm having the same problem. The first time I installed 13, it refused to read any feeds again and again. Uninstalled and re-installed 12. It worked perfectly, time after time. Yesterday I updated to 13 again. It worked fine until today. Now it comes up empty, time after time. Win 10 64bit.

**Comment by Funcy-dcm** [comment]
Try test version: http://yadi.sk/d/-mL1zh4gMHXwt
