### ISSUE TITLE
0.19.3 still says 0.19.2

### ISSUE THREAD

**Issue by ken1943** [QuiteRSS/quiterss#1256]
After installing 0.19.3, about still says 0.19.2

Please confirm problem

**Comment by brezelman** [comment]
When using updater (by clicking "new version" popup), the new version doesn't get installed!
Windows 10, installer version of QuiteRSS, laying in Program Files (x86) here.
Manual download and running installer installs version 0.19.3 successfully.

**Comment by trident-job** [comment]
I had the same issue.
Installed 3 times from the notification, but still 0.19.2 :(
**WORKAROUND:** I closed and restarted QuiteRSS **as an Admin**.
Then I clicked the notification and it installed OK.

**Comment by bilou47190** [comment]
The logiciel is HS, KO, Damn

**Comment by trident-job** [comment]
> The logiciel is HS, KO, Damn

Could you add value in your comment ?
Detail your issue, did you try the workaround noted upper ?
Have you find a way to make it work ?

**Comment by andrewpros** [comment]
@ken1943 
I had the same, try running the updater from QuiteRSS directory alone as an admin, it worked for me.

**Comment by Funcy-dcm** [comment]
You need to run updater.exe from under the administrator. In version 0.19.3 this bug is fixed
