### ISSUE TITLE
Не открываются новости ленты https://www.kinopoisk.ru/news.rss

### ISSUE THREAD

**Issue by werticoff** [QuiteRSS/quiterss#1257]
При клике на новость (для примера) https://www.kinopoisk.ru/media/news/4000475/ появляется следующее сообщение:
Flow control error
Failed to load URL https://www.kinopoisk.ru/media/news/4000475/.
QtNetwork Error 399

**Comment by Funcy-dcm** [comment]
У вас какая ОС?

**Comment by werticoff** [comment]
Здравствуйте! Windows 7 Pro SP1 x64

**Comment by Funcy-dcm** [comment]
Попробуйте http://yadi.sk/d/-mL1zh4gMHXwt

**Comment by werticoff** [comment]
Да, все работает, спасибо!
