### ISSUE TITLE
0.19.3 font smoothing

### ISSUE THREAD

**Issue by rkocman** [QuiteRSS/quiterss#1258]
It seems that with the latest update QuiteRSS does not respect the global environment setting for font smoothing anymore (at least on Windows 7).
I have the font smoothing setting set to disabled on Windows 7, since the ClearType technology is very blurry for me.
But now, QuiteRSS automatically uses font smoothing and there is no way how to turn it off.

**Comment by Casonctin** [comment]
I have the same issue and i'm using Windows 7.

![Capture](https://user-images.githubusercontent.com/5668677/73790150-00959880-476e-11ea-9ac7-f288dce8e0f7.png)

**Comment by qcybb** [comment]
I'm having the same issue in Windows 10. Please fix this!

**Comment by Funcy-dcm** [comment]
Try: https://yadi.sk/d/-mL1zh4gMHXwt

**Comment by rkocman** [comment]
It looks fine on Windows 7.

**Comment by qcybb** [comment]
Yes, that fixes the issue in Windows 10.

**Comment by Funcy-dcm** [comment]
Excellent! I will release a fix version soon
