### ISSUE TITLE
error: unknown type name 'QWebFullScreenRequest'

### ISSUE THREAD

**Issue by AngryPenguinPL** [QuiteRSS/quiterss#1259]
Hi.
When build QuiteRSS 0.19.3 with Clang (same issue also on GCC) on OpenMandriva Cooker I see this error:
```
In file included from src/newstabwidget.cpp:23:
BUILDSTDERR: src/webview/webpage.h:72:32: error: unknown type name 'QWebFullScreenRequest'
BUILDSTDERR:   void slotFullScreenRequested(QWebFullScreenRequest fullScreenRequest);
```
Full build log: http://file-store.openmandriva.org/api/v1/file_stores/7bf5e08283dbcf7a573967b362f85714507c26be.log?show=true

Qt 5.14.1
qt5-qtwebkit 5.9.1

**Comment by Funcy-dcm** [comment]
Use version webkit: https://github.com/qtwebkit/qtwebkit/releases
