### ISSUE TITLE
Startup Error: Cannot open SQLite database on Windows

### ISSUE THREAD

**Issue by Splode** [QuiteRSS/quiterss#1260]
I've just installed _quiterss_ with scoop. The _quiterss_ version is `0.19.3`. When starting the application, I receive the following error message via an alert window:

```
Cannot open SQLite database!
Error: unable to open database file Error opening database
```

The application exits after this alert is dismissed.

I have SQLite version `3.31.1` installed and it is available on my `PATH`.

Subsequent attempts to start the application result in the same behavior.

**Comment by vuon9** [comment]
Hi, I got the same problem, after delete feeds.db in installed folder then it works. 
I assume problem come from persisting action of scoop https://github.com/lukesampson/scoop-extras/blob/master/bucket/quiterss.json

**Comment by Splode** [comment]
@vuongggggg I just confirmed that this is an issue when installing with scoop on account of the `feeds.db` file in the `persist` directory. Instead of a proper database file, the `feeds.db` that is created is an empty directory. This causes the database connection error.

Removing the shortcut to `feeds.db` and restarting the application generates a new `feeds.db`  database file in the current install directory. After this, the application works as expected. However, this approach might break upgrading through scoop as `feeds.db` may be overwritten in subsequent installs. One option might be to move the created `feeds.db` file into the `persist` directory and re-link.

In all, this seems to be an issue with the quiterss scoop manifest and implementation.

**Comment by vuon9** [comment]
Yep, so your explanation is so enough, I created issue on scoop yesterday. https://github.com/lukesampson/scoop-extras/issues/3681
