### ISSUE TITLE
QuiteRSS Version 0.19.3 (29.01.2020) Révision 3873 DOWN.

### ISSUE THREAD

**Issue by bilou47190** [QuiteRSS/quiterss#1262]
Could you add value in your comment ?
 Detail your issue, did you try the workaround noted upper ?
 Ha e you find a way to make it work ?

**I didn't understand**
**do what ?**

![image](https://user-images.githubusercontent.com/37657380/73732126-ec37a880-4739-11ea-89d4-0cd9ab5b6d5c.png)

**Comment by Funcy-dcm** [comment]
How did this error happen?
