### ISSUE TITLE
Перестаёт читать ленты

### ISSUE THREAD

**Issue by vadimlitvinenko87** [QuiteRSS/quiterss#1265]
Рисует красный крест на лентах новостей и при обновлении вышеупомянутых ничего не меняется. Помогает только полный перезапуск программы.
![2020-2-8 13-47-26](https://user-images.githubusercontent.com/34354361/74081472-a0f30200-4a79-11ea-8275-91b650cb797f.png)

**Comment by Funcy-dcm** [comment]
В версии 0.19.2 так же работало? Необходимы ссылки на ленты

**Comment by vadimlitvinenko87** [comment]
Нет, версия 0.19.2 хорошо работает, откатил на неё.

вс, 9 февр. 2020 г. в 15:17, Egor Shilyaev <notifications@github.com>:

**Comment by Funcy-dcm** [comment]
Попробуйте: https://yadi.sk/d/-mL1zh4gMHXwt

**Comment by vadimlitvinenko87** [comment]
попробовал, перезагружал, чистил базы, полёт нормальный. Решил снова
проверить сборку с сайта версии 0.19.3, очень странно, но она тоже
перестала глючить. В общем пока проблем не возникает, но я часто люблю
переставлять систему и как раз до 17 февраля делал откат до чистой системы
и видимо это может быть взаимосвязано.

пн, 17 февр. 2020 г. в 18:49, Egor Shilyaev <notifications@github.com>:

**Comment by vadimlitvinenko87** [comment]
Нет, всё-таки с сайта версия глючная кажется. Постигла таже беда, и ещё
заметил неадекватное cleartype сглаживание внутри программы на шрифтах.
[image: 2020-2-25 16-16-51.png]

пн, 17 февр. 2020 г. в 18:49, Egor Shilyaev <notifications@github.com>:

**Comment by Funcy-dcm** [comment]
Используйте пока тестовую версию, позже будет новая версия
