### ISSUE TITLE
Падение приложения Версия 0.19.3 (29 Янв 2020) 

### ISSUE THREAD

**Issue by CBzeek** [QuiteRSS/quiterss#1266]
Добрый день.
после обновления
с - Версия 0.19.2 (26 Ноя 2019) 
на - Версия 0.19.3 (29 Янв 2020) 
приложение стало "падать" (самопроизвольно завершаться с ошибкой).

ОС - Microsoft Windows 7 Профессиональная 64х

**Comment by CBzeek** [comment]
![Quiterss-error](https://user-images.githubusercontent.com/60964131/74324706-787c4800-4d98-11ea-82ac-4ee9f98a1651.png)

**Comment by Funcy-dcm** [comment]
Ошибка в библиотеках.
Попробуйте: https://yadi.sk/d/-mL1zh4gMHXwt

**Comment by CBzeek** [comment]
Сегодня целый день на тестовой версии, полет нормальные, ни одного падения. спасибо за оперативность!
