### ISSUE TITLE
Suggestion for option to show title while scrolling content

### ISSUE THREAD

**Issue by elig0n** [QuiteRSS/quiterss#1267]
Hi, first thanks for this wonderful project 
I would like to suggest an option to keep displaying the top news article summary 'bar' (which usually includes title, date, author, tags and so on) while simultaneously being able to scroll the news article content itself without it disappearing.

**Comment by Baramiji** [comment]
Hi,
You can do this by editing **news.css** inside **Style** directory.
Go to this section, and add position as fixed:
```
.titleTable {
   ... Existing codes ...
   position: fixed;
}
```
After that go also to this other section, and add padding-top:
```
.newsTable {
   ... Existing codes ...
  padding-top: 100px;
}
```
**NB 1:** **padding-top** must be after the existing **padding**, not before.
**NB 2:** You can change **100px** to any size you want.

**Comment by elig0n** [comment]
That did it. Would you consider adding it as a toggle-able option in future release ?
Besides also making it unnecessary for me to modifying the file myself after every upgrade, other users might like it too.
