### ISSUE TITLE
[request] mp3 player by flash does not work on mac

### ISSUE THREAD

**Issue by vinbrule** [QuiteRSS/quiterss#1269]
Hi, I am using newest version on Mac. The click-to-play flash cannot play mp3 file anymore. Can you update it to use standard audio tag of html to play mp3 file?

Bests,

**Comment by Funcy-dcm** [comment]
Link feed and news

**Comment by vinbrule** [comment]
Hi, This is the link https://www.podcastfrancaisfacile.com/feed
