### ISSUE TITLE
News doesn't stay marked as unread

### ISSUE THREAD

**Issue by aswerw** [QuiteRSS/quiterss#1270]
If you click on a news item for a feed, or in my case a folder containing several feeds, that item will correctly be marked as read. 

However, if you then mark that news item as unread then the next time that feed becomes selected that news item will be marked as read again.

Example:
![gif](https://user-images.githubusercontent.com/10407330/76172169-ed218700-618a-11ea-9b39-c5ad87cbff79.gif)

Version: 0.19.3

**Comment by Funcy-dcm** [comment]
This is a normal job

**Comment by aswerw** [comment]
Are you sure? It seems like the wrong behavior to me.

If you accidentally misclick on a news item and want to read it at a later time, then you can't? You can mark it as unread but it will just get marked as read again once that feed gains focus.

The issue is that whichever news item was previously selected automatically becomes marked as read when the feed gains focus again.

**Comment by Funcy-dcm** [comment]
See settings: Menu - Tools - Options - Feeds
