### ISSUE TITLE
Цвет чередующихся строк не меняется

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#1272]
Даже если перезагрузить QuiteRSS, то цвет чередующихся строк не меняется. Изменение стиля приложения тоже не помогает.

Пользуюсь Ubuntu с QuiteRSS 0.19.2 (26.11.2019).

**Comment by Funcy-dcm** [comment]
fix: b449ef809662522634878c6f7f9624703e4430ec

Ещё необходимо включить в настройках опцию: "Menu - Options - Feeds - Alternating row background colors"
