### ISSUE TITLE
Не изменяется цвет заголовка

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#1273]
Фон заголовка новости получается сменить, а цвет самого заголовка — нет. Но если сменить цвет ссылки, то и заголовок меняется.

Пользуюсь Ubuntu с QuiteRSS 0.19.2 (26.11.2019).

**Comment by Funcy-dcm** [comment]
Всё правильно, так и должно быть

**Comment by sojusnik** [comment]
То есть заголовок всегда будет иметь цвет ссылки? Зачем тогда эта опция, если вроде все заголовки являются ссылкой на саму новость?

**Comment by Funcy-dcm** [comment]
Заголовок новости это целиком поле над новостью, а уже в нём есть ссылка на новость.

В заголовке ссылка цветом ссылки, а все остальные поля как цвет который в настройках.

**Comment by sojusnik** [comment]
Вас понял, просто ни разу не видел заголовок без ссылки, то есть у меня весь заголовок всегда одна сплошная ссылка.
