### ISSUE TITLE
19.3 CRASHES

### ISSUE THREAD

**Issue by dave47** [QuiteRSS/quiterss#1275]
PLEASE FIX 19.3. CRASHES ALL THE TIME !!!

**Comment by Funcy-dcm** [comment]
What is your OS?

**Comment by grisha999** [comment]
и у меня 10 раз на дню крашится Win 7 64bit со всеми обновами

**Comment by Funcy-dcm** [comment]
Ошибка в библиотеках.
Попробуйте: https://yadi.sk/d/-mL1zh4gMHXwt
