### ISSUE TITLE
Don't steal focus/tab back to the app when opening a link with your browser.

### ISSUE THREAD

**Issue by Kezxo** [QuiteRSS/quiterss#1276]
I have the browser selection setting set to "Use External Browser". Whenever I open a link in QuoteRSS it opens it in Firefox and then instantly tabs back to the QuoteRSS, it's even more confusing if you use it in fullscreen. It should just tab over to the browser when you open links.

QuiteRSS
Version 0.19.3 (29.01.2020)
Revision 3873

I'm using Firefox 73.0.1 (64-bit) and Windows 10 pro version 1909 (OS-version 18363.657)

Related issue:  #349

**Comment by Funcy-dcm** [comment]
Disable option: "Options->Browser->Open links in external browser in background 
(experimental)"

**Comment by Kezxo** [comment]
That works, thanks! Maybe I enabled that and forgot, thanks for the help.
