### ISSUE TITLE
Question about QuiteRSS

### ISSUE THREAD

**Issue by bengtogren** [QuiteRSS/quiterss#1282]
Hi!
I downloaded the portable version of QuiteRSS today to try it out.
I added a few RSS feeds, two of which were https://www.dn.se/rss/ and https://www.dn.se/rss/senaste-nytt. These are very similar, sometimes identical,
but they often differ in timing.
I noticed that when I had gone through the latest items in the one feed (making the boldface disappear), the boldface for the same items had disappeared in the other feed too!
Is this by design or is it a bug happening because the items have identical headers (names)?

Best regards
Bengt Ögren
Floda
Sweden

**Comment by Funcy-dcm** [comment]
So it is conceived.
Menu - Tools - Options - Feeds - Automatically mark identical news as read
