### ISSUE TITLE
Updating Feed Problems in QuiteRSS 0.19.3 (29.01.2020)

### ISSUE THREAD

**Issue by randombyt** [QuiteRSS/quiterss#1283]
After updating to latest version, QuiteRSS 0.19.3 (29.01.2020), QuiteRSS routinely shows a small cross on feed icons on system start (feed is inaccessible). Pressing update all feeds button does nothing and it requires restarting QuiteRSS, after that everything works smoothly. 

This issue only appeared after updating QuiteRSS to latest version.

OS: Win 8.1 (x64).

**Comment by Funcy-dcm** [comment]
Try version: http://yadi.sk/d/-mL1zh4gMHXwt
