### ISSUE TITLE
Feature request: Return cap+xml from a chosen feed item

### ISSUE THREAD

**Issue by craigerd2** [QuiteRSS/quiterss#1284]
My feed. https://api.weather.gov/alerts/active?status=actual

When I right-click on an item I get the Json representation in an external browser.  I'd like to be able to get the cap+xml representation (you change the accept header)  Does not need to be returned in the external browser if you can do it internally.  

To pull the cap+xml,  the instructions are at: https://www.weather.gov/documentation/services-web-api#/default/get_alerts__id_

Is this of interest as a feature to anyone?

**Comment by Funcy-dcm** [comment]
So?
![image](https://user-images.githubusercontent.com/4505526/78666634-0e43d780-78f1-11ea-93f4-9fc3cd898b8b.png)
