### ISSUE TITLE
Allow opening a link that starts with "//" ("http:" missing at the beginning)

### ISSUE THREAD

**Issue by RandomNerd1** [QuiteRSS/quiterss#1285]
This is a strange one, but one of my RSS feeds, for some reason, has its feed item links formed similar to this:

//subdomain.domain.com/thing

The problem is that if I click on the title of the feed item, intending to open it in my default browser (Firefox), QuiteRSS does nothing. The program does still see it as a link, but it doesn't look like it even attempts to pass it on to the browser when clicked.

However, if I copy the link and paste it manually into Firefox (or Chrome, or Internet Explorer, I tested on these even though I don't use them), it is able to open it just fine.

Can QuiteRSS be updated to 'understand' that it can try to pass links formatted this (admittedly-strange) way to external browsers?

**Comment by Funcy-dcm** [comment]
Send link feed

**Comment by RandomNerd1** [comment]
https://chan.sankakucomplex.com/post/atom?tags=rating%3Asafe

**Comment by RandomNerd1** [comment]
So I saw this mentioned as one of the things fixed in 0.19.4, which I was excited to download and try out...but the behavior when I click on the "//subdomain.domain.com/thing" link is the same: nothing happens at all...

**Comment by Funcy-dcm** [comment]
You must remove and re-add the feed

**Comment by RandomNerd1** [comment]
That did it, thanks! :)
