### ISSUE TITLE
В фильтре новостей Заголовок" + "Описание" и "Новости" приводят к разным результатам

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#1288]
Если в фильтре новостей создать следующие фильтры на одну ленту, то их результаты будут отличаться.

В одном фильтре создаем 2 строки:
"Заголовок" + "не содержит" + слово
"Описание" + "не содержит" + слово
выбираем "всем условиям"

потом запускаем фильтр и запоминаем результаты. Затем отменяем фильтрование, создаем и запускаем второй фильтр:

"Новости" + "не содержит" + слово
выбираем "всем условиям"

Поскольку в "Новости" входят "Заголовок" и "Описание", то результат должен быть одинаковым. Или я что-то не так понимаю?

Пользуюсь v0.19.2 на Ubuntu 19.10.

**Comment by Funcy-dcm** [comment]
Всё логично, в первом случае условие работает по "И", во втором по "Или"
