### ISSUE TITLE
Улучшить формулировку "Изменить поведение действия 'Следующая непрочитанная новость'"

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#1289]
Вместо `Изменить поведение действия 'Следующая непрочитанная новость'` лучше `	Действие "Следующая непрочитанная новость" при переходе на следующую ленту всегда выбирает верхнюю новость, вместо самой старой`.

**Comment by Funcy-dcm** [comment]
Слишком громоздко, кому надо и так разобрались )
