### ISSUE TITLE
read articles from one source appear as unread again on every check

### ISSUE THREAD

**Issue by chpasha** [QuiteRSS/quiterss#1293]
I'm running  0.19.2 on ubuntu 18.04 with kde plasma 5.18 and qt 5.14.1. One of the rss feeds appears again and again every single time I check for new articles. I checked it multiple times and it appears correct to me (it also worked without problems with Akregator). I also compared it to another feed which works correctly and the only difference I noticed is that guid tag in problem feed has attribute "isPermalink". Can it cause problems? I've disabled "store db in memory option" and tried to mark feed read and leave the app mutliple times without success. I attach the problem feed, maybe you could investigate further

[feed.zip](https://github.com/QuiteRSS/quiterss/files/4434366/feed.zip)

**Comment by Funcy-dcm** [comment]
Send link feed

**Comment by chpasha** [comment]
This is a local node server that runs on my home server, it is not accessible from outside. If you don't see any problems in the rss (or what could cause problems with reader) I'll try to setup the server somewhere where you can reach it from outside and let you know

**Comment by Funcy-dcm** [comment]
It works with a local file. Things are good

**Comment by chpasha** [comment]
so you can reproduce the problem locally, right?

**Comment by Funcy-dcm** [comment]
Everything works as it should, no problem

**Comment by chpasha** [comment]
then why I'm getting the same articles again and again when I press refresh? What could be wrong?

![image](https://user-images.githubusercontent.com/9569489/78537826-5af3b980-77f0-11ea-98da-db57f42c2a4e.png)

**Comment by Funcy-dcm** [comment]
Check "pubDate"

**Comment by chpasha** [comment]
It is always slightly different, do you think it is a reason? Shouldn't the GUID be the only identifier for unique item?

**Comment by chpasha** [comment]
I've changed the server to return a fixed fake date and it seems to work now. I think it is incorrect that the reader treats the items with same GUID but with changed pubDate as unread again

**Comment by Funcy-dcm** [comment]
When pubDate changes at the same news, it means that the news was edited. But you can enable the option in the feed properties: "Automatically delete duplicate news"

**Comment by chpasha** [comment]
thanks, I will give it a try
