### ISSUE TITLE
QuiteRSS keeps crashing after upgrade to 0.19.3

### ISSUE THREAD

**Issue by rolypolynz** [QuiteRSS/quiterss#1295]
Everything was running fine under 0.19.2 but then upgraded to 0.19.3 and now, every time I open QuiteRSS it crashes and closes as it updates the feeds.
I'm running Windows 10 1909
I've uninstalled QuiteRSS and manually removed any
 folders and files left over under c:\program Files (x86)\... and also from my profile under \AppData\local\...
Then I have re-instaled. When I run QuiteRSS the first time, everything is ok but then there is nothing for it to do.
Then I either import my feeds, refresh the feeds and the app crashes, or, I restore a backup (still can't believe there isn't a restore option in the app!) and again, refresh the feeds and the app crashes.
I only have 15 feeds (can provide the OPML file is needed)
[debug.log](https://github.com/QuiteRSS/quiterss/files/4441374/debug.log)
Thanks,
Roland.

**Comment by Funcy-dcm** [comment]
fix: b747e60dcea54257cc9dbe69eaf5c5bbec4275df

Try test version: http://yadi.sk/d/-mL1zh4gMHXwt

**Comment by rolypolynz** [comment]
Downloaded the test version, but same thing happens.

**Comment by Funcy-dcm** [comment]
Send screenshots: Menu - Help - About - Version, Menu - Help - About - Information
Send debug.log

**Comment by rolypolynz** [comment]
[debug.log](https://github.com/QuiteRSS/quiterss/files/4442417/debug.log)
![About-information](https://user-images.githubusercontent.com/63269128/78637569-bb711c80-78fe-11ea-91d1-49eec57837c8.jpg)
![About-version](https://user-images.githubusercontent.com/63269128/78637582-c0ce6700-78fe-11ea-8ecf-236e346e0759.jpg)

FYI, this is the test version. To get the screen shots I didn't have any feeds loaded. Then to get the debug.log I copied my feeds.db and quiterss.ini from my 0.19.2 install and as it launched and auto updated the feeds, it crashed.

**Comment by Funcy-dcm** [comment]
Is this the debug.log file after the crash?

**Comment by rolypolynz** [comment]
Yes. Not much in it. Is it possible to enable more debugging?

**Comment by Funcy-dcm** [comment]
No. Send a screenshot with a crash error

**Comment by rolypolynz** [comment]
There isn't a crash error, the app just closes. I'll try to create a short video of what happens.

**Comment by Funcy-dcm** [comment]
Good!

**Comment by rolypolynz** [comment]
Wow! What an effort to get this simple video clip.
See if you can download it from here:
https://mega.nz/folder/3c5ElKqD#qWXoV1F4TvdmweJoYA_d2A

**Comment by Funcy-dcm** [comment]
Try new test version: https://yadi.sk/d/yBnwDp7iTsvQhg

**Comment by rolypolynz** [comment]
![About-information](https://user-images.githubusercontent.com/63269128/78744877-c5565680-79b6-11ea-8c5c-f44301ae2eb2.jpg)
![About-version](https://user-images.githubusercontent.com/63269128/78744882-ca1b0a80-79b6-11ea-9140-0b379bc72fe4.jpg)
This new version also crashes as the feeds update. There isn't a debug.log file this time.

**Comment by Funcy-dcm** [comment]
Try new test version (Qt 5.13.2): https://yadi.sk/d/yBnwDp7iTsvQhg

**Comment by rolypolynz** [comment]
That seems to work :)

**Comment by Funcy-dcm** [comment]
Good!
Please, try new test version (Qt 5.14.2 + ext debug): https://yadi.sk/d/yBnwDp7iTsvQhg

**Comment by rolypolynz** [comment]
That crashes and there isn't much in the debug log again.


[debug.log](https://github.com/QuiteRSS/quiterss/files/4449394/debug.log)

**Comment by Funcy-dcm** [comment]
add in quiterss.ini to group [Settings] noDebugOutput = false

**Comment by rolypolynz** [comment]
[debug.log](https://github.com/QuiteRSS/quiterss/files/4449462/debug.log)

**Comment by Funcy-dcm** [comment]
Send your feeds.db and quiterss.ini

**Comment by rolypolynz** [comment]
[feeds.zip](https://github.com/QuiteRSS/quiterss/files/4449508/feeds.zip)

**Comment by Funcy-dcm** [comment]
Unfortunately, I can’t repeat the error
Please, try new test version (Qt 5.14.2 + ext debug): https://yadi.sk/d/yBnwDp7iTsvQhg
add in quiterss.ini to group [Settings] noDebugOutput = false

**Comment by rolypolynz** [comment]
[debug.log](https://github.com/QuiteRSS/quiterss/files/4449712/debug.log)
Still crashes.
Just to be clear it crashes whether I use my existing feeds.db and QuiteRSS.ini or whether I just import my feeds from an OPML file, leaving the QuiteRSS.ini as the default.
As you could see in the video, when I start QuiteRSS it tries to fetch the first 6 or 8 feeds (I haven't counted how many but it's not all of them) and the progress bar at the bottom doesn't move past 0%.
If I don't load my feeds or the QuiteRSS.ini file - ie a default install - and just fetch the QuiteRSS feed, it works. But if I add more feeds, then it fails.

**Comment by Funcy-dcm** [comment]
Please, try new test version (Qt 5.14.2 + ext debug) again: https://yadi.sk/d/yBnwDp7iTsvQhg

**Comment by rolypolynz** [comment]
Still crashes. However, I believe we can narrow it down to a proxy issue. I am using it behind a corporate firewall with proxy autodetect enabled. When I'm not connected to the corporate network, the feeds update successfully :)
Has something changed with the proxy detection in 0.19.3 as it still works perfectly in 0.19.2?

**Comment by Funcy-dcm** [comment]
Thanks for the additional information!
Send debug.log
I want to understand from the debugging information where the error

**Comment by rolypolynz** [comment]
[debug.log](https://github.com/QuiteRSS/quiterss/files/4452753/debug.log)
This debug log was generated while connected to the corp network. It is using the default quiterss.ini but wit the extra debugging turned on. I loaded my feeds from an OPML file.

**Comment by rolypolynz** [comment]
And this debug log is from when I run QuiteRSS without my feeds, just the default QuiteRSS feed, which updates successfully when I'm connected to the corp network.
[debug.log](https://github.com/QuiteRSS/quiterss/files/4452786/debug.log)

**Comment by rolypolynz** [comment]
This debug log is when I'm not connected to the corp network, I start QuiteRSS and it autoupdates the default QuiteRSS feed, then I import my OPML file and it updates all of them successfully.
[debug.log](https://github.com/QuiteRSS/quiterss/files/4452802/debug.log)

**Comment by Funcy-dcm** [comment]
Please, try new test version (Qt 5.14.2 + ext debug) again: https://yadi.sk/d/yBnwDp7iTsvQhg

**Comment by rolypolynz** [comment]
[debug.log](https://github.com/QuiteRSS/quiterss/files/4463729/debug.log)
Still crashes. This was with default QuiteRSS.ini + extra debugging, start QuiteRSS and load feeds from OPML file.

**Comment by Funcy-dcm** [comment]
Was the crash as usual?
Send video

**Comment by rolypolynz** [comment]
Crash is exactly the same as previously, it just closes, no error messages. Also, here is the entry from the Windows event log, not sure if that's any help?

![QuiteRSS-Win-Event-Log](https://user-images.githubusercontent.com/63269128/79040459-b1bc2180-7c3c-11ea-8e83-b4ffd40b7737.jpg)

**Comment by rolypolynz** [comment]
[debug.log](https://github.com/QuiteRSS/quiterss/files/4464379/debug.log)
Link to video that generated debug.log
https://mega.nz/file/uUpySKCI#5wWAU3m47DwP0EtG3geq_1H9lXlub4b93wM0Zn712uY

**Comment by Funcy-dcm** [comment]
Good! Thank you!
Please, try new test version (Qt 5.14.2 + fix + ext debug) again: https://yadi.sk/d/yBnwDp7iTsvQhg

**Comment by rolypolynz** [comment]
That was better, but still crashed. Usual scenario, started QuiteRSS, imported feeeds from opml file, part way through updating the feeds, app crashed. However, this time it got about 20% (according to the progress bar) while normally it dies around 6% or earlier.
[debug.log](https://github.com/QuiteRSS/quiterss/files/4465556/debug.log)
![image](https://user-images.githubusercontent.com/63269128/79056222-31330a80-7ca8-11ea-8c24-4af9127a68d6.png)
![image](https://user-images.githubusercontent.com/63269128/79056229-490a8e80-7ca8-11ea-95a8-81944f2a3f79.png)
Windows event log is exactly the same.

**Comment by Funcy-dcm** [comment]
Send video, please

**Comment by rolypolynz** [comment]
https://mega.nz/file/GAJSTQzR#yFBX-BSINTsARt3zS0pP9TWTi9T4YHLPjDNRkvxdOIs

**Comment by Funcy-dcm** [comment]
Please, try new test version (Qt 5.14.2 + ext debug) again: https://yadi.sk/d/yBnwDp7iTsvQhg

**Comment by rolypolynz** [comment]
[debug.log](https://github.com/QuiteRSS/quiterss/files/4466140/debug.log)
Exactly the same as before.

**Comment by Funcy-dcm** [comment]
Try to change in quiterss.ini `numberRequest=1`

**Comment by rolypolynz** [comment]
It looked like it was working but then crashed gain. Here is the latest debug.log and I'll upload another video shortly.
[debug.log](https://github.com/QuiteRSS/quiterss/files/4471835/debug.log)

**Comment by rolypolynz** [comment]
https://mega.nz/file/ONBz3QSI#V6-5M3kfnAIm7YEkWQzLjNyt4UETTH05GiiG-ChJjzg

**Comment by Funcy-dcm** [comment]
Please, try new test version (Qt 5.14.2 + ext debug) again: https://yadi.sk/d/yBnwDp7iTsvQhg
change in quiterss.ini `numberRequest=1`

**Comment by rolypolynz** [comment]
Another crash. Here is the latest debug log.
[debug.log](https://github.com/QuiteRSS/quiterss/files/4477846/debug.log)

**Comment by Funcy-dcm** [comment]
Please, try new test version (Qt 5.14.2 + ext debug) again: https://yadi.sk/d/yBnwDp7iTsvQhg

**Comment by rolypolynz** [comment]
[debug.log](https://github.com/QuiteRSS/quiterss/files/4484068/debug.log)
Still crashes.

**Comment by Funcy-dcm** [comment]
With `numberRequest=1`?

**Comment by Funcy-dcm** [comment]
Please, try new test version (Qt 5.14.2 + ext debug) again: https://yadi.sk/d/yBnwDp7iTsvQhg

**Comment by rolypolynz** [comment]
New version still crashes @ 26% (always 26%, tried several times).
numberRequest=1 and extra debugging set.
[debug.log](https://github.com/QuiteRSS/quiterss/files/4489607/debug.log)
https://mega.nz/file/7Fh0SQKT#fV4ieweQx6hhKyygw9kCiFJ9TwT7t_eMPWBczpzuuW8

**Comment by Funcy-dcm** [comment]
Ok. This issue is due to Qt 5.14
Please, try test version (Qt 5.13.2) again: https://yadi.sk/d/yBnwDp7iTsvQhg
I will let you know if there will be a new version of Qt ( > 5.14.2). In the meantime, we will try to use Qt 5.13.2

**Comment by rolypolynz** [comment]
That works perfectly. Any chance of an installer rather than the portable version?

**Comment by Funcy-dcm** [comment]
Later there will be an official release of the new version.
