### ISSUE TITLE
Change margins on text view

### ISSUE THREAD

**Issue by senseiski** [QuiteRSS/quiterss#1297]
Hello, is there a way to expand the margin on the sides for the article content (from the rss feed, not browser)? I've attached as screenshot to illustrate. I assume it has to do with css, but I know nothing about it.

![Screenshot at 2020-04-12 20-35-04](https://user-images.githubusercontent.com/6433919/79075705-2060b400-7cfd-11ea-90c3-25b6436cec23.png)

**Comment by Funcy-dcm** [comment]
Change `news.css`: 

.newsTable {
  padding: **25**px;
}

**Comment by senseiski** [comment]
> Change `news.css`:
> 
> .newsTable {
> padding: **25**px;
> }

Sorry, do I just add that to the end of the file? I'm totally CSS illiterate.

**Comment by Funcy-dcm** [comment]
No, find `.newsTable`. In it change: padding: **5**px;
