### ISSUE TITLE
Новость без ссылки не распознается как дубликат

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#1298]
В [этом](https://rss.nixnet.services/?action=display&bridge=Facebook&context=User&u=BuergerinitiativegegenBreitspurbahn&media_type=all&limit=-1&format=Atom) фиде есть новость без ссылки (см. "Anlässlich der österreichweiten Aktion…"). Несмотря на то, что в настройках фида включено "автоматическое удаление дубликатов новостей", на ту новость без ссылки это не распространяется, поскольку она на следующий день появляется заново в непрочитанном состоянии.

Хотелось, чтобы та новость появлялась только раз.

QuiteRSS v0.19.2 (26.11.2019)
Ревизия git-3862-89cb677
Включает: Qt-5.12.4, SQLite-3.29.0, WebKit-602.1
Ubuntu 19.10

**Comment by sojusnik** [comment]
Та новость без ссылки появляется не только на следующий день, но и где-то 2-3 раза в день, если обновлять фиды каждый час.

**Comment by Funcy-dcm** [comment]
Сам сайт генерирует новый Id для этой новости (похоже эта на ошибку в генерации xml).
Вы можете написать либо владельцу сайта и сообщить о проблеме.
Либо в свойствах ленты настроить "Добавлять новость в БД с датой..."
