### ISSUE TITLE
Doesn't get the feed when using OpenVPN connections on Windows 10

### ISSUE THREAD

**Issue by JohnPlanetary** [QuiteRSS/quiterss#1299]
In the latest version 0.19.3 and at least in the previous one to that, the QuiteRSS can't grab the feeds (Youtube and others) and also can't find the program updates, when using OpenVPN on Windows 10. I've tried with ProtonVPN, but also doesn't work with other OpenVPN compatible services, if I turn off the OpenVPN connection it will work.

All other programs are working just fine with the VPN.
Changing connection settings on the program also doesn't help.
Restart the program, or even the computer doesn't have any effect.
I can always reproduce these problem.

**Comment by Funcy-dcm** [comment]
Try test portable version: https://yadi.sk/d/yBnwDp7iTsvQhg
