### ISSUE TITLE
(feature request) relative format in feed timestamps

### ISSUE THREAD

**Issue by darkred** [QuiteRSS/quiterss#1300]
Greetings

I love QuiteRSS, it's the best RSS reader! Thanks a lot for your great work!

I'd like to make a suggestion: 
to offer an option to display the timestamps in the "Published" column in **relative format**:
e.g. instead of:
```
17:21
14:14
12.4.20
15.2.20
```
to become:
```
1 min ago
3 hours ago
6 days ago
2 months ago
```
and the initial, absolute timestamps to appear as tooltip (=when you mouseover them).

The relative timestamps should be recalculated every minute: 
- either **all** (=all entries of all feeds) **at once**, 
- or (for better performance) **only those that are currently visible to the user**, 
and the rest timestamps to get (re)calculated only as you scroll a feed/switch feeds.

Thank you

**Comment by Funcy-dcm** [comment]
Unfortunately this is not possible
