### ISSUE TITLE
no Qt platform plugin could be initialized

### ISSUE THREAD

**Issue by MichelZ** [QuiteRSS/quiterss#1302]
After updating to the latest version (0.19.4) on Windows 10, when trying to start it I get:

"This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem."

(Reinstalling did not work)

Any ideas?

**Comment by Funcy-dcm** [comment]
Portable?
Send screenshots

**Comment by MichelZ** [comment]
Not portable.

Screenshot of error right when launching:
![image](https://user-images.githubusercontent.com/1040252/79832127-0a13c180-83a9-11ea-91e7-cb865ad3210a.png)


Files in main directory:
![image](https://user-images.githubusercontent.com/1040252/79832077-ee102000-83a8-11ea-89fd-00e4b0a05653.png)

Files in platform directory:
![image](https://user-images.githubusercontent.com/1040252/79832091-f5372e00-83a8-11ea-96f0-d5fd9c7e7752.png)

**Comment by RandomNerd1** [comment]
Having the same issue.

**Comment by Funcy-dcm** [comment]
Found a problem, now I solve

**Comment by Funcy-dcm** [comment]
Try downloading again

**Comment by RandomNerd1** [comment]
Just redownloaded "QuiteRSS 0.19.4 Installer Windows" and same error. Was that specific exe updated?

**Comment by MichelZ** [comment]
Same here

**Comment by Funcy-dcm** [comment]
Site cache has not been cleared. Try downloading again late. 
Only the installer has changed: QuiteRSS-0.19.4-Setup
Check: MD5: d5a833dea34712d46e287934f9218db0

**Comment by Funcy-dcm** [comment]
Try downloading again

**Comment by MichelZ** [comment]
Works now!!! Thank you very much!
