### ISSUE TITLE
Избыточное уведомление об обновлении 19.4

### ISSUE THREAD

**Issue by grisha999** [QuiteRSS/quiterss#1303]
Добрый день. Стояла 19.3. Вышла 19.4. Запустил updater.exe из папки quiterss, программа обновилась нормально, но теперь при запуске программы появляется всплывающее окно - " Проверить наличие обновлений", хотя по факту последняя версия 19.4 уже установлена. В окне "о программе" видна версия 19.4, в окне "проверить наличие обновлений" - текущая версия 19.4 , ваша версия - 19.3. Как устранить баг? при попытке установки поверх - прога не запускается с ошибкой QT. Win 7 64bit ESU Updated

**Comment by Funcy-dcm** [comment]
Установщик не был обновлён из-за старых данных в кэше
