### ISSUE TITLE
0.19.4 build fails with qt 5.14.1

### ISSUE THREAD

**Issue by lgbaldoni** [QuiteRSS/quiterss#1304]
See [log](https://github.com/QuiteRSS/quiterss/files/4509897/quiterss_0194_qt5141.txt).

**Comment by Funcy-dcm** [comment]
What is your version of Webkit?

**Comment by lgbaldoni** [comment]
> What is your version of Webkit?

5.212~alpha3

**Comment by Funcy-dcm** [comment]
You need alpha 4. Or you can take the latest changes cf2e6b384b858e9d3243f0f3d6ec47ed0f267280

**Comment by lgbaldoni** [comment]
I confirm that solved the problem, TYVM.
