### ISSUE TITLE
Unreadable article for RTL language

### ISSUE THREAD

**Issue by 2dvision** [QuiteRSS/quiterss#1305]
At current, I use "QuiteRSS 0.18.12 Portable Windows" on Windows 7 64bit and Right-to-left layout is enabled.

RSS feed for test: https://www.independentpersian.com/rss.xml

---

**QuiteRSS 0.18.12 Portable Windows**
![rss18](https://user-images.githubusercontent.com/16509592/79865058-ca23fd00-83ef-11ea-9f5a-62472bb26112.jpg)
**Gif**
![rss18](https://user-images.githubusercontent.com/16509592/79865088-d7d98280-83ef-11ea-83c3-a5d00b7525db.gif)

---

I can't read article in next releases like 0.19.4.

There are several problem:
1. Article name don't display completely.
2. Line don't support wrap.
3. If change article section size, words are unreadable, Lines merge together.

**QuiteRSS 0.19.4 Portable Windows**
![rss19](https://user-images.githubusercontent.com/16509592/79865155-f50e5100-83ef-11ea-9564-6b98a7714a0b.jpg)
**Gif**
![rss19](https://user-images.githubusercontent.com/16509592/79865189-00617c80-83f0-11ea-9054-a9ff0177080f.gif)

**Comment by Funcy-dcm** [comment]
This is a webkit error.

**Comment by 2dvision** [comment]
Is there a solution to solve this problem? do you have a plan to solve it?

**Comment by Funcy-dcm** [comment]
Unfortunately, I can’t do anything. This is a third-party module.
I can try you to build the latest version with the old webkit
