### ISSUE TITLE
Link to quiterss archlinux is 404

### ISSUE THREAD

**Issue by Strubbl** [QuiteRSS/quiterss#1306]
Quiterss made it into the official archlinux packages. So the link to the aur is not valid anymore.

The link from the [download page](https://quiterss.org/quiterss-for-other-os) points to the [AUR](https://aur.archlinux.org/packages/quiterss/), but that is no longer valid. New link is: 
https://www.archlinux.org/packages/community/x86_64/quiterss/

Or if you want to add the official way to install quiterss in archlinux, it's

`pacman -S quiterss`

**Comment by Funcy-dcm** [comment]
Ok
