### ISSUE TITLE
Огромные отступы в панели лент

### ISSUE THREAD

**Issue by Crandel** [QuiteRSS/quiterss#1307]
OS: Arch Linux, i3wm
После обновления QT отступы на панели лент стали огромными, если дополнительные мониторы подключены к ноутбуку. Скорее всего дело в DPI, но до этого обновления все показывало отлично. Использую qt5ct для настройки QT приложений 
```
xdpyinfo | grep -B2 dots
screen #0:
  dimensions:    5760x1080 pixels (312x175 millimeters)
  resolution:    469x157 dots per inch
```
![2020-04-22_10-10](https://user-images.githubusercontent.com/4005032/79958071-07c96a00-8472-11ea-9a93-7b0ea13194a1.png)

Когда мониторы отключены, отступы минимальные

**Comment by Funcy-dcm** [comment]
Самом приложении для линукса правок с настройками DPI не было начиная версии 0.18.12.
Проблема действительно в Qt. И чем помочь не знаю
Как вариант можете сбросить шрифты в настройках приложения по умолчанию

**Comment by Crandel** [comment]
В qt5ct есть style sheets, выглядят вот так
```
QMenuBar, QMenu, QToolBar, QStatusBar, QFrame, QScrollBar {
    border: none;
}
``` 
Можете подсказать, какие элементы отвечают за этот список? Я попробую поискать, как можно их настроить

**Comment by Funcy-dcm** [comment]
К сожалению, тут подсказать ничем не могу

Я внёс правки в код, с изменениями DPI 5a3a5226ffc61893dcad60b193b00fb1edc9fa4f  можете попробовать проверить?

**Comment by Crandel** [comment]
Спасибо за попытку!
Я перешел на sway и wayland и там такой проблемы больше нету. 
У вас отличная программа!
