### ISSUE TITLE
Can't hide browser window

### ISSUE THREAD

**Issue by qcybb** [QuiteRSS/quiterss#1308]
Just upgraded to version 0.19.4, and now I can't hide the browser window in QuiteRSS screen.

This wasn't an issue in v0.19.3.

![quiterss](https://user-images.githubusercontent.com/16991734/80018342-bb3e5880-848a-11ea-88bf-fc4f6fc89673.png)

**Comment by qshbxz** [comment]
I want to hide this thing, too

**Comment by qcybb** [comment]
Any plans to have this fixed in the next release?

**Comment by Funcy-dcm** [comment]
This is done on purpose, as could accidentally hide

**Comment by Funcy-dcm** [comment]
I will add an option: Menu - View - Show/Hide - Browser

**Comment by qshbxz** [comment]
> I will add an option: Menu - View - Show/Hide - Browser

i love u

**Comment by qcybb** [comment]
> I will add an option: Menu - View - Show/Hide - Browser

Thank you!
