### ISSUE TITLE
Can't open a url in quiterss browser using the address field

### ISSUE THREAD

**Issue by WhoWouldaThunk** [QuiteRSS/quiterss#1310]
Related to the fix in https://github.com/QuiteRSS/quiterss/issues/1069
where you need to goto the webpage first, and then add the feed.

The problem being that you can't put an address into the browser field, hit enter, and have it goto the link. For whatever weird reason, the enter key does not work.

BUT

Using enter on the number pad does. Ideally, there should be a go button as browsers have, and, the enter key should work to submit the url, also.

**Comment by Funcy-dcm** [comment]
You need to disable shortcut "Return" in settings

**Comment by WhoWouldaThunk** [comment]
Thanks!

How does that shortcut even work? I've been clicking enter on everything I possibly can and I haven't been able to figure out what open news actually does.
