### ISSUE TITLE
QuiteRSS not updated in ubuntu PPA repository

### ISSUE THREAD

**Issue by pmanu93** [QuiteRSS/quiterss#1311]
Tried to install via `apt` but its not the latest version and keeps showing a dialog saying that theres a new version available...

![Captura de ecrã de 2020-04-27 13-42-08](https://user-images.githubusercontent.com/15691766/80373481-0a222e80-888d-11ea-8d23-6884ff55ba59.png)

Will it be available anytime soon?

Thanks in advance

**Comment by Funcy-dcm** [comment]
There is a new version. But the maintainer did not build for your OS.
I build only for Windows and Mac OS

**Comment by pmanu93** [comment]
I knew that there was a new version. :)
Anyway.. its fixed. The maintainer already uploaded the latest package (Thanks Andrey Palkin!)

Thank you guys!
