### ISSUE TITLE
Version 0.19.4 does not start on Windows 10

### ISSUE THREAD

**Issue by iniOr** [QuiteRSS/quiterss#1315]
Hi,

when starting the program :

![image](https://user-images.githubusercontent.com/43171930/80860566-b33f9f00-8c68-11ea-819f-de69204da6a9.png)

How to solve this ?
Re-installing does not work.

Thanks in advance

**Comment by Funcy-dcm** [comment]
Did you have a different version before this version?

**Comment by iniOr** [comment]
Hi apparently i got version 19.3 previously installed I get quiterss on Chocolatey : https://chocolatey.org/packages/quiterss#versionhistory

**Comment by Funcy-dcm** [comment]
Use: https://quiterss.org/ru/download
