### ISSUE TITLE
0.19.4: SSL handshake failed (6)

### ISSUE THREAD

**Issue by onlyjob** [QuiteRSS/quiterss#1318]
On Debian I'm trying to create a new feed from the following URL: https://www.mintpressnews.com/rss/
but it fails with `SSL handshake failed (6)` for no apparent reason (certificate is valid and Firefox is happy).

Where to override??

Also error message could have been more detailed.

Thanks.

**Comment by Funcy-dcm** [comment]
Error in assembly

**Comment by onlyjob** [comment]
This is quite unhelpful... :(  What do you mean??

**Comment by Funcy-dcm** [comment]
Unfortunately, I collect only for windows. You need to contact the debian maintainer
If the assembly is correct, there will be no error

**Comment by onlyjob** [comment]
I am the Debian maintainer and build is done correctly.
Also I have about 100 RSS feeds that work perfectly.
The problem only manifests with this particular feed (as far as I can say).
Please investigate.

**Comment by Funcy-dcm** [comment]
Send screenshots

**Comment by Funcy-dcm** [comment]
It works for me as it should (windows 10)

**Comment by onlyjob** [comment]
> Send screenshots

Seriously? Error message literally says "SSL handshake failed (6)" and there is nothing more you can get from the screenshot.

How can I get a more detailed error message? Is there a "debug" mode? How to troubleshoot?

**Comment by sojusnik** [comment]
Same here on Ubuntu 20.04 with [this](https://www.cirrus7.com/blog/rss) feed. If I go to Properties > Status of this feed, then I see: Квитирование SSL не удалось (6)

**Comment by Funcy-dcm** [comment]
I can’t understand exactly where you see the error

**Comment by sojusnik** [comment]
![grafik](https://user-images.githubusercontent.com/1245718/81914510-ae1c1180-95d1-11ea-86ed-924c9d9922f1.png)

**Comment by Funcy-dcm** [comment]
![image](https://user-images.githubusercontent.com/4505526/81919057-c2233b80-95f0-11ea-803a-734f1afb0946.png)

**Comment by sojusnik** [comment]
That's strange indeed. I get this error message only in this feed, from my 100+ feeds. Can this be a Debian based issue?

**Comment by Funcy-dcm** [comment]
Do you have other https feeds?

**Comment by onlyjob** [comment]
I have plenty of HTTPS feeds and they are all working without issues. Out of curiosity I've added https://www.cirrus7.com/blog/rss (which @sojusnik have problems with) and it worked properly.
However the original feed (https://www.mintpressnews.com/rss/) can not be added.

Could it be a QT/webkit issue?

**Comment by Funcy-dcm** [comment]
What version of Qt?
Doesn't depend on webkit

**Comment by onlyjob** [comment]
Qt v5; Build does depend on webkit library: `libqt5webkit5 (>= 5.212.0~alpha2)`.

**Comment by Funcy-dcm** [comment]
Qt 5.14.2?

**Comment by onlyjob** [comment]
```
 libqt5concurrent5 (= 5.11.3+dfsg1-1+deb10u3),
 libqt5core5a (= 5.11.3+dfsg1-1+deb10u3),
 libqt5dbus5 (= 5.11.3+dfsg1-1+deb10u3),
 libqt5designer5 (= 5.11.3-4),
 libqt5designercomponents5 (= 5.11.3-4),
 libqt5gui5 (= 5.11.3+dfsg1-1+deb10u3),
 libqt5help5 (= 5.11.3-4),
 libqt5multimedia5 (= 5.11.3-2),
 libqt5multimediagsttools5 (= 5.11.3-2),
 libqt5multimediaquick5 (= 5.11.3-2),
 libqt5multimediawidgets5 (= 5.11.3-2),
 libqt5network5 (= 5.11.3+dfsg1-1+deb10u3),
 libqt5opengl5 (= 5.11.3+dfsg1-1+deb10u3),
 libqt5positioning5 (= 5.11.3+dfsg-2),
 libqt5printsupport5 (= 5.11.3+dfsg1-1+deb10u3),
 libqt5qml5 (= 5.11.3-4),
 libqt5quick5 (= 5.11.3-4),
 libqt5quickparticles5 (= 5.11.3-4),
 libqt5quicktest5 (= 5.11.3-4),
 libqt5quickwidgets5 (= 5.11.3-4),
 libqt5sensors5 (= 5.11.3-2),
 libqt5sql5 (= 5.11.3+dfsg1-1+deb10u3),
 libqt5sql5-sqlite (= 5.11.3+dfsg1-1+deb10u3),
 libqt5test5 (= 5.11.3+dfsg1-1+deb10u3),
 libqt5webchannel5 (= 5.11.3-2),
 libqt5webkit5 (= 5.212.0~alpha2-21),
 libqt5webkit5-dev (= 5.212.0~alpha2-21),
 libqt5widgets5 (= 5.11.3+dfsg1-1+deb10u3),
 libqt5xml5 (= 5.11.3+dfsg1-1+deb10u3),
```

**Comment by Kein** [comment]
I'm having the same issue on Windows build, for https://blog.discord.com/feed or https://www.ixbt.com/export/news.rss, random SSL handshake errors.

**Comment by onlyjob** [comment]
They are not _random_ SSL handshake errors, but deterministic 100% reproducible on certain web sites.

**Comment by Kein** [comment]
> 100% reproducible

Really. That's odd, they are no longer reproducible.

**Comment by onlyjob** [comment]
On my up-to-date Debian Buster the problem is deterministic and reliably reproducible.

**Comment by Kein** [comment]
So do you know what causes issue? Certificates definitely fine. Outdated SSL imlementation?
