### ISSUE TITLE
Can't find feed url

### ISSUE THREAD

**Issue by morefilms** [QuiteRSS/quiterss#1331]
Hello. Why don't work this rss
https://wwvw.zone-annuaire.com/rss.xml

**Comment by mark05e** [comment]
I think the website has some sort of firewall which blocks certain types of requests. When you access from the browser it seems to work but when you run it on feed validator service, it seems to give a capcha page.

Examples:

[Feedvalidator.org](https://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwwvw.zone-annuaire.com%2Frss.xml)
![image](https://user-images.githubusercontent.com/1783193/84348280-3e437b80-abbd-11ea-8283-30c618d82182.png)

[W3C Feed Validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwwvw.zone-annuaire.com%2Frss.xml)
![image](https://user-images.githubusercontent.com/1783193/84348350-6501b200-abbd-11ea-9d40-b8fa52bd7be0.png)
