### ISSUE TITLE
ability to disable embedded browser

### ISSUE THREAD

**Issue by hamidhtc** [QuiteRSS/quiterss#1336]
i dont need embedded browser , please make ability to disable it.
![Untitlببed](https://user-images.githubusercontent.com/7674614/86508829-5f803c00-bdf8-11ea-8bdc-d1ac6cc2d72e.png)

**Comment by qcybb** [comment]
You can wait for the update - which includes a new option to do just this -or- do this :

1 - Exit quiterss
2 - Open QuiteRSS.ini (you can see where it is located for you in the "about" section of QuiteRSS help option).
3 - Replace the "NewsTabSplitterState=..." line by:
NewsTabSplitterState=@bytearray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x5!\0\0\0\0\0\0\0\0\x1\x1\0\0\0\x2\0)
4 - Save and reopen QuiteRSS.
