### ISSUE TITLE
Improvment suggestion : Threads

### ISSUE THREAD

**Issue by jediafr** [QuiteRSS/quiterss#1343]
On some RSS feeds  i get multiple time the same article title, could you help regrouping those in one thread or at least get us a rule to mark them as read, or delete them ?

**Comment by tonypachino** [comment]
where i can suggest a new feature?

**Comment by Funcy-dcm** [comment]
Menu - Tools - Options - Feeds - Automatically mark identical news as read
Properties feed - Automatically delete duplicate news

**Comment by jediafr** [comment]
> Menu - Tools - Options - Feeds - Automatically mark identical news as read
> Properties feed - Automatically delete duplicate news

Big thank you for taking the time to answer.
