### ISSUE TITLE
Can't find feed URL!

### ISSUE THREAD

**Issue by rm76** [QuiteRSS/quiterss#1362]
First of all, thank you for developing and maintaining your beautiful news aggregator!
My attempt to create a feed from URL http://documenti.camera.it/apps/rssFeeds/ultimiStampati/pdlUltimiStampati.asp?idLegislatura=18 fails with error "Can't find feed URL!".
But if I open that URL in Firefox, I can see that it is a valid URL.
I'm not a programmer so I wouldn't know how to proceed from here.
I'd be very grateful if you could help me!
Thanks!

**Comment by darcosion** [comment]
Hello, 

I've tried some `curl http://documenti.camera.it/apps/rssFeeds/ultimiStampati/pdlUltimiStampati.asp?idLegislatura=18` with same user agent than QuiteRSS and it's work. So I can assume that it's not an issue relative to website configuration. :)

Can you please precise which Operating System you use ? 

An `QuiteRSS.log` file would be appreciable also.

**Comment by rm76** [comment]
Thank you. The feed has a problem. I contacted camera.it IT staff and they fixed it. Now everything works as expected. Thanks.
