### ISSUE TITLE
How to read a feed that has CloudFlare?

### ISSUE THREAD

**Issue by JLChamberlain** [QuiteRSS/quiterss#1368]
I've had a feed in QuiteRSS for a few years now but recently has become unable to receive content from the feed (I believe due to a new CloudFlare implementation on the site), instead of receiving content I receive the status "Error transferring https://hikarinoakariost.info/feed/ - server replied: Service Temporarily Unavailable (403)". Is there any way to remedy this?

**Comment by darcosion** [comment]
Hello, 

hikarinoakariost.info redirect to hikarinoakari.com for me now, can you confirm this redirection ?
You'r right about cloudflare, if you `dig hikarinoakari.com`, they provide two cloudflare's IP.

I assumed than it's been problem relative to a migration of the website.

I can `curl` and `wget` the new website by the way.
