### ISSUE TITLE
When the information source is added，Could not add  TinyTinyRSS service

### ISSUE THREAD

**Issue by ZhuningS** [QuiteRSS/quiterss#1385]
When the information source is added，Could not add  TinyTinyRSS service
URL: http://192.168.1.103:1281/index.php
hint RSS URL not exist
![image](https://user-images.githubusercontent.com/38108376/102078432-e45e8f80-3e45-11eb-8848-350c0e49847d.png)

**Comment by Funcy-dcm** [comment]
TinyTinyRSS is not supported
