### ISSUE TITLE
[REQ] ability to convert DOI links into Sci-Hub links

### ISSUE THREAD

**Issue by firinael** [QuiteRSS/quiterss#1393]
this would become my de-facto RSS reader _(and one I'd recommend to every academic)_ if I was able to convert the links from scientific journals' feeds into sci-hub links.

there's been an implementation of this sort of thing as a [Tiny Tiny RSS plugin](https://github.com/joshp23/ttrss-to-Sci-Hub), but I'm not exactly a programmer so I've no idea how it'd be possible to implement it into QuiteRSS.

cheers!

**Comment by senseiski** [comment]
@firinael have you tried using zotero for that (rss feeds for journals + addon to use sci-hub)?
