### ISSUE TITLE
Application Update Notification

### ISSUE THREAD

**Issue by mrspirytus** [QuiteRSS/quiterss#1394]
Hello,

I just installed QuiteRSS using PPA on my Ubuntu Mate 20.04. Version I am running is Version 0.19.3 (29.01.2020)
But I get occasional popup that Version 0.19.4 is available. 
```$ sudo apt update```
Does not seem to show any updates.
Is 0.19.4 update been removed for some reason?

**Comment by Funcy-dcm** [comment]
Developers are not affiliated with the Ubuntu repository
