### ISSUE TITLE
After latest update can no longer open feeds, only can open the most recent entry

### ISSUE THREAD

**Issue by VictorVow** [QuiteRSS/quiterss#1395]
Since the latest update I can no longer view each feed, it just opens as blank whenever I click on it. 

![](https://i.imgur.com/dPLsAAu.png)

I'm able to get it to open directly to the most recent unread story by setting Options > Feeds > General > Action on feed opening > "Open the news". But this is hardly a replacement for being able to open the feed normally.

**Comment by VictorVow** [comment]
Ended up just restoring a backup of `QuiteRss.ini` from a few days ago but yeah still have no idea what that bug was or how it could have been otherwise fixed.

**Comment by Funcy-dcm** [comment]
![68747470733a2f2f692e696d6775722e636f6d2f64504c734141752e706e67](https://user-images.githubusercontent.com/4505526/104286284-a3a27680-54d6-11eb-9e9b-b5a219b3c026.png)

**Comment by VictorVow** [comment]
Ahh I see. It'd be good if the UI was adjusted to make this more noticeable. Maybe a right-pointing arrow at the left edge of the bar, which would open the page in full again?
