### ISSUE TITLE
Request: Launching QuiteRSS without GUI window or splash screen (to be used to launch at startup in the background)

### ISSUE THREAD

**Issue by KSXGitHub** [QuiteRSS/quiterss#1396]
QuiteRSS should add a CLI flag called `--background` to enable launching tray icon without showing splash screen or GUI window. This would be used to create a background service that notifies user on new feeds.

**Comment by Funcy-dcm** [comment]
Menu-Tools-Options-General-Show splash
Menu-Tools-Options-System tray-Move to the...-starting...

**Comment by KSXGitHub** [comment]
@Funcy-dcm The solution you proposed require modifying configuration. However, I want to create a desktop file at `$HOME/.config/autostart` or a systemd service.

**Comment by Funcy-dcm** [comment]
We have a GUI application

**Comment by KSXGitHub** [comment]
@Funcy-dcm My point wasn't "modifying configuration is hard", it was "configuration cannot be distributed via a package manager".
