### ISSUE TITLE
Request: Native notification

### ISSUE THREAD

**Issue by KSXGitHub** [QuiteRSS/quiterss#1397]
Instead of a custom GUI window, I prefer a more integrated notification (the one that `notify-send` and `akgregator` use).

When there is exactly 1 new item, the notification should show the feed's title as "summary" and the item's title as "body".

When there are multiple new items from exactly 1 feed, the notification should show the feed's title as "summary" and the total number of new items as "body".

When there are multiple new items from multiple feeds, the notification should show the total number of new items.

**Comment by Funcy-dcm** [comment]
Use notification settings, we do not plan to do native notification

**Comment by KSXGitHub** [comment]
@Funcy-dcm Why? Non native notification is annoying. It would be far more convenient to handle all notifications in one place.

If all apps use their own custom notification, then user would have to close each one of them in different ways multiple times. If all apps use native notification, then user could manage all of them in a few keystrokes.
