### ISSUE TITLE
Bug with a flash player

### ISSUE THREAD

**Issue by Z0nder** [QuiteRSS/quiterss#1405]
Very annoying issue that if there in the news is a link which ends like "mp4" or "mkv" then internal browser shows this at the top (painted red square):

![alt text](https://i.imgur.com/7tHcRXR.png)

Instead of the news content at top, I see this player, there is nothing in the news to play.
Is it possible to remove it together with that "Link to video" somehow?
If I disable JS and plugins then still I see a white space with that "Link to video".

Feed link:
http://rlsbb.ru/category/foreign-movies/feed/

**Comment by Funcy-dcm** [comment]
The feed itself contains a video block, so we reflect this according to the standard

**Comment by Purfview** [comment]
> 
> 
> The feed itself contains a video block, so we reflect this according to the standard

I wrote that "there is nothing in the news to play", so it doesn't contain "video block". 
Only a link formated  for example as "www.site.com/download/dks3dls6dl.mkv", they don't link to video directly.

**Comment by Funcy-dcm** [comment]
```
<enclosure url="https://uploadgig.com/file/download/b2159c6a1a4b7081/S.2020.RUSSIAN.720p.BluRay.x264.DTS-FGT.mkv" length="0" type="video/x-matroska" />
<enclosure url="http://nitroflare.com/view/B613FE85B7D9D15/S.2020.RUSSIAN.720p.BluRay.x264.DTS-FGT.mkv" length="0" type="video/x-matroska" />
```

**Comment by Z0nder** [comment]
Oh, I see now.
But still "I see a white space with that "Link to video"" if I disable plugins, could it be tweaked that it would show nothing?
