### ISSUE TITLE
internal Browser: broken on pages with responsive design

### ISSUE THREAD

**Issue by qrssuser** [QuiteRSS/quiterss#1407]
Hi,

few time ago, tagesschau.de changed their design to a "mobile devices friendly design", so they said. Since then quiterss cannot display these pages in a good readable way. Please see the attached screenshots of QuiteRSS 0.19.4 and Internet Explorer 11 for details. You can self experience it using this url: http://www.tagesschau.de/xml/rss2.

greetings
Jens

![quiterssbugreport 01](https://user-images.githubusercontent.com/78318921/106395022-3a8c8f80-6400-11eb-9e6d-a7fc1e72a192.jpg)
![quiterssbugreport 02](https://user-images.githubusercontent.com/78318921/106395032-46785180-6400-11eb-88fa-4fc9ceca1d6c.jpg)

**Comment by senseiski** [comment]
The feed works fine on Linux. Have you enabled Javascript for the feed? For me it works equally well with and without it, but it might be different on Windows.
![Screenshot from 2021-02-04 23-20-23](https://user-images.githubusercontent.com/6433919/106956677-a001b880-673f-11eb-9895-2b7e212e22ae.png)

**Comment by qrssuser** [comment]
Hello Senseiski,
thanks for reviewing!
I don't know what happened, but it is working again. JavaScript was activated and I did some restarts over a few days before posting, to avoid reporting a "bug" on a temporary problem, but in the end it was a temporary one. As my external Browsers were displaying the pages correctly and the internal Browser did as well with other ("traditional") web pages,  I guess it was a local problem in the dependencies of the internal Browser related to html5 or something else quite new.
Greetings,
Jens
