### ISSUE TITLE
Is Quiterss development dead?

### ISSUE THREAD

**Issue by Motocycle347** [QuiteRSS/quiterss#1416]
Is Quiterss development dead?

**Comment by Funcy-dcm** [comment]
Probably yes

**Comment by darcosion** [comment]
No !!! We hold the line !

![spongetemplate](https://user-images.githubusercontent.com/16328515/107963961-1789e000-6fa9-11eb-9683-7dc3f168b4ff.png)

**Comment by neuhaus** [comment]
I'm wondering about the same thing. Looks like the last release was 3 years ago.

**Comment by Katarn** [comment]
Currently the most active fork is https://github.com/ChiaYen-Kan/quiterss
True, there is no possibility to create an issues.
