### ISSUE TITLE
Google logo in Youtube feeds?

### ISSUE THREAD

**Issue by MoneyAllDay** [QuiteRSS/quiterss#1465]
Is it just me that when adding a new feed from Youtube it places a Google logo instead of the Youtube one?

![screenshot 2021-07-11 00 37 53](https://user-images.githubusercontent.com/19583547/125178850-677b7480-e1e0-11eb-98c0-e629ea8c1a72.png)

**Comment by Teezton** [comment]
Same problem here.

![Image 005](https://user-images.githubusercontent.com/5905860/128015508-285a26e2-1843-4667-a95b-96816377fe63.png)

**Comment by MoneyAllDay** [comment]
As of today 12/Aug/2021 this issue seems to be solved by itself, most likely a problem with Youtube.

Reason for which i'm closing this.
