### ISSUE TITLE
What's the best way to check dead feeds? [Newbie question]

### ISSUE THREAD

**Issue by p2635** [QuiteRSS/quiterss#1467]
I'm migrating from Feedbro (FF addon) and on there, you can view feeds that are last retrieve date/broken etc.
![image](https://user-images.githubusercontent.com/4522927/126070731-190cd02f-7f81-4c08-92d6-b74c0690e2a4.png)

What's the best way to do this on QuiteRSS?

**Comment by Teezton** [comment]
> I'm migrating from Feedbro (FF addon) and on there, you can view feeds that are last retrieve date/broken etc.
> ![image](https://user-images.githubusercontent.com/4522927/126070731-190cd02f-7f81-4c08-92d6-b74c0690e2a4.png)
> 
> What's the best way to do this on QuiteRSS?

> Feedbro

**First Option**

![Image 004](https://user-images.githubusercontent.com/5905860/128025847-e9d74a4f-9676-40d9-b481-267829151637.png)

**Second Option**

Check for icons with a red cross.

![Image 003](https://user-images.githubusercontent.com/5905860/128025153-0b22d86c-7500-4093-867b-6fb8dad68905.png)

**Third Option**

![Image 001](https://user-images.githubusercontent.com/5905860/128024011-74e94c12-6b43-4d91-9a7e-3a144318861b.png)

**Fourth Option**

Go to _C:\Users\Username\AppData\Local\QuiteRss\QuiteRss_
Find _debug.log_ and check lines with this word:

![Image 002](https://user-images.githubusercontent.com/5905860/128024925-9fb05683-a11d-4c17-b5e8-377a66bb7db1.png)

**Comment by p2635** [comment]
Thank you so much @Teezton , now I can keep things clean
