### ISSUE TITLE
Dependency on qtwebkit

### ISSUE THREAD

**Issue by lgbaldoni** [QuiteRSS/quiterss#1470]
I'm the maintainer of quiterss for openSUSE and I've just been informed that the package is about to be deleted because qtwebkit is about to be dropped.

Is it possible to build quiterss without it? Or is there any plan to patch it?

Thanks

**Comment by Funcy-dcm** [comment]
Unfortunately, qtwebkit won't work without it.  Everything is very much tied to qtwebkit.
