### ISSUE TITLE
Can't find a "Dark Mode" setting in Windows

### ISSUE THREAD

**Issue by kb6ojs** [QuiteRSS/quiterss#1501]
I've configured Windows to use Dark Mode for all apps, and for Windows itself, but QuiteRSS doesn't pick up on that by itself.  There doesn't _**seem**_ to be a setting in the app to make an app-specific setting for Dark Mode.  I read in other postings that QuiteRSS _**does**_ recognize a dark-mode OS configuration in Linux, but it doesn't **_appear_** to do so in Windows.

Am I missing something, and if so can you point me to it?

Thanks.  //Steve//

**Comment by hffaust** [comment]
I had the exact same problem the other day. Take a look at this screenshot, it should help. 
![image](https://user-images.githubusercontent.com/15644021/147626374-3d30dd05-76fa-4f1c-9436-11f7a20202cc.png)

**Comment by hffaust** [comment]
So in summary: Settings Button > View > Application Style > Dark

**Comment by kb6ojs** [comment]
Thanks.  Both messages are appreciated, and both gave me the answer I needed.

 

//Steve//

**Comment by hffaust** [comment]
Great. Happy to hear that. Please close this issue when you can.
