### ISSUE TITLE
https://quiterss.org  Error 521 Web server is down

### ISSUE THREAD

**Issue by cowsay1** [QuiteRSS/quiterss#1527]
website with binaries is down for at least last 2 days, cannot update using scoop

**Comment by martinrotter** [comment]
Maybe anything to do with UK/RU conflict?

**Comment by Katarn** [comment]
This happened 1 or 2 months ago, it seems they forgot to pay for hosting.

**Comment by core-code** [comment]
cc @Funcy-dcm

**Comment by arhohryakov** [comment]
Please, be patient. The hosting has been paid. Admin is notified. Waiting...

**Comment by arhohryakov** [comment]
It is working! http://quiterss.org
