### ISSUE TITLE
Additions ?

### ISSUE THREAD

**Issue by HenryInMD** [QuiteRSS/quiterss#1531]
It would be really helpful if the tray icon listed the number of unread articles.  It would also be _really_ helpful if the unread articles list continued to actually account for unread articles.  On my machine (Win10 Pro), when I open the app, the unread articles are still highlighted--that is they are bolded--but the count of the number goes to zero, seeming to indicate there are no more unread, which is just wrong.

thanks,

**Comment by arhohryakov** [comment]
You can choose this behavior in Options:

![image](https://user-images.githubusercontent.com/4505544/161543594-b440aae1-60a8-4ee4-a85c-cf98d258fea3.png)

**Comment by HenryInMD** [comment]
Can you please provide me a bit more detail on how to do that?  I need to know precisely where in the Options section.  

 

Thanks for the quick response!

 

Henry

 

Follow me on Instagram (  <https://www.instagram.com/henry_s_winokur/>  )… I try to post at least 1 new image every day!

I'm on  <https://www.facebook.com/HenWin>  too!

 <http://www.henrywinokur.com/> www.henrywinokur.com

**Comment by arhohryakov** [comment]
Main Menu -> Tools -> Options.

**Comment by HenryInMD** [comment]
I know how to get to the Options menu.  I don’t know what settings in the options menu to change/modify to get it to behave as you said it would.  

 

Is there any documentation that would explain it and if yes, where can I get it?

 

Thanks, 

 

Henry

 

Follow me on Instagram (  <https://www.instagram.com/henry_s_winokur/>  )… I try to post at least 1 new image every day!

I'm on  <https://www.facebook.com/HenWin>  too!

 <http://www.henrywinokur.com/> www.henrywinokur.com
