### ISSUE TITLE
No launch anymore

### ISSUE THREAD

**Issue by fretere** [QuiteRSS/quiterss#1591]
Hi,
I'm in Manjaro uptodate and Quiterss doesn't launch anymore...

Need a rebuild?

Thanks.

**Comment by Universebenzene** [comment]
Might be an AUR issue or you might need a rebuild yourself. Better bring your error message [here](https://aur.archlinux.org/packages/quiterss) first.

**Comment by fretere** [comment]
Hi, I found the solution on the Manjaro forum: just rebuild qt5-webkit and it works again.
Thanks.
