### ISSUE TITLE
Feature Request - Date format to ISO-like

### ISSUE THREAD

**Issue by 0xRamsi** [QuiteRSS/quiterss#1602]
Can we get a date formatting that is similar to the ISO 8601 format?
So `YYYY-MM-DD`, instad of `DD.MM.YY`. Of course with a space in stead of the 'T' delimiter between date and time (if time is present).

This may be more work that it seems, cause I have not seen any screen for "settings". This might be necessary to implement first, but I personally will be happy edit a config file.

Thanks.

**Comment by vitusson** [comment]
I think "Options -> Feed -> Display -> Display format for date" is what you're looking for

**Comment by 0xRamsi** [comment]
After a bit of searching, I found the options. Somehow I was sure there is none. Thanks!
