### ISSUE TITLE
QuiteRSS site and binaries unavailable

### ISSUE THREAD

**Issue by aliesbelik** [QuiteRSS/quiterss#1604]
Attempt to access QuiteRSS site (https://quiterss.org/) and binary downloads [since mid 04.2024](https://web.archive.org/web/20240000000000*/quiterss.org) redirects to https://quiterss.org/files/ which results in 404.
Even if it was done intentionally seems to be a good point to leave at least last version binaries available somewhere for download, e.g. adding them to the release asset here on Github.
Especially since QuiteRSS is still popular.

Sure, all the files are still accessible from web.archive but it seems to be more reasonable and secure if they are provided by the authors on the resources they control.

I'm raising this issue in сonnection with the possibility to maintain [QuiteRSS manifest](https://github.com/ScoopInstaller/Extras/blob/master/bucket/quiterss.json) for Scoop installer (ScoopInstaller/Extras#13166): either deprecate manifest, or host archived binaries as part of Scoop project, or use QuiteRSS  website/github downloads if they become avialable again (hope this happens).

**Comment by arhohryakov** [comment]
QuiteRSS site (https://quiterss.org/) has been restored and `files` is available too.

**Comment by aliesbelik** [comment]
Thank you for quick reaction and fix.
