### ISSUE TITLE
Jump to begin/end of a feed ? 

### ISSUE THREAD

**Issue by FrankBKK** [QuiteRSS/quiterss#1605]
Is there a way to jump to the begin/end of a feed list ? 

My feeds are usually sorted by published date and some feeds somehow manage to post news with dates far behind the actual date so I need to jump to the end of the list which is rather tedious when you have several hundred entries and no way to jump ....

**Comment by Katarn** [comment]
Home/end keys on keyboard?

**Comment by FrankBKK** [comment]
that did the trick - thank you !
