### ISSUE TITLE
Проблемы с отображением шрифтов

### ISSUE THREAD

**Issue by GoogleCodeExporter** [QuiteRSS/quiterss#180]
```
Если сменить стандартные шрифты в 
настройках, то в окне открытой "новости" у 
них обрезается верх(скриншот 1). Это 
случается со всеми шрифтами, кроме 
стандартного. Будь то Trebuchet MS или тот же Comic 
Sans, Arial, Tahoma, так и с любым сторонним. Еще 
программа почему-то не во всех шрифтах 
видит кириллицу в списке новостей(скриншот 
2), хотя она в них есть, и получается, что она 
пишет английский текст выбранным шрифтом, 
а русский стандартным.
```

Original issue reported on code.google.com by `lol.mash...@gmail.com` on 18 Mar 2013 at 11:20

Attachments:
- [2013-03-18_19-11.png](https://storage.googleapis.com/google-code-attachments/quite-rss/issue-180/comment-0/2013-03-18_19-11.png)
- [2013-03-18_19-17.png](https://storage.googleapis.com/google-code-attachments/quite-rss/issue-180/comment-0/2013-03-18_19-17.png)

**Comment by Funcy-dcm** [comment]
С последней версией проблемы с шрифтами 
остались?
