### ISSUE TITLE
Integration AdBlock

### ISSUE THREAD

**Issue by GoogleCodeExporter** [QuiteRSS/quiterss#189]
```
Думаю будет полезно, да и люди просят.


```

Original issue reported on code.google.com by `egor.shi...@gmail.com` on 19 Mar 2013 at 1:22

**Comment by currentcolor** [comment]
Жаль, что когда принималось решение, какой блокер интегрировать, Ublock Origin не попал во внимание. Он, в отличие от эдблока, не имеет коммерческих "исключений".
В данный момент, частично вижу рекламные блоки (яндекс.директ и т.д.). Не очень здорово читать технические статьи и рекламу шуб сбоку.

Спасибо за QuiteRSS и с наступающими!
