### ISSUE TITLE
Sync with Feedly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [QuiteRSS/quiterss#398]
```
Здравствуйте! Добавьте, пожалуйста, в своё 
приложение поддержку синхронизации с Feedly.

Спасибо.
```

Original issue reported on code.google.com by `flava...@gmail.com` on 11 Oct 2013 at 7:10

**Comment by mwoffenden** [comment]
Are we getting closer?

**Comment by Zottelchen** [comment]
So I will put a bounty on this. Maybe this will go faster then ;)
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=26390401)
Click here to see the bounty.](https://www.bountysource.com/issues/26390401-sync-with-feedly)

**Comment by mwoffenden** [comment]
I'm in.

**Comment by Funcy-dcm** [comment]
#128
