### ISSUE TITLE
memory consumption and harddisk activity

### ISSUE THREAD

**Issue by cyberbeat** [QuiteRSS/quiterss#739]
I have two problems. I use quiterss massivly - with multiple folders and many feeds.

But quiterss needs about 800 mb ram with only one tab open. That seems too much for me.

Another problem: when I refresh a folder of feeds, all things get very slow und unresponsive and my harddisk is very active a long time. Do you make many sqlite inserts without using transactions? I strongly would recommend using transactions for such cases.

**Comment by bearburger** [comment]
To decrease memory usage you can use one of SQLite managers (SQLite Manager extension for Firefox for example) and do VACUUM command on database. Can't say this will save you 700Mb but in my case usage dropped from 450Mb to 320Mb.

The problem with HDD usage is different. If I right understand situation database is missing important indexes so if you have a lot of news (120K in my case) it takes ages to select right set of news. The only one way to fix this is add indexes by yourself or ask developers to work on DB optimization. I've added some to my installation and quite happy with the result.

**Comment by Funcy-dcm** [comment]
cyberbeat, What file size feeds.db?

**Comment by Funcy-dcm** [comment]
bearburger, "Menu - Tools - Clean Up".
VACUUM - "Menu - Tools - Options - Feeds - Clean Up - Enable DB optimization"

**Comment by cyberbeat** [comment]
feeds.db was very big (about 120 mb), VACUUM the news table helped getting the size small again (and I think also the RAM usage).

But that does not help for the disk usage when fetching the feeds. What happens is:

I have some feed folder structure like
-folder
--subfolder
---feed 1
---feed 2
--subfolder 2
--- feed 3
...
and pressing F5 for a refresh of the selected folder "folder" (with a total about 15 feeds) triggers HD activity for about half a minute, where no other action in quiterss is possible. this is quite annoying.

**Comment by Funcy-dcm** [comment]
cyberbeat, send video

**Comment by cyberbeat** [comment]
I don't know, what you could see in a video, except that the progress-bar at the bottom takes about half a minute to fetch the feeds from 0% to 100%.

**Comment by Funcy-dcm** [comment]
Send files: feeds.db & quiterss.ini

**Comment by bearburger** [comment]
@Funcy-dcm thank you for info about optimization feature.

Anyway there is still a lot of queries that doesn't use index and VACUUM can't help with it. 
There is only 2 indexes (at least what I see in my DB that was created in 0.12): `feedId` on `news` table, `xmlUrl+disableUpdate` on `feeds` table.

Let's open `updatefeeds.cpp` and look at some queries. _All_ queries to `news` table and 10 queries to `feeds` table doesn't use indexes. Situation for `mainwindow.cpp` isn't much better and if I right understand issues with performance in this file directly affects main window performance.

In my opinion you can partially fix both issues (memory usage and performance) with #729 feature implementation. Currently there is no point to completely clear deleted news database as for most part of feeds program will load them again and you will need to delete them again. So all deleted news still use disk spaces, still take part in queries (delete marker does nothing when query does full scan). But if you can add feature like "don't load news with date < date of last full clear" that will allow us to remove a lot of rows from database without side effects.

In my case there is 100K deleted news from 120K total. I've tried to remove all deleted news from copy of database. Initial size was 105Mb and after clean 47Mb. Memory consumption dropped from 320 to 290Mb. I can't say this is super cool results but still something. But as I said cleaning doesn't work in my case as after first update about 30K of delete news will return and I'll need to remove them manually again :-(

## 

Егор, после создания индексов отзывчивость интерфейса действительно стала выше. Причём на потреблении памяти это практически никак не сказывается (+-10МБ это не проблема при общем потреблении 300+). Жутко тормозили выборки по папкам, если внутри 15+ фидов и в каждом несколько тысяч сообщений (даже удаленных, ситуацию при выборке без индексов это не меняет) - интерфейс тупо "замораживался" и любые нажатия приводили к окошку "Не отвечает. Завершить или подождать?".

**Comment by cyberbeat** [comment]
After a look to updatefeeds.cpp, I think the indexes are ok, the queries use the id or the feedId for the news table (both indexed).

I think I need to edit the source code to insert some time tracking and perhaps add some sqlite debug output (https://www.sqlite.org/errlog.html).

**Comment by cyberbeat** [comment]
I now started to debug and used some timers to find the problem.

most harddisk + time consuming is the query:

UPDATE feeds SET status='%1' WHERE id=='%2' in method "finishUpdate" in "updatefeeds.cpp"
simply because it is called for every feed in my folder, and there is no transaction around the sum of the queries, so the db has to be locked+unlocked for every query.

I also tested the "in memory db" option, where the problem is gone.

I also tested the pragma synchronize = off, which also solves the problem (0,5% of the time is used).

update: I did not test heavy updates on the news table, which I could try later

**Comment by Funcy-dcm** [comment]
@cyberbeat Thank you for your help in solving the problem. Unfortunately, I could not do better code optimization.

**Comment by cyberbeat** [comment]
perhaps you could provide an ini-option to do pragma synchronize=off? it does not have to be a gui-option, a simple ini-file-option would be ok for me..

**Comment by Funcy-dcm** [comment]
The implementation will be revised in QuiteRSS2
