### ISSUE TITLE
QuiteRSS doesn't start and exits with 0 in the shell

### ISSUE THREAD

**Issue by ghost** [QuiteRSS/quiterss#740]
that's a pretty weird case.

``` bash
23:52  ~ ❯❯ quiterss 
23:52  ~ ❯❯ echo $?
0
```

 I used `strace` to see what could have provoked that.
the trace is here => https://gist.github.com/2d1852999c9eab2622d9
It looks like there is a lot of `"= -1 EAGAIN (Resource temporarily unavailable)"`

I'm running 0.7.15, on Funtoo.

**Comment by Funcy-dcm** [comment]
Need an file debug.log.

**Comment by ghost** [comment]
Apparently it solved itself, I don't understand how or why. But next time it happens, I'll upload debug.log.
