### ISSUE TITLE
Window minimizes to system tray when switching workspace under Xfce

### ISSUE THREAD

**Issue by padsen** [QuiteRSS/quiterss#742]
I'm using 0.17.6 on Xubuntu 15.04 (vivid), Xfce 4.12. When I have the QuiteRSS window open and switch to another workspace, the window has disappeared when I switch back. I have to click the icon in the system tray to get it to reappear. If I uncheck "Move to the system tray when minimizing QuiteRSS" in "Options" -> "System tray", this does not happen, so it seems it considers switching workspaces the same as minimizing the window. I have not tried this under anything except Xfce.

**Comment by Funcy-dcm** [comment]
Unfortunately, I can not repeat this mistake.
