### ISSUE TITLE
Disturbing default anti-privacy "feature"

### ISSUE THREAD

**Issue by fixingshit** [QuiteRSS/quiterss#743]
RSSOwl migrator here. RSSOwl became a nightmare of bugs and annoyances, so I hope QuiteRSS won't be the same!

By default, "Help improve QuiteRSS by sending usage information" is checked in the options. What exactly does this mean? It doesn't say it's anonymous. It makes me extremely worried about what it actually does. Is it sending all my feeds to the developers of QuiteRSS for them to snoop at? What exactly is sent?

**Comment by Funcy-dcm** [comment]
Loading only pages with statistics: https://quiterss.org/runAplication
Code: https://github.com/QuiteRSS/quiterss/blob/master/src/updateappdialog.cpp

**Comment by Funcy-dcm** [comment]
Open access to the statistics: https://www.openstat.com/counter/2284913

**Comment by genodeftest** [comment]
Could you please change this setting so that QuiteRSS asks the user on first startup whether to send this data or not? I find it quite privacy-infringing to do so and it is illegal in some countries for a reason.

**Comment by Funcy-dcm** [comment]
It does not collect information from your computer. It is usual loading of web page.

**Comment by genodeftest** [comment]
I understand that it only loads the file http://quiterss.org/runAplication as src/updateappdialog.cpp#L86 tells me. Still it will provide some data about my computer (IP address, quiteRSS version, probably package version or architecture, …).

**Comment by Funcy-dcm** [comment]
The implementation will be revised in QuiteRSS2
