### ISSUE TITLE
Random old posts appear as new

### ISSUE THREAD

**Issue by fixingshit** [QuiteRSS/quiterss#744]
This VERY annoying bug happened all the time with RSSOwl. In fact, it was what made me switch away from it to QuiteRSS. And now it happens in QuiteRSS too. I'm going nuts over this.

Note: I know for 100% sure that none of these have changed:
- <title>
- <link>
- <guid>
- <category>

Only the "<description>" one changes, but it changes for all the other ones as well, and they don't re-appear. Only (seemingly) random ones appear as new. I don't get this. Why is this happening?

**Comment by Funcy-dcm** [comment]
Send file feeds.db and specify a feed and news
Send screenshots

**Comment by fixingshit** [comment]
?
