### ISSUE TITLE
i cannot switch between folders or another site feeds, 

### ISSUE THREAD

**Issue by thesmartraja** [QuiteRSS/quiterss#749]
there are no side pane to switch between two rss feeds 
![screenshot from 2015-04-29 10 34 58](https://cloud.githubusercontent.com/assets/12164398/7385031/6de32068-ee5b-11e4-9e4e-290ef26caf44.png)

**Comment by Funcy-dcm** [comment]
Ctrl+D

**Comment by thesmartraja** [comment]
Thank you friend
