### ISSUE TITLE
Фильтры новостей не работают с Google Alerts

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#750]
Фильтры (инструменты > фильтры новостей), которые учитывают ключевые слова в новостях (заголовок + описание) лент [Google Alerts](https://www.google.ru/alerts), к сожалению не находят ключевые слова в описании новости, а только в заголовке. Если фильтровать только по описанию, то тоже ничего не находится. 

Поиск в панели списка новостей однако работает как положено - "найти в новостях" находит искомое слово как в заголовке, так и в описании.

С остальными лентами фильтры (инструменты > фильтры новостей) работают безупречно.

Заранее благодарен!

**Comment by Funcy-dcm** [comment]
Какая у вас ОС?

**Comment by sojusnik** [comment]
Ubuntu Gnome 14.10 64-bit.

**Comment by sojusnik** [comment]
К сожалению в новой версии QuiteRSS (0.18.2) проблема до сих пор присутствует - фильтр учитывает слово только в заголовке, но не в описании. Слово написано латиницей.

Могу ли я Вам чем-нибудь помочь при устранении этого бага?

Как можно опять открыть эту тему, так как вопрос видимо еще не решен?

**Comment by Funcy-dcm** [comment]
Необходимы скриншоты и ссылка на ленту (не понял где взять ленту Google Alerts)

**Comment by sojusnik** [comment]
Очень странно, но я только что подписался на RSS ленту недавно созданного оповещения (в Google Alerts) и проверил работу фильтра - вроде все работает...
Пока не закрывайте тему, может докопаюсь до истины...

**Comment by Funcy-dcm** [comment]
Будем надеяться, что баг сам пропадёт )
