### ISSUE TITLE
debian 8 cinnamon: minimize to tray keeps the window in the taskbar window list

### ISSUE THREAD

**Issue by badpenguin** [QuiteRSS/quiterss#753]
when i minimize the icon in the tray area appears as from settings
but the window is keep visible in the bottom bar in the window list
is there a way to hide from the list while minimized in the tray?

**Comment by Funcy-dcm** [comment]
Send quiterss.ini file

**Comment by badpenguin** [comment]
here you are :)

[General]
currentVersionApp=0.17.6
remindAboutVersion=false
NewsTabSplitterState=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x2\0\0\x1\xc7\0\0\x2\x19\x1\0\0\0\x1\x1\0\0\0\x2)
GeometryState=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\0\0\0\0\0\x1e\0\0\a\x7f\0\0\x4\x90\0\0\0\0\0\0\0\x32\0\0\x1\x5\0\0\x2H\0\0\0\0\x2\0)
ToolBarsState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\a\x80\0\0\x3\xfe\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x1e\0T\0o\0o\0l\0\x42\0\x61\0r\0_\0G\0\x65\0n\0\x65\0r\0\x61\0l\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
MainSplitterState="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x2\0\0\x1<\0\0\x6=\0\0\0\0\x1\x1\0\0\0\x1)"
FeedsWidgetVisible=true
FeedsWidgetSplitterState=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x2\0\0\x2'\0\0\x1\xcd\0\0\0\0\x1\x1\0\0\0\x2)
NewsCategoriesTreeVisible=true
categoriesTreeExpanded=true
VersionDB=16

[Settings]
cleanDiskCache=false
showCloseButtonTab=true
updateCheckEnabled=false
statisticsEnabled=true
storeDBMemory=true
timeoutRequest=15
numberRequest=10
numberRepeats=2
userStyleBrowser=
useDiskCache=true
maxDiskCache=50
dirDiskCache=/home/agx/.cache/QuiteRss/QuiteRss
styleSheetNews=/usr/share/quiterss/style/news.css
browserStandardFont=Nimbus Roman No9 L
browserFixedFont=Courier New
browserSerifFont=Nimbus Roman No9 L
browserSansSerifFont=Nimbus Sans L
browserCursiveFont=Comic Sans MS
browserFantasyFont=Impact
browserDefaultFontSize=16
browserFixedFontSize=13
browserMinFontSize=0
browserMinLogFontSize=0
autoUpdatefeedsStartUp=true
showSplashScreen=true
reopenFeedStartup=false
openNewTabNextToActive=false
createLastFeed=false
showTrayIcon=true
startingTray=false
minimizingTray=true
closingTray=false
behaviorIconTray=2
singleClickTray=true
clearStatusNew=true
emptyWorking=true
langFileName=it
feedsFontFamily=FreeSans
feedsFontSize=10
newsFontFamily=Sans
newsFontSize=9
newsTitleFontFamily=Sans
newsTitleFontSize=11
newsTextFontFamily=Arial
newsTextFontSize=12
notificationFontFamily=Arial
notificationFontSize=12
autoUpdatefeeds=true
autoUpdatefeedsTime=60
autoUpdatefeedsInterval=0
openingFeedAction=3
openNewsWebViewOn=true
markNewsReadOn=true
markCurNewsRead=true
markNewsReadTime=0
markPrevNewsRead=false
markReadSwitchingFeed=false
markReadClosingTab=false
markReadMinimize=false
showDescriptionNews=true
formatData=dd. MMM. yyyy
formatTime=hh:mm
alternatingColorsNews=false
changeBehaviorActionNUN=false
simplifiedDateTime=true
notDeleteStarred=false
notDeleteLabeled=false
markIdenticalNewsRead=true
mainNewsFilter=filterNewsAll_
cleanupOnShutdown=true
maxDayClearUp=30
maxNewsClearUp=200
dayClearUpOn=true
newsClearUpOn=true
readClearUp=false
neverUnreadClearUp=true
neverStarClearUp=true
neverLabelClearUp=true
cleanUpDeleted=false
optimizeDB=false
externalBrowserOn=-1
externalBrowser=/usr/bin/iceweasel
javaScriptEnable=true
pluginsEnable=true
maxPagesInCache=3
downloadLocation=
askDownloadLocation=true
defaultZoomPages=100
autoLoadImages=true
soundNewNews=false
soundNotifyPath=/usr/share/quiterss/sound/notification.wav
showNotifyOn=false
positionNotify=3
countShowNewsNotify=10
widthTitleNewsNotify=300
timeShowNewsNotify=10
fullscreenModeNotify=true
onlySelectedFeeds=false
mainToolbarLock=true
mainToolbarShow2=true
feedsToolbarShow2=true
newsToolbarShow=true
browserToolbarShow=true
categoriesPanelShow=true
statusBarShow=true
styleApplication=greenStyle_
showUnreadCount=true
showUndeleteCount=false
showLastUpdated=false
indentationFeedsTree=true
newsLayout=0
browserPosition=1
openLinkInBackground=true
openLinkInBackgroundEmbedded=true
openingLinkTimeout=1000
stayOnTop=false
hideFeedsOpenTab=false
showToggleFeedsTree=true
defaultIconFeeds=false
autocollapseFolder=false
showMenuBar=false
saveCookies=1

[NewsHeader]
state="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x6\x1\0\0\0!\0\0\0\0\0\0\0\x3\0\0\0\b\0\0\0\t\0\0\0\n\0\0\0\v\0\0\0\x4\0\0\0\a\0\0\0\f\0\0\0\r\0\0\0\x5\0\0\0\xe\0\0\0\xf\0\0\0\x6\0\0\0\x10\0\0\0\x11\0\0\0\x2\0\0\0\x1\0\0\0\x12\0\0\0\x13\0\0\0\x14\0\0\0\x15\0\0\0\x16\0\0\0\x17\0\0\0\x18\0\0\0\x19\0\0\0\x1a\0\0\0\x1b\0\0\0\x1c\0\0\0\x1d\0\0\0\x1e\0\0\0\x1f\0\0\0 \0\0\0!\0\0\0\0\0\0\0\x11\0\0\0\x10\0\0\0\x1\0\0\0\x6\0\0\0\n\0\0\0\r\0\0\0\a\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\b\0\0\0\t\0\0\0\v\0\0\0\f\0\0\0\xe\0\0\0\xf\0\0\0\x12\0\0\0\x13\0\0\0\x14\0\0\0\x15\0\0\0\x16\0\0\0\x17\0\0\0\x18\0\0\0\x19\0\0\0\x1a\0\0\0\x1b\0\0\0\x1c\0\0\0\x1d\0\0\0\x1e\0\0\0\x1f\0\0\0 \0\0\0!\x1\xff\xff\xff\x1\0\0\0\x1a\0\0\0 \0\0\0\x64\0\0\0\x1f\0\0\0\x64\0\0\0\x1e\0\0\0\x64\0\0\0\x1d\0\0\0\x64\0\0\0\x1c\0\0\0\x64\0\0\0\x1b\0\0\0\x64\0\0\0\x1a\0\0\0\x64\0\0\0\x19\0\0\0\x64\0\0\0\x18\0\0\0\x64\0\0\0\x17\0\0\0\x64\0\0\0\x16\0\0\0\x64\0\0\0\x15\0\0\0\x64\0\0\0\x14\0\0\0\x64\0\0\0\x13\0\0\0\x64\0\0\0\x12\0\0\0\x64\0\0\0\xf\0\0\0\x64\0\0\0\xe\0\0\0\x64\0\0\0\f\0\0\0\x64\0\0\0\v\0\0\0\x64\0\0\0\t\0\0\0\x64\0\0\0\b\0\0\0\x64\0\0\0\x5\0\0\0\x64\0\0\0\x4\0\0\0\x64\0\0\0\x3\0\0\0\x64\0\0\0\x2\0\0\0\x64\0\0\0\0\0\0\0\x64\0\0\x6=\0\0\0!\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\0\0\0\x16\0\0\0\x81\0\0\0\0\0\0\0!\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x16\0\0\0\x1\0\0\0\x2\0\0\0\x16\0\0\0\x1\0\0\0\x2\0\0\0\x16\0\0\0\x1\0\0\0\x2\0\0\x1\xe4\0\0\0\x1\0\0\0\0\0\0\0^\0\0\0\x1\0\0\0\0\0\0\0^\0\0\0\x1\0\0\0\0\0\0\x3[\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0)"
columns=",17,16,1,6,10,13,7,"
sortBy=6
sortOrder=0

[addFeedWizard]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\x2\xf9\0\0\x1{\0\0\x4\x88\0\0\x2\xb2\0\0\x2\xf9\0\0\x1{\0\0\x4\x88\0\0\x2\xb2\0\0\0\0\0\0)

[Flags]
updatingFeeds=false

[AdBlock]
lastUpdate=@Variant(\0\0\0\x10\0%~7\x5\x19!\x80\x1)
enabled=true
useLimitedEasyList=true
disabledRules=@Invalid()

[options]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\x3\xe0\0\0\x2\x1c\0\0\x6\x9b\0\0\x4K\0\0\x3\xe0\0\0\x2\x1c\0\0\x6\x9b\0\0\x4K\0\0\0\0\0\0)

[Color]
feedsListTextColor=#313739
feedsListBackgroundColor=
newsListTextColor=#313739
newsListBackgroundColor=
newNewsTextColor=#313739
unreadNewsTextColor=#313739
focusedNewsTextColor=#313739
focusedNewsBGColor=
linkColor=#0066CC
titleColor=#0066CC
dateColor=#666666
authorColor=#666666
newsTextColor=#000000
newsTitleBackgroundColor=#FFFFFF
newsBackgroundColor=#FFFFFF
feedWithNewNewsColor=#0000ff
countNewsUnreadColor=#0000ff
focusedFeedTextColor=#313739
focusedFeedBGColor=
feedDisabledUpdateColor=#999999
alternatingRowColors=#efefef

[networkProxy]
type=0
hostName=
port=0
user=
password=

[feedSettings]
currentId=16
filterName=filterFeedsUnread_

[newsSettings]
filterName=filterNewsUnreadStar_

[ClickToFlash]
whitelist=@Invalid()
enabled=true

[Shortcuts]
addFeedAct=Ctrl+N
addFolderAct=Ctrl+Shift+N
deleteFeedAct=
createBackupAct=
exitAct=Ctrl+Q
updateFeedAct=F5
updateAllFeedsAct=Ctrl+F5
openHomeFeedsAct=
showDownloadManagerAct=
showCleanUpWizardAct=
setNewsFiltersAct=
setFilterNewsAct=
optionsAct=F8
deleteNewsAct=Del
deleteAllNewsAct=Ctrl+Del
feedProperties=Ctrl+E
feedKeyUp=Ctrl+Up
feedKeyDownAct=Ctrl+Down
newsKeyUpAct=Left
newsKeyDownAct=Right
newsKeyPageUpAct=
newsKeyPageDownAct=
nextUnreadNewsAct=Space
prevUnreadNewsAct=
nextFolderAct=
prevFolderAct=
importFeedsAct=
exportFeedsAct=
autoLoadImagesToggle=
markAllFeedRead=
markFeedRead=
markNewsRead=
markAllNewsRead=
markStarAct=
collapseAllFolderAct=
expandAllFolderAct=
expandFolderAct=
openDescriptionNewsAct=Return
openInBrowserAct=Ctrl+Space
openInExternalBrowserAct=Ctrl+O
openInNewTabAct=T
openInBackgroundTabAct=Ctrl+T
switchFocusAct=Ctrl+Tab
switchFocusPrevAct=Ctrl+Shift+Tab
visibleFeedsWidgetAct=Ctrl+D
placeToTrayAct=
zoomInAct=Ctrl++
zoomOutAct=Ctrl+-
zoomTo100Act=Ctrl+0
printAct=Ctrl+P
printPreviewAct=Ctrl+Shift+P
savePageAsAct=Ctrl+S
savePageAsDescriptAct=
fullScreenAct=F11
stayOnTopAct=F10
closeTabAct=Ctrl+W
closeOtherTabsAct=
closeAllTabsAct=
nextTabAct=
prevTabAct=
reduceNewsListAct=Alt+Up
increaseNewsListAct=Alt+Down
restoreLastNewsAct=Ctrl+Z
findTextAct=Ctrl+F
copyLinkAct=
backWebPageAct=
forwardWebPageAct=
reloadWebPageAct=
emailShareAct=
evernoteShareAct=
gplusShareAct=
facebookShareAct=
livejournalShareAct=
pocketShareAct=
twitterShareAct=
vkShareAct=
linkedinShareAct=
bloggerShareAct=
printfriendlyShareAct=
settingPageLabelsAct=
showLabelsMenuAct=
labelAction_1=
labelAction_2=
labelAction_3=
labelAction_4=
labelAction_5=
labelAction_6=

**Comment by Funcy-dcm** [comment]
Unfortunately, I have no means of checking on the same operating system as yours.

**Comment by genodeftest** [comment]
This seems like a cinnamon issue to me. Can you check with another application which minimizes to tray? Ideally with another application written in Qt4?
