### ISSUE TITLE
Showing Updated Feed Even When Not Updated

### ISSUE THREAD

**Issue by ghost** [QuiteRSS/quiterss#755]
rss 17.7

When I open RSS some feeds are in blue color as if they have new updates.  They do not. The color is wrong.

thx

**Comment by Funcy-dcm** [comment]
Send screenshots

**Comment by ghost** [comment]
What do you want with a screenshot for this?  The feeds are blue with no 
new articles.

On 5/4/2015 6:43 AM, Shilyaev Egor wrote:

> Send screenshots
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/QuiteRSS/quiterss/issues/755#issuecomment-98673467.

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by Funcy-dcm** [comment]
I have all working. No screenshots or video, I can not do anything.

**Comment by ghost** [comment]
Here it is although I don't know what good it going to do you.

On 5/4/2015 7:58 AM, Shilyaev Egor wrote:

> I have all working. No screenshots or video, I can not do anything.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/QuiteRSS/quiterss/issues/755#issuecomment-98687037.

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com
