### ISSUE TITLE
Core Dump on Manjaro Linux

### ISSUE THREAD

**Issue by nobicycle** [QuiteRSS/quiterss#757]
Hello.
Thanks for the app.
QuietRSS compiles and installs from Arch AUR, but running it produces:
$ quiterss
_IceTransSocketUNIXConnect: Cannot connect to non-local host hp6560
_IceTransSocketUNIXConnect: Cannot connect to non-local host hp6560
Segmentation fault (core dumped)

I attached the zipped dump qrss.core.gz by renaming it qrss.core.gz.png
![qrss core gz](https://cloud.githubusercontent.com/assets/1372447/7507809/43902e3e-f4a8-11e4-8ffe-543b3fc1cc4d.png)
Best wishes

**Comment by genodeftest** [comment]
The file you attached seems broken. Can you please attache a backtrace as described in [Debugging QuiteRSS](https://github.com/QuiteRSS/quiterss/wiki/Debugging-QuiteRSS)

**Comment by nobicycle** [comment]
Please close this issue.
On the latest ARCH (rolling release), QuietRSS compiles fine.
Thank you
