### ISSUE TITLE
[wayland] open link in external browser in background broken

### ISSUE THREAD

**Issue by genodeftest** [QuiteRSS/quiterss#758]
I am using quiterss on Fedora. I have enabled the experimental feature to open links in the external browser in background. It works fine on gnome/X11, thanks for that! It does not work on gnome/wayland.
Is there any details I could provide? Do you consider this a bug in GNOME?

**Comment by Funcy-dcm** [comment]
Unfortunately, this feature is not stable, even within a single operating system. The best solution we have found.
