### ISSUE TITLE
Export particular folder in opml format

### ISSUE THREAD

**Issue by sathishkumarsk1993** [QuiteRSS/quiterss#760]
I export my feeds to opml and store in locally and in the cloud. I have been thinking about a way to export only a particular folder (say, technology-feeds of tech websites) as opml. It will be useful since I could load these into android feed reader(palabre) for more curated content, as opposed to loading entire feeds and then have to delete it. We always can edit the opml file directly. But, wouldn't it be simpler to do it from the software itself? I am using QuiteRss version:0.17.7 (19.04.2015) on Ubuntu 15.04 . Can you suggest a solution?

**Comment by Funcy-dcm** [comment]
Can you show your ideas in the screenshots?

**Comment by dogancelik** [comment]
I really want this. I don't want to export all folders. Maybe just one folder or several folders, separate OPML files into categories.

Here's the first example, one folder selected. Folder right click, Export menu item.
You can select multiple folders, no export folder/feed selection dialog.

![export](https://cloud.githubusercontent.com/assets/486818/15936636/7c2c44e2-2e74-11e6-9700-50e22bebcf53.png)

Here's second example, application main menu item "Export feeds" has a selection dialog for folders.

![export-dialog](https://cloud.githubusercontent.com/assets/486818/15936971/bfc74246-2e75-11e6-8e11-c1d961ec4a7f.png)

**Comment by sathishkumarsk1993** [comment]
Thanks :-)

**Comment by dogancelik** [comment]
@Funcy-dcm did this get implemented or closed for inactivity?

**Comment by Funcy-dcm** [comment]
Unfortunately, we no longer add new features, because we started developing QuiteRSS2.
Apparently I closed casually without comment
