### ISSUE TITLE
Need columns to auto-size to width of content

### ISSUE THREAD

**Issue by mwoffenden** [QuiteRSS/quiterss#761]
Columns (particularly date columns) constantly need re-sizing.  Need an option to auto-size the column width to the content, or set minimum number of pixels for each column.

The issue is shown and highlighted below.

![2015-05-18 16_15_13-reuters_ top news - quiterss](https://cloud.githubusercontent.com/assets/6774346/7689391/d9f59038-fd79-11e4-8fb4-1e15c45f99b7.png)

**Comment by Funcy-dcm** [comment]
Sometimes the size of the columns are reset?

**Comment by mwoffenden** [comment]
The problem is that the columns don't size properly by themselves -- so that the data is hidden.  As shown in the image.

**Comment by vzjrz** [comment]
It would be great if the columns would remember their size but they don't. They keep resetting on every restart at least that's my experience.

**Comment by mwoffenden** [comment]
Remembering the size would be nice.  But the best solution is that the program should auto resize columns to their contents.  This simple fix would prevent the situation shown in my image above, where dates are not shown properly.

**Comment by Funcy-dcm** [comment]
Unfortunately, I still could not find a good solution
