### ISSUE TITLE
best practice: please write commit messages in English

### ISSUE THREAD

**Issue by onlyjob** [QuiteRSS/quiterss#762]
Commit messages in Russian make it difficult to understand changes.
Please always compose commit messages in English.

**Comment by Funcy-dcm** [comment]
Unfortunately, I do not have time for it. I'd rather spend time on programming.

**Comment by onlyjob** [comment]
Go ahead if you're not looking forward to attract contributors... :(

Besides, it is not a good practice to close a bug simply because it doesn't feel easy to fix or because you disagree -- your denial will not make problem go away...
