### ISSUE TITLE
QT5 upgrade issue (no feeds)

### ISSUE THREAD

**Issue by onlyjob** [QuiteRSS/quiterss#764]
I've re-built QuiteRSS 0.17.7 with QT5 but it did not pick up my feeds database made by QT4 build. QuiteRSS/QT5 started with sample feed and no history at all...

Please advise how to upgrade. Thanks.

**Comment by Funcy-dcm** [comment]
Unfortunately, qt5 will not operate. Incorrect operation of some components.
Fourth row: https://github.com/QuiteRSS/quiterss/blob/master/INSTALL

**Comment by onlyjob** [comment]
So QT5 is not supported (yet)?

Is it on the readmap?

 FYI: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784520

**Comment by Funcy-dcm** [comment]
There is a problem with the display of the tree feeds.

**Comment by onlyjob** [comment]
Yes, I've noticed that too. Please remember that soon webkit/QT4 will become unsupported. Ideally it would be nice to have a ticket to track QT5 transition progress.
