### ISSUE TITLE
feeds toolbar won't appear

### ISSUE THREAD

**Issue by smcoll** [QuiteRSS/quiterss#766]
When QuiteRSS opened today, the Feeds Toolbar wasn't visible, even though it was selected under View > Show/Hide.  Toggling that doesn't change anything.

Version 0.17.7 (19.04.2015)
Revision git-3522-1d598bb

Ubuntu 14.04

**Comment by Funcy-dcm** [comment]
Make screenshots.

**Comment by smcoll** [comment]
Layout is the same no matter whether "Feeds Toolbar" is enabled or not.

![screenshot from 2015-05-21 10 32 45](https://cloud.githubusercontent.com/assets/321438/7752430/01a617ce-ffa5-11e4-9163-f67e88b61b34.png)

**Comment by Funcy-dcm** [comment]
On the left there is a gray band in a few pixels with an arrow in the middle (CTRL+D).

**Comment by smcoll** [comment]
OK, thanks.  Maybe toggling show/hide on that toolbar should auto-expand the panel if collapsed?  i don't know if i would have ever noticed the arrow.
