### ISSUE TITLE
Mark item read as you scroll over them in newspaper mode

### ISSUE THREAD

**Issue by rgamici** [QuiteRSS/quiterss#769]
I was using "The Old Reader" and recently migrated to QuiteRSS. The newspaper mode is very impressive, and in my opinion much better than selecting every item to read. However, in newspaper mode the news aren't marked as read.
Is it possible to implement an option to mark an item as read as you scroll through them in newspaper mode?

**Comment by Funcy-dcm** [comment]
We have planned to implement this functionality.

**Comment by rgamici** [comment]
Is there a place that I can check what are you planning, so I don't ask for something that is already planned?

**Comment by Funcy-dcm** [comment]
https://quiterss.org/ru/forums/predlozheniya/newspaper-view-otmechat-prochtennymi-prokruchennye-vverh-soobshcheniya

**Comment by Funcy-dcm** [comment]
Will be implemented in QuiteRSS2
