### ISSUE TITLE
Limit image/objects size

### ISSUE THREAD

**Issue by rgamici** [QuiteRSS/quiterss#770]
Some feeds don't constrain the image size, it's probably done in the original website frames. Because of that, QuiteRSS shows those images in original size, sometimes its width is much bigger than the panel and it doesn't fit on the screen.
Is it possible (or create an option) to limit the images width to the panel width or another user defined value?

**Comment by dogancelik** [comment]
I noticed this too, I think there should be an option for this.

**Comment by Funcy-dcm** [comment]
Unfortunately, I can not find a solution to this problem.

**Comment by dogancelik** [comment]
I'm away from PC so don't know but if QuiteRSS has custom CSS feature then
one can set a `max-width: 500px` on img tags.

**Comment by Funcy-dcm** [comment]
Links feed and news

**Comment by rgamici** [comment]
Thank you for your replies.
As @dogancelik said, there's a custom CSS editor, I edited the code and it worked. I had to add "height: auto;" to keep the scale.
The default style is missing "height: auto;", and then it doesn't keep the proportion, only reduces the width. I think that was the real reason some images looked strange.

**Comment by Funcy-dcm** [comment]
fixed 0fe3f9a660dbd7b45e9791fc709a95ed80ad2f8b
