### ISSUE TITLE
Problems on Fedora 22

### ISSUE THREAD

**Issue by Replayattack** [QuiteRSS/quiterss#774]
It freezes, interface icons not loading, to close the application you have to kill the process in Fedora 22 (GNOME 3.16); in Fedora 22 (KDE) operating normally.

**Comment by Replayattack** [comment]
![captura de pantalla de 2015-06-11 22-17-06](https://cloud.githubusercontent.com/assets/6188052/8149671/7bfd1f8c-1291-11e5-9b32-beae1c5a1ab2.png)

**Comment by genodeftest** [comment]
@Enawa Which version do you use? I am using 0.17.6 (from repositories) and it works fine under GNOME (both X and Wayland).

Are you using the repository version too? If yes, can you please provide a backtrace? To do that, please follow the steps I described in [Debugging QuiteRSS](https://github.com/QuiteRSS/quiterss/wiki/Debugging-QuiteRSS).
