### ISSUE TITLE
Координаты списка "меню" в многомониторной конфигурации

### ISSUE THREAD

**Issue by konarev** [QuiteRSS/quiterss#776]
Linux 4.0.5-1 XFCE 4.12.0-1 двухмониторная конфигурация. 
Левый (основной) монитор расположен горизонтально, правый-вертикально. QuiteRSS распахнут на правом. При нажатии кнопки "Меню", оно появляется не под кнопкой, а на уровне правого верхнего угла рабочей области левого (основного) монитора.
![_2015-06-10_14-14-17](https://cloud.githubusercontent.com/assets/10911212/8081526/3c848608-0f7e-11e5-997c-1ba62d6f44c1.jpg)

**Comment by Funcy-dcm** [comment]
К сожалению, Linux с XFCE у меня нет, проверить не могу
