### ISSUE TITLE
very slow news delete

### ISSUE THREAD

**Issue by omega3** [QuiteRSS/quiterss#777]
I have one feed with over 4000 news (over 87500 news in base). The old news from this feed dated December 2014 are deleted very quickly while for newer dates like from yesterday it takes a few seconds to be deleted (moved to deleted folder).
version 0.17.7 (19.04.2015) revision git-3522-1d598bb  on Linux Kubuntu 14.04

**Comment by genodeftest** [comment]
Do you have the automatic database cleanup enabled? Check under `Tools → Options → Feeds → Clean Up`. You should especially enable DB optimization.
If that doesn't help try keeping the whole database in RAM, see `Tools → Options → General → Store a DB in memory`.
If that still doesn't help your database might be too big and/or your harddisk too slow. How big is it? Check in `~/.local/share/data/QuiteRSS/QuiteRSS`. If it is some hundred MB, you might have to keep less feeds or buy a faster disk.
_EDIT_: Or maybe QuiteRSS does slow SQL queries. See #739 for details.
