### ISSUE TITLE
Latency Update

### ISSUE THREAD

**Issue by ghost** [QuiteRSS/quiterss#779]
Here is a sample of 10.  I cannot tell you what each hop is doing.  I do notice that reloading all is slow if I watch the progress bar.  In fact it is slow if only reloading 1 feed.

![quietrss latency-1](https://cloud.githubusercontent.com/assets/11735715/8184013/00614356-140a-11e5-8034-af61be7ccaca.png)

**Comment by ghost** [comment]
I did not realize you were in France, so 145ms is not bad.

**Comment by Funcy-dcm** [comment]
This is normal ;)
