### ISSUE TITLE
News title is truncated by _ (underscore)

### ISSUE THREAD

**Issue by somrandus** [QuiteRSS/quiterss#780]
When a news title have an _ (underscore), the remaining title following it is truncated. In my case, I have a news title of `千秋楽、ありがとう(>_<) 宮本茉凜` but it is truncated to `千秋楽、ありがとう(>_`. This can be observed in both the title in the news list and the title in the news header. debug.log doesn't show anything that seems related to this.

How to reproduce:
1. Add feed from http://feedblog.ameba.jp/rss/ameblo/idolrenaissance/rss20.xml (the news item that triggers the bug may be gone in a few days, the actual article where you can see the correct title is at http://ameblo.jp/idolrenaissance/entry-12040140491.html)
2. Observe one of the news title is `千秋楽、ありがとう(>_` whereas the correct title is `千秋楽、ありがとう(>_<) 宮本茉凜`

Screenshot:
![2015-06-18_054937_cr](https://cloud.githubusercontent.com/assets/4956956/8219947/77aa305e-1580-11e5-8a51-2408b153e8f5.png)

Additional info:
Opera 12's feed reader displays the title correctly.

Version: 0.17.7.3522
OS: Windows Vista SP2

**Comment by Funcy-dcm** [comment]
Try version 0.18.6
