### ISSUE TITLE
quiterss should not ship copies of 3rd party software

### ISSUE THREAD

**Issue by genodeftest** [QuiteRSS/quiterss#781]
For different reasons (updateability, especially security updates) and reducing package size, QuiteRSS should not ship 3rd party software like qftp, qtsingleapplication, sqlite and sqlitex.

**Comment by Nikoli** [comment]
When possible only system libs are used, 3rdparty dir is only for os2|win32|mac, look at https://github.com/QuiteRSS/quiterss/blob/master/3rdparty/sqlite.pri and https://github.com/QuiteRSS/quiterss/blob/master/QuiteRSS.pro

qftp is still not packaged for many linux distros, but we can add SYSTEMQFTP build option if your distro has it and you are willing to verify correct build.
