### ISSUE TITLE
quiterss has stopped working

### ISSUE THREAD

**Issue by ghost** [QuiteRSS/quiterss#784]
Faulting application name: QuiteRSS.exe, version: 0.17.7.3522, time stamp: 0x5533dfdc
Faulting module name: QtNetwork4.dll, version: 4.8.5.0, time stamp: 0x51cc9e04
Exception code: 0xc0000005
Fault offset: 0x0003908b
Faulting process id: 0x548
Faulting application start time: 0x01d0ae758831b641
Faulting application path: C:\Program Files (x86)\QuiteRSS\QuiteRSS.exe
Faulting module path: C:\Program Files (x86)\QuiteRSS\QtNetwork4.dll
Report Id: 234bf862-1a6d-11e5-be42-8bc6dc8e7c28

**Comment by Funcy-dcm** [comment]
Try version 0.18.6
