### ISSUE TITLE
Freeze when importing opml file

### ISSUE THREAD

**Issue by badosu** [QuiteRSS/quiterss#785]
I am using a compiled version of the master branch (166342454034edd824f1831933c5dccc5256f6b8) on Arch Linux x86-64.

QuiteRSS freezes just after importing an OPML file, it shows the imported entries but hangs after starting the update task. See a screenshot of the frozen state:

![2015-06-29-123839_950x526_scrot](https://cloud.githubusercontent.com/assets/347552/8411978/3fb032bc-1e5d-11e5-9246-351cf91468ef.png)

This is the minimal opml file that reproduces the issue on my system (news.opml), this was exported via [newsbeuter](http://www.newsbeuter.org/):

``` xml
<?xml version="1.0"?>
<opml version="1.0">
  <head>
    <title>newsbeuter - Exported Feeds</title>
  </head>
  <body>
    <outline type="rss" xmlUrl="http://abstrusegoose.com/feed.xml" htmlUrl="http://abstrusegoose.com" title="Abstruse Goose"/>
  </body>
</opml>
```

**Comment by Funcy-dcm** [comment]
I have everything working well. Try with the latest commit.
