### ISSUE TITLE
[rfe] provide an option to make quiterss never load any content from the internet

### ISSUE THREAD

**Issue by genodeftest** [QuiteRSS/quiterss#786]
This is a request for enhancement (rfe).
I care for privacy. Because of that I don't like websites to know when and how I read their news feeds. To achieve this I want the internal browser of quiterss to never connect to the internet.

Currently in quiterss preferences (Menu: Tools → Options) you can select these options:
- Browser → Privacy: control whether to save local data
- Browser → Click to Flash: control whether to use click-to-flash
- Browser → General, section "Content":
  - whether to load images
  - whether to enable JavaScript
  - whether to enable plugins

Even with all those options set to maximum privacy quiterss keeps loading some content from the websites such as iframes. I want the internal browser to behave like it were offline – it must not make any internet connections at all.

There are some basic ideas on the web to create a QNetworkAccessManager or setting a proxy for a specific component. See https://forum.qt.io/topic/15382/solved-can-we-set-specific-network-proxy-for-qwebview and https://doc.qt.io/qt-5/qnetworkaccessmanager.html for details. It seems to be harder with Qt5. Once QuiteRSS is migrated to Qt5 I'll take a look at this.

**Comment by Funcy-dcm** [comment]
I understand you, I will try to implement.

**Comment by genodeftest** [comment]
There is a simple solution to this rfe:
1. enable adblocker
2. add a new filter with this text: `*`
done. Running `strace -e connect -f -s 10000 quiterss` shows there are no more connections to the network.

There could be an easier interface to do so, but it works.
