### ISSUE TITLE
Add a way to save database manually

### ISSUE THREAD

**Issue by imconcerned** [QuiteRSS/quiterss#787]
I've had several cases where I just got done starring a bunch of youtube videos (I have my subscription feeds in QuiteRSS so I can star them and add them to a batch list to download them using youtube-dl) where it crashes, and I lost all my stars. Could there be a way to manually save the database so I don't lose everything? The crashes wouldn't be a problem if I could do this. Thanks

**Comment by Funcy-dcm** [comment]
"Menu - Create backup"
