### ISSUE TITLE
Wrong path in NetworkManager::addLocalCertificate

### ISSUE THREAD

**Issue by genodeftest** [QuiteRSS/quiterss#788]
I am using QuiteRSS 0.17.7 from fedora packages.

QuiteRSS keeps asking for the same certificate over and over again. A look into debuglog shows that 
`NetworkManager::addLocalCertificate` tries to create a file `/home/username/(1).local/share/data/QuiteRss/QuiteRss/certificates/crt`:

```
WARNING: NetworkManager::addLocalCertificate cannot write to file:  "/home/username/(1).local/share/data/QuiteRss/QuiteRss/certificates/crt" 
```

**Comment by Funcy-dcm** [comment]
Try version 0.18.6
