### ISSUE TITLE
"SSL handshake failed (6)" for multiple servers with no obvious reason

### ISSUE THREAD

**Issue by genodeftest** [QuiteRSS/quiterss#789]
Some of my feeds don't get updated in QuiteRSS 0.17.7 (fedora package). The warning looks like this: `WARNING: "Request failed: result = -1, error - SSL handshake failed (6), url - https://www.lobbycontrol.de/feed/"`. This issue has been existing for quite some time, it was not introduced in 0.17.7. I am not sure whether it is an issue within quiterss code or somewhere else.

This is a list of affected sites:
https://www.lobbycontrol.de/feed/
https://www.freitag.de/RSS
https://fsfe.org/news/news.en.rss

According to the [SSLLabs server test](https://www.ssllabs.com/ssltest/) the certificates are valid, configuration is acceptable (but not good) and it should work in most browsers (36 on their list, except IE6 on Windows XP).

**Comment by Funcy-dcm** [comment]
Send screenshots: "Menu - Feeds - Properties - Status"

**Comment by genodeftest** [comment]
For all three (Lobbycontrol, Freitag, FSFE News):

Status: SSL handshake failed (6)
Created: [some months ago when I started using QuiteRSS]
Last update: [none]
News count: 0 (0 new, 0 unread)
Description: [empty]

**Comment by genodeftest** [comment]
Both Konqueror and QupZilla fail to connect to these sites via https. Epiphany (Gnome WebKit browser) and firefox can connect to these sites. Looks like an issue in the Qt stack to me. Konqueror also tells me `Additional Information: fsfe.org: SSL negotiation failed`. Some other https connections work fine.

**Comment by genodeftest** [comment]
Ok, sorry, my fault.
I set the system-wide crypto policy (see [1] and [2]) to "FUTURE" which disallows SHA1 and some other weak configurations.

[1] https://fedoraproject.org/wiki/Changes/CryptoPolicy
[2] https://github.com/nmav/fedora-crypto-policies
