### ISSUE TITLE
It does not work to remove the news

### ISSUE THREAD

**Issue by Helgion** [QuiteRSS/quiterss#790]
It does not work to remove the news by date and number when you turn off program

**Comment by Funcy-dcm** [comment]
I do not understand. Tell us about your problem in detail.

**Comment by Helgion** [comment]
К вам можно обращаться по-русски?

To you you can access in Russian?

**Comment by Funcy-dcm** [comment]
Лучше по-русский =)

**Comment by Helgion** [comment]
Я настроил программу на удаление новостей:
![001](https://cloud.githubusercontent.com/assets/13301957/8654807/74edc97e-2995-11e5-8a02-b4e8e3b48a42.jpg)
После этого выключаю программу, она сохраняет базу и все. При следующем включении программы количество новостей остается тем же. Хотя часть новостей имеет возраст более 30 дней. Количество новостей в некоторых лентах превышает 200 штук.
Произвожу принудительную очистку:
![002](https://cloud.githubusercontent.com/assets/13301957/8654810/7de5a006-2995-11e5-9445-dab7e71876f9.jpg)
Но никаких просроченных новостей не удаляется…
![003](https://cloud.githubusercontent.com/assets/13301957/8654819/8b7a2e44-2995-11e5-9599-c47cccd5f3fd.jpg)
Подскажите, что делать!

**Comment by Helgion** [comment]
похоже ответа не дождешься...

**Comment by online** [comment]
@Helgion, здравствуйте! Попробуйте установить галочку здесь:

![14 07 2015_20h42m40s](https://cloud.githubusercontent.com/assets/722881/8680281/f9aed800-2a68-11e5-8ee4-1b30db671482.png)

**Comment by Helgion** [comment]
После выключения и последующего включения были удалены все прочитанные новости вне зависимости от возраста новости в днях и максимального количества новостей... вторая и третья строчка на вашем скрине у меня не работают...

**Comment by Funcy-dcm** [comment]
Пока нет времени, т.к. был выход релиза, чуть позже попытаюсь разобраться.

**Comment by Funcy-dcm** [comment]
Ваша проблема в старой версии (0.17.7) тоже проявлялась? 
Необходимы файлы feeds.db и quiterss.ini, упакуйте и пришлите мне.

**Comment by Helgion** [comment]
Здравствуйте!

Да в 0.17.7тоже была такая проблема.

**Comment by Helgion** [comment]
Уважаемая техподдержка, не знаю что произошло. Программу не переустанавливал, но вчера одна из многих лент набрала более 200 новостей и с утра, запустив комп, произошло чудо! Превышающие по количеству новости были удалены!!!
