### ISSUE TITLE
[0.18.1][Win 7 64] Crash on button "Mark Read"

### ISSUE THREAD

**Issue by Manimap** [QuiteRSS/quiterss#791]
Hi,

As I said in the forums, there is a problem with "mark read" button and labels. Here is a paste of what I wrote:

I found the cause of my crashes: Simply select a few news, label them anything you want (example "later"), then go to the label and "Mark Read" all of them. Guaranteed crash, at least for me.

Later:

I reproduced the crash with a fresh portable 0.18.1 without any configuration and 1 imported rss.

You have to use the button "Mark Read" on a label to crash QuiteRSS. Right Click does work well.

**Comment by Funcy-dcm** [comment]
Try test portable version: https://yadi.sk/d/-mL1zh4gMHXwt

**Comment by Manimap** [comment]
No crash with the version you provided (it's not the same as the one in the website), but the button doesn't work anymore on labels.

**Comment by Funcy-dcm** [comment]
Test portable version: https://yadi.sk/d/-mL1zh4gMHXwt

**Comment by Manimap** [comment]
Your version (3622) didn't solve the issue unfortunately.
Here is what I have done:
- I downloaded portable build 3622
- I extracted and launched it
- I added added a random rss feed (google news rss feed)
- I selected a few news that I put in important label
- I selected the label
- I clicked on the "mark read" button

-> no result at all.

Here is a screenshot:
http://imgur.com/NbF2bFv

**Comment by Funcy-dcm** [comment]
This button is for feeds tree, not for the categories - "**Mark Feed Read**".
Use the context menu.
