### ISSUE TITLE
Qt4 and Qt5 compilations uses different data dirs.

### ISSUE THREAD

**Issue by slawkis** [QuiteRSS/quiterss#792]
~/.local/share/QuiteRss/QuiteRss for Qt5
~/.local/share/data/QuiteRss/QuiteRss for Qt4

Maybe quiterss should check both locations at start - and ask about import if needed?

**Comment by genodeftest** [comment]
See the discussion on https://forum.qt.io/topic/28658/differences-qdesktopservices-vs-qstandardpaths

**Comment by genodeftest** [comment]
Fedora downstream bug report containing a patch: https://bugzilla.redhat.com/show_bug.cgi?id=1485714
