### ISSUE TITLE
Update check does weird things

### ISSUE THREAD

**Issue by genodeftest** [QuiteRSS/quiterss#793]
It looks like the update check is broken:
![quiterss-updater](https://cloud.githubusercontent.com/assets/934401/8669400/925a02a0-2a14-11e5-9192-3a2291b6f4fe.png)
This is a screenshot from today which should display versions 0.18.1 and 0.18.2 too. QuiteRSS should not tell that 0.17.7 is the latest version since 0.18.x is.

I am using quiterss 0.17.7 on a fedora 22 x86_64 installation with the package from https://apps.fedoraproject.org/packages/quiterss

**Comment by Funcy-dcm** [comment]
This is done deliberately - a library for Windows compatible.
Verify upgrade is now at a new address.

**Comment by genodeftest** [comment]
Still the same. 0.17.7 will never update to 0.18 and thus not to any newer release.

**Comment by Funcy-dcm** [comment]
Check now that everything should be fine.

**Comment by genodeftest** [comment]
Yes, thanks!
