### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by ghost** [QuiteRSS/quiterss#794]
Windows 7 64bit  qrss 18.2

Faulting application name: QuiteRSS.exe, version: 0.18.2.3623, time stamp: 0x02972d50
Faulting module name: Qt5WebKit.dll, version: 5.4.2.0, time stamp: 0x6537746e
Exception code: 0xc0000005
Fault offset: 0x01350370
Faulting process id: 0x980
Faulting application start time: 0x01d0beb7043f8900
Faulting application path: C:\Program Files (x86)\QuiteRSS\QuiteRSS.exe
Faulting module path: C:\Program Files (x86)\QuiteRSS\Qt5WebKit.dll
Report Id: c1f64540-2ac8-11e5-9f6e-e89a8fbc7af4

**Comment by Funcy-dcm** [comment]
What actions are you committed?

**Comment by ghost** [comment]
do not know

On 7/15/2015 12:35 PM, Shilyaev Egor wrote:

> What actions are you committed?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/QuiteRSS/quiterss/issues/794#issuecomment-121671419.

---

This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Funcy-dcm** [comment]
This WebKit error
