### ISSUE TITLE
Still No Automatic Cleanup

### ISSUE THREAD

**Issue by ghost** [QuiteRSS/quiterss#795]

**Comment by genodeftest** [comment]
Does using Tools → Options → Feeds → Clean Up not work for you?
**EDIT:** Ok, it doesn't. Feeds database is increasing on every update. Forget my question.

**Comment by ghost** [comment]
Yes it does but I get so many updates I have to do it multiple times a 
day.  lt would be nice to have an option to cleanup on minimize or 
cleanup every 2,3,4, ... hours.  Minimize would be the best I think.

I have been asking for some kind of option like this for over a year and 
it never makes the list.  I am quite sure many other people are tired of 
clicking tools option cleanup and then going thru the screens to make 
that happen.

thx

On 7/16/2015 3:13 PM, Christian Stadelmann wrote:

> Does using Tools → Options → Feeds → Clean Up not work for you?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/QuiteRSS/quiterss/issues/795#issuecomment-122054405.

---

This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Funcy-dcm** [comment]
There is manual cleaning and cleaning with minimization

**Comment by mailinglists35** [comment]
what is cleaning with minimization?

since I keep the laptop open 24/7 I need periodic cleanup, in an automated way.
is there any way you could rethink the cleanup logic?

thanks.
