### ISSUE TITLE
RSS entries are considered new if title/date updated

### ISSUE THREAD

**Issue by Voker57** [QuiteRSS/quiterss#797]
Proper behaviour would be to update existing items' content if they have guid (with having an option of not marking them new)

**Comment by genodeftest** [comment]
Using the guid might be problematic since some feeds don't provide them.

**Comment by Voker57** [comment]
That's why I said "if they have guid"

**Comment by Funcy-dcm** [comment]
The implementation will be revised in QuiteRSS2
