### ISSUE TITLE
Duplicate news that don`t have title in each update

### ISSUE THREAD

**Issue by GDXN** [QuiteRSS/quiterss#798]
I found that if a news don't have a title, during update is considered it a new news even if it's already present and adds it as new resulting in multiple duplicates of the same news.
it happened to me in: http://feeds.feedburner.com/WtfJapanSeriously?format=xml

**Comment by Voker57** [comment]
Probably related to #797

**Comment by kingjon3377** [comment]
I'm seeing this with, among others, http://michaelvelthuizen.blogspot.com/feeds/posts/default?alt=rss

**Comment by Funcy-dcm** [comment]
fix: 5fbff73e70f6ac9dcd7d267337e63c1cdb985401
