### ISSUE TITLE
Can't watch youtube videos at full screen

### ISSUE THREAD

**Issue by BostAxola** [QuiteRSS/quiterss#802]
Since I installed new version, I can't watch youtube videos at full screen.

![captura de pantalla 2015-07-25 13 04 09](https://cloud.githubusercontent.com/assets/8408600/8889145/d290e3b8-32cd-11e5-8235-6ad87374a7fa.png)

**Comment by BostAxola** [comment]
Sorry for the crappy post, I did it on a hurry. 

The problem is:
![sin titulo](https://cloud.githubusercontent.com/assets/8408600/9423440/e518bd6a-48c3-11e5-8114-d6d050b8567b.png)

Searching, I found out it's a Qt 5 problem: https://github.com/QupZilla/qupzilla/issues/1127 & https://bugreports.qt.io/browse/QTBUG-43625

I did some html5 test and the results were a little bit confusing:
- http://www.jwplayer.com/html5/fullscreen/ Claimed it was supported, thought I couldn't wtach the video at fullscreen.
  ![captura](https://cloud.githubusercontent.com/assets/8408600/9423472/370b9cfe-48c5-11e5-8e73-3947a3a884ce.PNG)
- [Html5Test Report](html5te.st/de3850296dd1f00a)
- On http://www.quirksmode.org/html5/tests/video.html
  - **H.264/X.264** fullscreem worked, but when QuiteRSS crashed when trying to exit fullscreen.
  - **WebM** fullscreem worked.
  - **Ogg/Theora** fullscreem worked, but when QuiteRSS crashed when trying to exit fullscreen.

![captura](https://cloud.githubusercontent.com/assets/8408600/9423496/a0ea03c6-48c6-11e5-8164-0c113261a59c.PNG)

**Comment by Funcy-dcm** [comment]
This WebKit error
