### ISSUE TITLE
[rfe] try to avoid displaying horizontal scrollbars

### ISSUE THREAD

**Issue by genodeftest** [QuiteRSS/quiterss#804]
Currently some news items (e.g. [1] from [2], for future reference I saved the file into a Gist [3]) are displayed in a way that there is a horizontal scrollbar visible. See this screenshot:
![quiterss-horizontal-scroll](https://cloud.githubusercontent.com/assets/934401/8894949/07e5de1e-33c9-11e5-9c02-553aaf520caa.png)
It would be nice to refine the content in a way that I don't have to scroll horizontally to read the text, just as it is on the original website [1].

[1] https://ttboj.wordpress.com/2015/07/23/git-archive-with-submodules-and-tar-magic/
[2] https://ttboj.wordpress.com/feed/
[3] https://gist.github.com/genodeftest/a5800c1393b1cf7cc799

**Comment by Funcy-dcm** [comment]
The data come in this form.

**Comment by dufferzafar** [comment]
Is it possible (via CSS somehow?) to fix the width of the container to be something like 600px, so that the horizontal scrollbar isn't activated?

I would want the text to reflow like it does on a mobile browser.
