### ISSUE TITLE
tray popup - after update to version 18 very small icons

### ISSUE THREAD

**Issue by Jaki143** [QuiteRSS/quiterss#806]
In the versions up to 17 the icons of the tray popup, especially the ones for next/previous page and mark all as read had a nice size of - 32? And the news' rows were had a decent space between them. Now with the update to version 18 the icons seem to be only 16x16 and the rows are so narrow that both the icons and the news are hard to click (for me). 

I am using QuiteRSS in KDE SC 4.14 and the size of the "small icons" which ist the minimum icon size to use, is set to 32. Maybe in the former versions QuiteRSS did follow those rules and doesn't anymore now or it is a coincidence that you shrunk the icons - but please can you add an option to make the tray popup icons bigger again? At least the navigation/mark all as read buttons? As it is now it is no fun to use for people without good eyesight and/or with a slight hand coordination problem.

**Comment by Funcy-dcm** [comment]
Send screenshots

**Comment by Jaki143** [comment]
![quiterss-tiny-buttons-in-tray-popup](https://cloud.githubusercontent.com/assets/13529836/9215417/a89e3a70-40aa-11e5-8ec1-28808f20cbed.jpg)

Alas I don't have a screenshot of some version before 18. I can only show the quiterss popup with the small icons compared to the minimum icon size I use (Linux, KDE) but before 18 the space between the text rows were a little wider so the entries were better to click. And the 3 icons at the right side below the feed, the arrows and the checkmark, were bigger and therefore much better to click.

**Comment by Jaki143** [comment]
Wrong image... 
![quiterss18-popup-icons](https://cloud.githubusercontent.com/assets/13529836/9215584/cba3991e-40ac-11e5-896a-043269dd86ba.jpg)

**Comment by Funcy-dcm** [comment]
Will be implemented in QuiteRSS2
