### ISSUE TITLE
Popup showing the oldest unread message not the newest

### ISSUE THREAD

**Issue by h333n** [QuiteRSS/quiterss#807]
I have set the number of shown messages in the popup to 2 (which actually shows exactly 1, but thats another bug that doesn't bother me).
Everytime the newsfeed provides a new item, I expect this new item to be shown in the popup, no matter if the item before was noticed by me or not. Instead after some time an old post is shown. If I never interact with the popup or QuiteRSS, it remains always the same old post. As far as I was able to analyze it, it seems to be the oldest post, that I did not yet see in the QuiteRSS window.
This behaviour was observed in Version QuiteRSS 0.17.0 and is still observed in QuiteRSS-0.18.2

**Comment by Funcy-dcm** [comment]
Try version 0.18.6
