### ISSUE TITLE
Unescaped HTML in feed titles causes entries which duplicate repeatedly, other issues.

### ISSUE THREAD

**Issue by Billiam** [QuiteRSS/quiterss#809]
If an rss item's title field contains HTML like the following, even if wrapped in a CDATA, the entry will show an empty title, and will repeat in the news feed (and appears to duplicate again whenever the feed is refreshed). Duplicated entries will be marked as new, and deleted entries will reappear when the feed is refreshed.

If the field is htmlencoded instead, it will be displayed correctly.

``` xml
<item>
    <title><![CDATA[<3]]></title>
    <author>...</author>
    <link>https://somelink</link>
    <guid isPermaLink="false">9442101f4e29f39795a00c09fd38fbf3d99b6e249bc8d41acb7bcfc1f07c1423</guid>
    <pubDate>Thu, 30 Jul 2015 12:51:58 -0500</pubDate>
</item>
```

**Comment by Funcy-dcm** [comment]
Try version 0.18.6
