### ISSUE TITLE
Change focus from news list to internal browser, on loading web page

### ISSUE THREAD

**Issue by ShamblerBishop** [QuiteRSS/quiterss#811]
This suggestion is for use in combination with double-clicking news items - i.e. when 'Show news description instead of loading web page' is checked - I don't know if it would be suitable for one-click loads.

When the internal web browser loads the web page, after a double-click, focus should be changed from the news list to the browser, so that the up/down arrow keys etc., can be used to navigate the page - this streamlines user interaction a bit.

**Comment by Funcy-dcm** [comment]
I agree. Will be implemented in QuiteRSS2
