### ISSUE TITLE
Options menu tooltip descriptions

### ISSUE THREAD

**Issue by ShamblerBishop** [QuiteRSS/quiterss#812]
When you hover over any configurable entries in the options menu, a tooltip describing the option in more detail, would be useful; this would require localization updates etc..

**Comment by Funcy-dcm** [comment]
I agree, it will be convenient. But I find it hard to choose the text for clues.

**Comment by ShamblerBishop** [comment]
Ya, that may be a bit tricky - can just leave ones that we're unsure of, without helper tooltip text.

Now that I'm a bit more familiar with the options code, from the 'news mouse config' change, I may have a shot at this - and at refactoring the options code in general, so it is easier to add stuff, and easier to see when tooltip help is missing.

I'm not doing this yet though, so this issue still 'open' for grabbing.
