### ISSUE TITLE
News list option - open item in new browser tab, by default

### ISSUE THREAD

**Issue by ShamblerBishop** [QuiteRSS/quiterss#815]
When you double-click an item in the news list, it would be good to be able to configure that, to open the item with the internal browser, in a new tab - you can do this with the keyboard shortcut 'T', but it'd be nice to have the option to make it default behaviour.

I've gone through the settings to see if this was already possible, and it doesn't seem to be.

This may be a bit overkill/advanced (so maybe only do if adding a 'Display Advanced Options' tickbox to preferences), but I'd suggest refactoring the options, to allow independently reconfiguring both 'single click' and 'double click' of news items, with a drop-down list having these selections:
- do nothing
- show description
- show description in new tab
- show description in new tab (background)
- load web page
- load web page in new tab
- load web page in new tab (background)
- load in external browser

You could also add a 'middle click' drop-down selection, with the same options, for maximum configurability.

Tab Mix Plus, for Firefox, has a great deal of configuration settings for the Mouse in this regard, which may be good for inspiration:
https://addons.mozilla.org/en-us/firefox/addon/tab-mix-plus/
Tax Mix Plus Options -> Mouse -> Mouse Click

**Comment by ShamblerBishop** [comment]
I've just discovered that 'middle click' already does this, and the 'Open links in embedded browser in background' option toggles whether this opens in background or foreground.

So that's good, all the functionality is already there, it just needs to be made more configurable (so, ticket is still valid).

**Comment by ShamblerBishop** [comment]
I've started on this - will look like this (will get rid of 'Show news description instead of loading web page', but will respect its bool setting in the config file):
![mouseoptions](https://cloud.githubusercontent.com/assets/6533522/9065798/c8a7778a-3acb-11e5-8686-0afdfffa0593.jpg)

**Comment by ShamblerBishop** [comment]
I have this done and ready to pull in - accidentally mixed it in with my previous pull, #817.

In my own repo, the commit is at ShamblerBishop/quiterss@77705a0d9cbfba2250848863179c41d245aff3a7.

**Comment by sevecose** [comment]
> I've started on this - will look like this (will get rid of 'Show news description instead of loading web page', but will respect its bool setting in the config file):
> ![mouseoptions](https://cloud.githubusercontent.com/assets/6533522/9065798/c8a7778a-3acb-11e5-8686-0afdfffa0593.jpg)

Where is it? Version 0.19.4
