### ISSUE TITLE
Does not Minimize on System Restart + Sits in Taskbar -  Resolved

### ISSUE THREAD

**Issue by ghost** [QuiteRSS/quiterss#816]
I believe I have found permanent solution.  Changed QuiteRss to start 45 seconds after boot.  Works every time.  My guess is it gives time for Windows Services QuiteRss needs to start.

If this is true it might solve other QuiteRss problems.

**Comment by Funcy-dcm** [comment]
Unfortunately, we can not implement support for these buttons
