### ISSUE TITLE
Provide larger logo for OSX

### ISSUE THREAD

**Issue by jfml** [QuiteRSS/quiterss#819]
Hey, just found out about QuiteRSS, it's really good!

However the application icon is low res and looks pretty bad in the application switcher (Cmd-tab) on OSX. Is it possible to provide a larger logo, I think OSX standard is 512px (I'd do it myself but I have no idea how to exchange icons in Qt apps).

Thanks a lot!

**Comment by kfix** [comment]
The current build on the website is 0.17.7 w/ QT4.
A new build of 0.18.x w/QT5 [might](https://trac.macports.org/ticket/36410) look [better](https://bugreports.qt.io/browse/QTBUG-23870).

**Comment by jfml** [comment]
Yeah, if they ever build the OSX-Version of 0.18 …

**Comment by Funcy-dcm** [comment]
https://quiterss.org/ru/article/878

**Comment by jfml** [comment]
@Funcy-dcm Cool, thanks so much! Unfortunately, the icon is still very pixelated (as much as before, I think) when switching apps (cmd-shift), see attached. But thanks again for making quiterss, it's by far the best RSS-reader out there.

![quiterss](https://cloud.githubusercontent.com/assets/4312909/13645436/ece1977c-e622-11e5-908b-2cb906d18a1d.jpg)
