### ISSUE TITLE
[0.18.2] Mark all feeds read doesnt work

### ISSUE THREAD

**Issue by pasha-zzz** [QuiteRSS/quiterss#820]
Subj bunnon doesnt mark all feeds read, only empties internal browser frame.

**Comment by Funcy-dcm** [comment]
I have everything working. You can make a video?

**Comment by pasha-zzz** [comment]
Ani GIF - http://rghost.ru/8zhbRmhN4.view

**Comment by online** [comment]
@pasha-zzz, если вы нормально не владеете английским языком, то зачем на нём пытаться изложить проблему? На приложенной вами анимации используется русский интерфейс, значит, скорее всего, вы носитель этого языка.

**Comment by pasha-zzz** [comment]
Mark all feeds read - вполне себе существующая кнопка. И она не работает. Разве это было непонятно из описания?
