### ISSUE TITLE
Unread news, when read, are marked unread again sometimes

### ISSUE THREAD

**Issue by rsola** [QuiteRSS/quiterss#821]
Windows 7 32-bit, QuiteRSS 0.18.2 portable (may be related to issue #800)

Suppose the option "Mark news as read" is set to "On selecting. With timeout 0 seconds". Also, the setting "Store DB in memory" is disabled.

Repro steps:
You select a feed with unread news. Within an interval of a few seconds after the feed is opened, you select an unread news item. It doesn't care whether the item is new or not. QuiteRSS marks the item as read, because the timeout expires immediately. However, the item state is unexpectedly reverted sometimes, i.e., is marked as unread. If it was new, it is also marked as such.

If you wait several seconds before selecting an item, this behavior usually doesn't happen. I haven't tested a "mark as read" timeout greater than zero or enabling "Store DB in memory".

Don't get me wrong. QuiteRSS is great, but I feel the 0.18.x releases a bit unstable. Thanks for developing this amazing software.

**Comment by Funcy-dcm** [comment]
Send video.

0.18.x - This transition to the new library Qt5. There may be a problem.

**Comment by rsola** [comment]
Hi, I have prepared three GIF images which I hope will clarify some aspects of this issue. Note: I didn't include the preview pane in the views.
1. Select a feed with an unread item, then use the green circle to mark as read (with a single mouse click):
   ![quiterss 0 18 2 toggle read 2](https://cloud.githubusercontent.com/assets/6336521/9157260/61256d3a-3ef7-11e5-9c9d-484d593977f6.gif)
   The item becomes marked as unread again.
2. One of the unread items is selected in a feed with two unread items. Then switch to another feed and return to the first feed.
   ![quiterss 0 18 2 toggle read 3](https://cloud.githubusercontent.com/assets/6336521/9157295/adcd502a-3ef8-11e5-9f03-ec7ac4e8b2f7.gif)
   The originally selected item is instantly marked as read because it is shown in the preview pane with a timeout of zero. However, it becomes marked as unread and a few seconds later is marked as read again, as would be expected.
3. One of the unread items (will be named A) is selected in a feed with two unread items. Then switch to another feed and return to the first feed. This time, click (select) the second unread item (named B).
   ![quiterss 0 18 2 toggle read 4](https://cloud.githubusercontent.com/assets/6336521/9157329/a7f18008-3ef9-11e5-8a4b-7287198f24b8.gif)
   Item A will stay as read. When selected, item B will be shown in the preview pane and marked as read. However, it will become unread again.

**Comment by Achaean** [comment]
Same problem here (at Mint 17.2 x64 KDE).

**Comment by Funcy-dcm** [comment]
Try version 0.18.6
