### ISSUE TITLE
[CLOSED - Devs don't care] Stay on top - unable to see the "add" and "clean up"

### ISSUE THREAD

**Issue by Teezton** [QuiteRSS/quiterss#823]
What happens 
User can't use/see the "Add" and "Clean Up" function since it's under the QuiteRSS.

Steps
1. Press "View"
2. Select "Stay On Top (F10)" 
3. Press "Add"

Vídeo
https://vimeo.com/135804754

OS version
Microsoft Windows 7 Service Pack 1 64-bit

Possible solution for QuiteRSS team
Create an exception for "Add" and "Clean Up" function.

**Comment by Teezton** [comment]
1 year and still no feedback or fix, good luck with your project.

**Comment by Funcy-dcm** [comment]
Fix version 0.18.6
