### ISSUE TITLE
Режим "Работать автономно"

### ISSUE THREAD

**Issue by i00kv6d** [QuiteRSS/quiterss#828]
Здравствуйте!
Возможно ли появления этого режима в программе? Очень не хватает!

Спасибо за внимание.

**Comment by Teezton** [comment]
There is no function like that.
Meanwhile you can remove this (see image), so you can "work offline":

![imagem 002](https://cloud.githubusercontent.com/assets/5905860/9293790/3a982ed0-4430-11e5-9548-1814d3bbd2ff.jpg)

**Comment by Funcy-dcm** [comment]
Вы можете просто не обновлять ленты и отключить отображение картинок
