### ISSUE TITLE
Undo button *badly* needed!

### ISSUE THREAD

**Issue by fixingshit** [QuiteRSS/quiterss#832]
I can't tell you how many times I've deleted a news article too soon and then found myself having to go through hell to get the information back. There really needs to be a working "undo last delete" function in QuiteRSS!

**Comment by Funcy-dcm** [comment]
1) Categories "Deleted", Button on News Toolbar "Restore News"
2) Shortcut key: CTRL+Z
3) ...

**Comment by fixingshit** [comment]
Huh? What are you talking about? There's no "categories", first of all.
