### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by golex12** [QuiteRSS/quiterss#833]
Добрый день!

Каждый раз при проверке RSS вылетает вот такое сообщение.
Как его можно заблокировать? 
![cer](https://cloud.githubusercontent.com/assets/13914952/9423070/8c7ad316-48bc-11e5-8464-81b9e51dcbde.jpg)

**Comment by Funcy-dcm** [comment]
Добрый день,
Можете дать ссылку на ленту?

**Comment by golex12** [comment]
Какая то из них RSS.
https://paste.ee/p/D3uei

QuiteRSS 0.18.2 revision 3623

**Comment by Funcy-dcm** [comment]
Я проблему не смог повторить. ОС какая?

**Comment by golex12** [comment]
Windows 10
Av: bitdefender internet security 2015

**Comment by Funcy-dcm** [comment]
Можете сделать скриншот окна диалога: "О программе - Информация"

**Comment by golex12** [comment]
![screen](https://cloud.githubusercontent.com/assets/13914952/9553528/493d870e-4dc8-11e5-8819-2b53eb7f2e01.jpg)

**Comment by Funcy-dcm** [comment]
Интересует вкладка "Информация"

**Comment by golex12** [comment]
![info](https://cloud.githubusercontent.com/assets/13914952/9562837/528c408a-4e80-11e5-8734-e341d61e3c1d.jpg)

**Comment by golex12** [comment]
Когда ждать функцию отключения предупреждения? 
Реально достали сообщения эти.

**Comment by Funcy-dcm** [comment]
Попробуйте версию 0.18.4
