### ISSUE TITLE
Possibility to use a custom tray icon

### ISSUE THREAD

**Issue by KabbAmine** [QuiteRSS/quiterss#834]
Hi, thanks for your wonderful program, I'm using it for a long time now (Linux & Windows) and it works great :+1: 

I'm a dark theme user, and the majority (If not all) of my icons are monochromatic, but the quiterss green one doesn't suit well with the theme.

![tray](https://cloud.githubusercontent.com/assets/5658084/9423998/01d5232e-48e4-11e5-9de5-6c39f95792f7.png)

It will be really great if we have possibility to use a custom tray icon, maybe via an option like the one in [qbittorrent](https://github.com/qbittorrent/qBittorrent) (Which uses also Qt).

![qb](https://cloud.githubusercontent.com/assets/5658084/9424076/9a0cf97a-48e7-11e5-97ec-b83b2cec9dea.png)

**Comment by Funcy-dcm** [comment]
Unfortunately, we draw the icon in real time. Now there is no time for implementation, because we will develop QuiteRSS2
