### ISSUE TITLE
QuiteRSS 0.8.2 in Fedora 22 freezes

### ISSUE THREAD

**Issue by sgros** [QuiteRSS/quiterss#835]
After starting QuiteRSS it works normally for a very brief period of time (few seconds at most) and then it freezes. The following messages are printed on the console:

(quiterss:26464): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(quiterss:26464): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(quiterss:26464): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

I noticed if I start QuiteRSS while in offline mode, and then connect to network it works normally. If I start QuiteRSS while being connected it freezes.

I also tried with the newest version available from QuiteRSS's site, but no luck.

Freeze happens also when I click to any link within the browsing pane. It loads about 70% of a Web page and then freezes. It seems to be always reproducible and related to the previously reported freeze.

Here is stack trace when the application is freezed:

> (gdb) thread apply all backtrace
> 
> Thread 11 (Thread 0x7fffa7b25700 (LWP 27995)):
> # 0  0x00000036c16f72fd in poll () at /lib64/libc.so.6
> # 1  0x00000036c4649dbc in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
> # 2  0x00000036c4649ecc in g_main_context_iteration () at /lib64/libglib-2.0.so.0
> # 3  0x00000036cdbba4ee in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 4  0x00000036cdb88791 in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 5  0x00000036cdb88b05 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 6  0x00000036cda78289 in QThread::exec() () at /lib64/libQtCore.so.4
> # 7  0x00000036cda7aaac in QThreadPrivate::start(void*) () at /lib64/libQtCore.so.4
> # 8  0x00000036c2207555 in start_thread () at /lib64/libpthread.so.0
> # 9  0x00000036c1702b9d in clone () at /lib64/libc.so.6
> 
> Thread 10 (Thread 0x7fffa7324700 (LWP 27996)):
> # 0  0x00000036c16f72fd in poll () at /lib64/libc.so.6
> # 1  0x00000036c4649dbc in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
> # 2  0x00000036c4649ecc in g_main_context_iteration () at /lib64/libglib-2.0.so.0
> # 3  0x00000036cdbba4ee in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 4  0x00000036cdb88791 in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 5  0x00000036cdb88b05 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 6  0x00000036cda78289 in QThread::exec() () at /lib64/libQtCore.so.4
> # 7  0x00000036cda7aaac in QThreadPrivate::start(void*) () at /lib64/libQtCore.so.4
> # 8  0x00000036c2207555 in start_thread () at /lib64/libpthread.so.0
> # 9  0x00000036c1702b9d in clone () at /lib64/libc.so.6
> 
> Thread 9 (Thread 0x7fffa6b23700 (LWP 27997)):
> # 0  0x00000036c16f72fd in poll () at /lib64/libc.so.6
> # 1  0x00000036c4649dbc in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
> # 2  0x00000036c4649ecc in g_main_context_iteration () at /lib64/libglib-2.0.so.0
> # 3  0x00000036cdbba4ce in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 4  0x00000036cdb88791 in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 5  0x00000036cdb88b05 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 6  0x00000036cda78289 in QThread::exec() () at /lib64/libQtCore.so.4
> # 7  0x00000036cda7aaac in QThreadPrivate::start(void*) () at /lib64/libQtCore.so.4
> # 8  0x00000036c2207555 in start_thread () at /lib64/libpthread.so.0
> # 9  0x00000036c1702b9d in clone () at /lib64/libc.so.6
> 
> Thread 8 (Thread 0x7fffa5f08700 (LWP 27998)):
> # 0  0x00000036c16f72fd in poll () at /lib64/libc.so.6
> # 1  0x00000036c4649dbc in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
> # 2  0x00000036c4649ecc in g_main_context_iteration () at /lib64/libglib-2.0.so.0
> # 3  0x00000036cdbba4ee in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 4  0x00000036cdb88791 in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 5  0x00000036cdb88b05 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 6  0x00000036cda78289 in QThread::exec() () at /lib64/libQtCore.so.4
> # 7  0x00000036cda7aaac in QThreadPrivate::start(void*) () at /lib64/libQtCore.so.4
> # 8  0x00000036c2207555 in start_thread () at /lib64/libpthread.so.0
> # 9  0x00000036c1702b9d in clone () at /lib64/libc.so.6
> 
> Thread 7 (Thread 0x7fffa507f700 (LWP 27999)):
> # 0  0x00000036c220c540 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
> # 1  0x00000036da18af61 in JSC::BlockAllocator::blockFreeingThreadMain() () at /lib64/libQtWebKit.so.4
> # 2  0x00000036da4896d6 in WTF::wtfThreadEntryPoint(void*) () at /lib64/libQtWebKit.so.4
> # 3  0x00000036c2207555 in start_thread () at /lib64/libpthread.so.0
> # 4  0x00000036c1702b9d in clone () at /lib64/libc.so.6
> 
> Thread 6 (Thread 0x7fff8e06e700 (LWP 28000)):
> # 0  0x00000036c16f72fd in poll () at /lib64/libc.so.6
> # 1  0x00000036c4649dbc in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
> # 2  0x00000036c4649ecc in g_main_context_iteration () at /lib64/libglib-2.0.so.0
> # 3  0x00000036cdbba4ee in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 4  0x00000036cdb88791 in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 5  0x00000036cdb88b05 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 6  0x00000036cda78289 in QThread::exec() () at /lib64/libQtCore.so.4
> # 7  0x00000036cdb68863 in QInotifyFileSystemWatcherEngine::run() () at /lib64/libQtCore.so.4
> # 8  0x00000036cda7aaac in QThreadPrivate::start(void*) () at /lib64/libQtCore.so.4
> # 9  0x00000036c2207555 in start_thread () at /lib64/libpthread.so.0
> # 10 0x00000036c1702b9d in clone () at /lib64/libc.so.6
> 
> Thread 5 (Thread 0x7fff8d86d700 (LWP 28003)):
> # 0  0x00000036c16f72fd in poll () at /lib64/libc.so.6
> # 1  0x00000036c4649dbc in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
> # 2  0x00000036c4649ecc in g_main_context_iteration () at /lib64/libglib-2.0.so.0
> # 3  0x00000036cdbba4ce in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 4  0x00000036cdb88791 in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 5  0x00000036cdb88b05 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () at /lib64/libQtCore.so.4
> # 6  0x00000036cda78289 in QThread::exec() () at /lib64/libQtCore.so.4
> # 7  0x00000036cda7aaac in QThreadPrivate::start(void*) () at /lib64/libQtCore.so.4
> # 8  0x00000036c2207555 in start_thread () at /lib64/libpthread.so.0
> # 9  0x00000036c1702b9d in clone () at /lib64/libc.so.6
> 
> Thread 4 (Thread 0x7fff7ffff700 (LWP 28005)):
> # 0  0x00000036c220c8e9 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
> # 1  0x00000036cda7aff4 in QWaitCondition::wait(QMutex*, unsigned long) () at /lib64/libQtCore.so.4
> # 2  0x00000036cda6e097 in QThreadPoolThread::run() () at /lib64/libQtCore.so.4
> # 3  0x00000036cda7aaac in QThreadPrivate::start(void*) () at /lib64/libQtCore.so.4
> # 4  0x00000036c2207555 in start_thread () at /lib64/libpthread.so.0
> # 5  0x00000036c1702b9d in clone () at /lib64/libc.so.6
> 
> Thread 3 (Thread 0x7fff7f7fe700 (LWP 28006)):
> # 0  0x00000036c220c8e9 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
> # 1  0x00000036cda7aff4 in QWaitCondition::wait(QMutex*, unsigned long) () at /lib64/libQtCore.so.4
> # 2  0x00000036cda6e097 in QThreadPoolThread::run() () at /lib64/libQtCore.so.4
> # 3  0x00000036cda7aaac in QThreadPrivate::start(void*) () at /lib64/libQtCore.so.4
> # 4  0x00000036c2207555 in start_thread () at /lib64/libpthread.so.0
> # 5  0x00000036c1702b9d in clone () at /lib64/libc.so.6
> 
> Thread 2 (Thread 0x7fff8d06c700 (LWP 28004)):
> # 0  0x00000036c220c8e9 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
> # 1  0x00000036cda7aff4 in QWaitCondition::wait(QMutex*, unsigned long) () at /lib64/libQtCore.so.4
> # 2  0x00000036cda6e097 in QThreadPoolThread::run() () at /lib64/libQtCore.so.4
> # 3  0x00000036cda7aaac in QThreadPrivate::start(void*) () at /lib64/libQtCore.so.4
> # 4  0x00000036c2207555 in start_thread () at /lib64/libpthread.so.0
> # 5  0x00000036c1702b9d in clone () at /lib64/libc.so.6
> 
> Thread 1 (Thread 0x7ffff7f83900 (LWP 27991)):
> # 0  0x00000036c16fceb9 in syscall () at /lib64/libc.so.6
> # 1  0x00000036c468f02f in g_cond_wait () at /lib64/libglib-2.0.so.0
> # 2  0x00000036c46711fb in g_once_init_enter () at /lib64/libglib-2.0.so.0
> # 3  0x00007fff77d63d08 in gdk_display_manager_get_type () at /lib64/libgdk-3.so.0
> # 4  0x00007fff77d63da9 in gdk_display_manager_get () at /lib64/libgdk-3.so.0
> # 5  0x00007fff77d63e79 in gdk_display_get_default () at /lib64/libgdk-3.so.0
> # 6  0x00007fff7c401233 in _gtk_modules_init () at /lib64/libgtk-3.so.0
> # 7  0x00007fff7c3d82db in post_parse_hook () at /lib64/libgtk-3.so.0
> # 8  0x00000036c46551c7 in g_option_context_parse () at /lib64/libglib-2.0.so.0
> # 9  0x00007fff7c3d7ff8 in gtk_parse_args () at /lib64/libgtk-3.so.0
> # 10 0x00007fff7c3d8059 in gtk_init_check () at /lib64/libgtk-3.so.0
> # 11 0x00007fff7c3d80a9 in gtk_init () at /lib64/libgtk-3.so.0
> # 12 0x00007fff7cac4faa in NP_Initialize () at /usr/lib64/mozilla/plugins/libevbrowserplugin.so
> # 13 0x00000036d985d4a1 in WebCore::PluginPackage::load() () at /lib64/libQtWebKit.so.4
> # 14 0x00000036d985d686 in WebCore::PluginPackage::fetchInfo() () at /lib64/libQtWebKit.so.4
> # 15 0x00000036d95dc016 in WebCore::PluginPackage::createPackage(WTF::String const&, long const&) () at /lib64/libQtWebKit.so.4
> # 16 0x00000036d95d98f7 in WebCore::PluginDatabase::refresh() () at /lib64/libQtWebKit.so.4
> # 17 0x00000036d95da912 in WebCore::PluginDatabase::installedPlugins(bool) () at /lib64/libQtWebKit.so.4
> # 18 0x00000036d8e544f2 in PlatformStrategiesQt::getPluginInfo(WebCore::Page const*, WTF::Vector<WebCore::PluginInfo, 0ul>&) () at /lib64/libQtWebKit.so.4
> # 19 0x00000036d9523034 in WebCore::PluginData::PluginData(WebCore::Page const*) () at /lib64/libQtWebKit.so.4
> # 20 0x00000036d94ffa00 in WebCore::Page::pluginData() const () at /lib64/libQtWebKit.so.4
> # 21 0x00000036d95233fb in WebCore::DOMPluginArray::length() const () at /lib64/libQtWebKit.so.4
> # 22 0x00000036d9e158fd in WebCore::jsDOMPluginArrayLength(JSC::ExecState*, JSC::JSValue, JSC::PropertyName) () at /lib64/libQtWebKit.so.4
> # 23 0x00000036da1fbf51 in JSC::JSValue::get(JSC::ExecState*, JSC::PropertyName, JSC::PropertySlot&) const () at /lib64/libQtWebKit.so.4
> # 24 0x00000036da2e07c3 in JSC::LLInt::getByVal(JSC::ExecState*, JSC::JSValue, JSC::JSValue) () at /lib64/libQtWebKit.so.4
> # 25 0x00000036da2dae5c in llint_slow_path_get_by_val () at /lib64/libQtWebKit.so.4
> # 26 0x00000036da2e491a in llint_op_get_by_val () at /lib64/libQtWebKit.so.4
> # 27 0x0000006e0000005b in  ()
> # 28 0x00007fffa4393cc0 in  ()
> # 29 0x00007fffa43d7660 in  ()
> 
> Python Exception <class 'OverflowError'> int too big to convert: 
> # 30 0xffffffffffffffff in  ()#31 0x00007fffa6101f80 in  ()
> # 32 0x0000000024244ad0 in  ()
> # 33 0x0000000000000000 in  ()

**Comment by Funcy-dcm** [comment]
http://quiterss.org/ru/forums/oshibki-zamechaniya/padaet-pri-zapuske

**Comment by Funcy-dcm** [comment]
Unfortunately, this problem is not yet know how to solve.
Try disabling the option "Enable JavaScript"

**Comment by sgros** [comment]
Disabling JavaScript makes QuiteRSS responsive. Thanks.

**Comment by Funcy-dcm** [comment]
This problem is the core Webkit
