### ISSUE TITLE
Пропадание столбцов в списке записей

### ISSUE THREAD

**Issue by birkoffe** [QuiteRSS/quiterss#837]
При первом запуске quiterss в RDP-сессии не всегда корректно отображаются столбцы в списке записей.

![screenshot_1](https://cloud.githubusercontent.com/assets/828228/9806045/c18e1216-5861-11e5-9500-dfaa5ac69cfd.png)

При любом изменении размера столбцы нормально появляются

![screenshot_2](https://cloud.githubusercontent.com/assets/828228/9806060/e21e3290-5861-11e5-8d55-85263f746487.png)

Хост машина Win8.1x64

**Comment by Funcy-dcm** [comment]
К сожалению, мы не можем решить эту проблему. Постараюсь применить другую реализацию в QuiteRSS2
