### ISSUE TITLE
C++ error

### ISSUE THREAD

**Issue by naughtiesfriend** [QuiteRSS/quiterss#850]
When going to read a post, I get a popup diagnostic that when I click on "Ok" it closes the program.  Please see the diagnostic attached.  Help! How do I get rid of it.  It worked fine before.
![1](https://cloud.githubusercontent.com/assets/15224476/10626614/d5527fda-777e-11e5-9a46-4b074f9a81ab.jpg)

**Comment by Funcy-dcm** [comment]
Send video

**Comment by naughtiesfriend** [comment]
Please find it attached

**Comment by Funcy-dcm** [comment]
Try version 0.18.4
