### ISSUE TITLE
QuiteRSS constantly freezes. [Kubutnu 15.10]

### ISSUE THREAD

**Issue by kirillmukhin** [QuiteRSS/quiterss#851]
Kubuntu 15.10 (64-bit); QuiteRSS 0.18.2

 The program freezes while attempting to update the feed(-s). However, if the updating feed(-s) have no new articles, the program is working as it should.

 Obviously, the problem occurs when importing / adding new feeds. After adding new feed you can see it in the feed list and you can see unread articles, but program instantly freezes. At the next launch, after force quit, that feed disappears.

Once I was able to add 25+ feeds and update them. Though, after restarting QuiteRSS, neither adding, nor updating feeds were not working.

Terminal output:

> ~$ quiterss 
> (quiterss:2696): GLib-GObject-WARNING **: cannot register existing type 'GstObject'
> 
> (quiterss:2696): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
> 
> (quiterss:2696): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed
> 
> (quiterss:2696): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
> 
> (quiterss:2696): GStreamer-CRITICAL **: gst_element_class_set_details_simple: assertion 'GST_IS_ELEMENT_CLASS (klass)' failed
> 
> (quiterss:2696): GStreamer-WARNING **: static caps 0x7f65c500de90 string is NULL
> 
> (quiterss:2696): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
> 
> (quiterss:2696): GStreamer-WARNING **: static caps 0x7f65c500de10 string is NULL
> 
> (quiterss:2696): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
> 
> (quiterss:2696): GStreamer-WARNING **: static caps 0x7f65c500de90 string is NULL
> 
> (quiterss:2696): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed

**Comment by voidquest** [comment]
Kubuntu 15.10 (64-bit), QuiteRSS 0.18.2

I've had exactly the same experience as Thrash-td.

**Comment by Funcy-dcm** [comment]
Try version 0.18.6
