### ISSUE TITLE
Заставка при запуске не отключается

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#862]
Несмотря на то, что "показывать заставку при запуске" в настройках QuiteRSS отключена, она все равно всплывает при каждом запуске. Эта проблема появилась только после перехода на Ubuntu Gnome 15.10 c 15.04. При этом версия QuiteRSS вроде не менялась.

Прилагаю свой [QuiteRss.ini.txt](https://github.com/QuiteRSS/quiterss/files/52931/QuiteRss.ini.txt) (переименовал на *.ini.txt для того чтобы этот файл можно было залить на GitHub - просто *.txt не берет).

Версия 0.18.2 (14.07.2015)

**Comment by sojusnik** [comment]
После инсталляции 0.18.3 через [launchpad ppa](https://launchpad.net/~quiterss/+archive/ubuntu/quiterss) проблема исчезла.

**Comment by sojusnik** [comment]
После инсталляции (0.18.4+dfsg-1) из официальных репозиториев Ubuntu 16.10 заставка опять всплывает при запуске, хотя в настройках это отключено.

**Comment by Funcy-dcm** [comment]
С файлом настроек всё в порядке. С ним у меня работает всё как надо. Возможно у вас его не подхватывает

**Comment by sojusnik** [comment]
Файл вроде один и тот же, но все зависит от метода инсталляции: Если через официальный репозиторий Ubuntu инсталлировать, заставка появляется при каждом запуске, а если через [launchpad ppа](https://launchpad.net/%7Equiterss/+archive/ubuntu/quiterss), то нет.

Сейчас QuiteRss.ini лежит в /.config/QuiteRss/QuiteRss.ini

PS: На данный момент http://quiterss.org/ недоступен. Вы планируете в будущем дальше работать над Вашим великолепным ридером?

**Comment by Funcy-dcm** [comment]
Здесь launchpad ppа собирал человек с нашей команды. Про официальный репозиторий я не в курсе.
Сайт сейчас переезжает на новый сервер.
Я уже несколько раз пытался перевести проект на последний Qt, но там новый движок браузера. Выводы такие что проще переписать приложение.

**Comment by sojusnik** [comment]
Сочувствую!

И еще маленькое наблюдение: Если в Gnome [сменить рабочее место](https://www.youtube.com/watch?v=bRHAio98n-g), то QuiteRSS больше не отображается как активная программа [в левом доке](http://i.imgur.com/1VnTFEO.jpg). Даже с помощью Alt+Tab на нее больше нельзя вернуться. А если с лаунчпада брать, то все как положено...

**Comment by sojusnik** [comment]
> И еще маленькое наблюдение: Если в Gnome сменить рабочее место, то QuiteRSS больше не отображается как активная программа в левом доке. Даже с помощью Alt+Tab на нее больше нельзя вернуться. А если с лаунчпада брать, то все как положено...

С Qt4 версией, которая с лаунчпада, все работает как положено. А если взять Qt5 версию из официального репозитория Ubuntu, то глючит.

**Comment by Funcy-dcm** [comment]
Попробуйте версию: 0.18.10. Там была проблема в файле настроек.

**Comment by sojusnik** [comment]
@Funcy-dcm Спасибо! Теперь жду пока Андрей обновит [репозиторий](https://launchpad.net/~quiterss/+archive/ubuntu/quiterss) для Ubuntu.
