### ISSUE TITLE
Feature Request: "Mark news as read while reading in newspaper layout"

### ISSUE THREAD

**Issue by war59312** [QuiteRSS/quiterss#872]
Hi,

Would love to have:

"Mark news as read while reading in newspaper layout"

See this option in RSSOwl.

As you scroll using the mouse, each article gets marked as read.

A hell of a lot easier than having to mark each article as read or having to mark them all as read.

Update: Looks like support was starting to be added:

https://github.com/QuiteRSS/quiterss/blob/master/src/feedpropertiesdialog.h#L55

Thank you,

Will

**Comment by Funcy-dcm** [comment]
https://quiterss.org/en/node/1153
