### ISSUE TITLE
Support for RTL langauges in interface

### ISSUE THREAD

**Issue by damascene** [QuiteRSS/quiterss#875]
Text in RTL languages (read and written from right to left) is shown with wrong alignment.
Text is aligned to left while it should be aligned to right.

Some of RTL languages are: Arabic, Persian, Hebrew and Urdu

In Quiterss
![screenshot from 2016-01-06 10 53 53](https://cloud.githubusercontent.com/assets/411046/12138999/c346f50e-b465-11e5-8ef2-cdb1c73dc4ef.png)

In other program with better alignment in feed preview 
![screenshot from 2016-01-06 11 01 09](https://cloud.githubusercontent.com/assets/411046/12138897/0dd4a536-b465-11e5-95da-9e97d3cf75b1.png)

**Comment by Funcy-dcm** [comment]
Try version: 0.18.10
