### ISSUE TITLE
Support for dark themes missing

### ISSUE THREAD

**Issue by genodeftest** [QuiteRSS/quiterss#877]
Steps to reproduce:
1. change your qt theme to e.g. breeze-dark
2. start quiterss

What happens:
- News list is showing gray font on dark gray background, barely readable.
- Feed tree view is showing gray or dark blue font on dark gray background, barely readable.
- In many places all over the application (including preferences dialog) table column headers are displayed black on white instead of light on dark

Suggested solution:
Remove all code with custom colors and custom styling.

**Comment by jornmo** [comment]
I confirm! This is not good at all with Breeze Dark. (I am using the QT5 version)

**Comment by clayote** [comment]
This is the only thing keeping me with Liferea.

**Comment by Funcy-dcm** [comment]
@genodeftest Send screenshots

**Comment by genodeftest** [comment]
@Funcy-dcm : I'm sorry I cannot provide a screenshot because I cannot choose breeze-dark on my current system.

@jornmo, @LogicalDash : Can you provide the screenshot, please?

**Comment by glaubersm** [comment]
My system: 
Arch Linux
KDE Plasma 5.13.3 desktop environment
QuiteRSS Version 0.18.12 (02.07.2018)

![quiterss](https://user-images.githubusercontent.com/15967631/42950940-7603b5a6-8b4b-11e8-9efe-df895150185a.png)

![quiterss2](https://user-images.githubusercontent.com/15967631/42950941-762f7eca-8b4b-11e8-8733-73375f97da1d.png)

![quiterss3](https://user-images.githubusercontent.com/15967631/42951148-ef60b354-8b4b-11e8-9085-0e7c3430db14.png)

**Comment by rodneyrod** [comment]
Confirming the same issue here.

**Comment by marrub--** [comment]
![An example of the issue](http://mab.greyserv.net/f/1549989383528.png)
This issue makes it impossible to use the program with Windows set to High Contrast. Either the background needs to be the system default, or the text needs to be explicitly black. Alternatively, make both of them configurable.

**Comment by Katarn** [comment]
Just remove all styles from selected by you .qss-file in application folder.

**Comment by jaakristioja** [comment]
This also happens on first install on latest Kubuntu. It seems that I'm not going to start using QuiteRSS... :-(
![quiterss](https://user-images.githubusercontent.com/2684083/58046354-b3c15180-7b4d-11e9-8036-ca520c2a9eeb.png)

**Comment by 532910** [comment]
quiterss 0.19.1+dfsg-1 debian sid, `$QT_QPA_PLATFORMTHEME=qt5ct`, Adwaita-Dark
![image](https://user-images.githubusercontent.com/14617699/69082176-9c0d4c00-0a50-11ea-9b9c-251879ec2482.png)

![image](https://user-images.githubusercontent.com/14617699/69082206-acbdc200-0a50-11ea-98cb-c14242d012fe.png)

**Comment by Katarn** [comment]
@jaakristioja @532910 Have you tried doing as I suggested?

**Comment by jaakristioja** [comment]
@Katarn I don't understand your suggestion. What exactly do you suggest to remove? From what folder?

**Comment by 532910** [comment]
it's a first run after the clean install without any user modifications, so there are nothing to remove

**Comment by Katarn** [comment]
Remove all *.qss (but not *.css!) files from /usr/share/quiterss/style and restart app.

**Comment by 532910** [comment]
<del> Nothing changed. </del>
My fault, looks dark now, but with issues:

![image](https://user-images.githubusercontent.com/14617699/69091948-68d0ba00-0a5c-11ea-89cd-0f16fd5b0d10.png)

**Comment by Katarn** [comment]
```¯\_(ツ)_/¯```

It can tuning. Restore deleted files (e.g., reinstall app) and in qss file tune colors. As I understand it, this task is not of primary importance, so you can try to adapt the colors yourself.

**Comment by maboroshin** [comment]
Use the new dark.qss. And These specifications override the theme.

Empty the following in `QuiteRSS.ini`: 
```feedsListBackgroundColor=
newsListBackgroundColor=
focusedNewsTextColor=
focusedNewsBGColor=
focusedFeedTextColor=
focusedFeedBGColor=
```

Sample: Overwriting remains in the left part on the white theme.
![quiteRSSOver](https://user-images.githubusercontent.com/41102508/69897572-1f079e00-1391-11ea-87fb-ff5b1a2e70dc.png)

**Comment by maboroshin** [comment]
Specification in theme file is unknown.

- Link color (linkColor)
- Feed with new news (feedWithNewNewsColor)
- Count of unread news in feeds tree (countNewsUnreadColor)
- Alternating row colors (alternatingRowColors)
- Margin at the bottom of the link list

Link color has poor visibility.
 
![quiteRSSweb](https://user-images.githubusercontent.com/41102508/69897631-08157b80-1392-11ea-8c57-2aa5876c8b4e.png)

Margin color between little news list and web. Web background?
![quiteRSSMargin](https://user-images.githubusercontent.com/41102508/69897633-0a77d580-1392-11ea-938b-cb6747add0e5.png)

**Comment by maboroshin** [comment]
I create [Color Theme Converter](https://genkaku.in/tool/replacetheme.html). Please check it.

**Comment by maboroshin** [comment]
`newsTextColor=`
- × :  **When it is empty**, the dark color specified in the theme becomes the background. However, the font color becomes black. Thus we can't see the text. 
- Default: **Specify this color**. This text color and background color are **overwritten by default**.

**Comment by maboroshin** [comment]
Please version 0.19.3 or higher. Or use [Color Theme Converter](https://genkaku.in/tool/replacetheme.html).

![quiteRSSOver](https://user-images.githubusercontent.com/41102508/69912970-b4c82980-1474-11ea-9cd0-612043b85304.png) Sample image about override.

And These specifications override the theme. To empty the following in ```QuiteRSS.ini```:

If `alternatingRowColors=` (Empty), Then this color to be Black in Light theme. Thus, alternate color can not use in the light theme. A single color can be switched between dark and light depending on the theme.

(maybe). In `dark.qss`, `alternate-background-color: #3a393a;` is not reflect.

For devdeloper, Please make default value when empty.
- `alternatingRowColors=#f6f6f6` (light)
- `alternatingRowColors=#3a393a` (dark)

To Empty for loading default source code's value. Or `linkColor` to be magic blue `#0089DB`. Magic blue is visible for dark/light.
```
linkColor=
newsListBackgroundColor=
```

To Empty for load the theme. Otherwise, the lights overlap in the dark.
```
feedsListBackgroundColor=
focusedNewsTextColor=
focusedNewsBGColor=
focusedFeedTextColor=
focusedFeedBGColor=
```

I don't know setting this value, in theme. However, the theme color is reflected. Which value? Is it a default value in the source?
```
feedWithNewNewsColor=
```

Note : I checked Windows 10, not Linux.

**Comment by maboroshin** [comment]
I adjusted the value of the dark theme file (`dark.qss`) and the `QuiteRSS.ini` file.
It becomes the default value. ("Default color" part of the image below) But we can be used as the dark.
![qdark](https://user-images.githubusercontent.com/41102508/69913006-50f23080-1475-11ea-9834-bd0059990163.png)

**Comment by jaakristioja** [comment]
> Remove all *.qss (but not *.css!) files from /usr/share/quiterss/style and restart app.

@Katarn It says "Permission denied" when I try to do that.

**Comment by meelten** [comment]
> I adjusted the value of the dark theme file (`dark.qss`) and the `QuiteRSS.ini` file.
> It becomes the default value. ("Default color" part of the image below) But we can be used as the dark.
> ![qdark](https://user-images.githubusercontent.com/41102508/69913006-50f23080-1475-11ea-9834-bd0059990163.png)

Can you tell me step by step how to achieve that? I want to use system theme but then news window is white which looks bad with dark system theme. I don't know what should I edit to change news background color.

**Comment by Digitalone1** [comment]
February 2021 and this issue is still existent. Using adwaita-dark on Gnome causes issues in QuiteRSS. I know there's a workaround, but it's not acceptable to edit a style file when the application should follow the system configuration.

I switched to Liferea.

**Comment by Funcy-dcm** [comment]
Menu - View - Application style - System or Dark

**Comment by Digitalone1** [comment]
I was searching in the Tool > Options. Maybe the Style dialog could be inserted there. My bad anyway.

**Comment by hffaust** [comment]
would love to see this come true in 2022

**Comment by ClandestineClout** [comment]
Is there any way to install a dark reader extension to make the built-in browser display pages in dark mode? (Windows)

**Comment by ghost** [comment]
> Remove all *.qss (but not *.css!) files from /usr/share/quiterss/style and restart app.

That worked, thanks!
