### ISSUE TITLE
WARNING: DirectShowPlayerService::doSetUrlSource: Unresolved error code 80004005

### ISSUE THREAD

**Issue by TerVel76** [QuiteRSS/quiterss#878]
Приложение не отвечает (Application not responding)

debug.log:
15.01.2016 12:05:52.261 WARNING: Run application!
15.01.2016 12:05:52.372 WARNING: Preparation database
15.01.2016 12:05:52.388 WARNING: sqliteDBMemFile(): from file to memory...
15.01.2016 12:05:52.626 WARNING: sqliteDBMemFile(): finished!
15.01.2016 12:05:52.628 WARNING: Run application 2
15.01.2016 12:05:54.823 WARNING: Run application 3
15.01.2016 12:05:54.834 WARNING: Run application 4
15.01.2016 12:05:54.839 WARNING: Run application 5
15.01.2016 12:05:55.101 WARNING: Run application 6
15.01.2016 12:06:20.721 WARNING: DirectShowPlayerService::doSetUrlSource: Unresolved error code 80004005

Task killed !

**Comment by TerVel76** [comment]
21.01.2016 13:56:36.972 WARNING: DirectShowPlayerService::doSetUrlSource: Unresolved error code 80004005

**Comment by Funcy-dcm** [comment]
Try version 0.17.7

**Comment by TerVel76** [comment]
Версия 0.18.3 (26.01.2016) Ревизия 3659
Проблем, пока, не замечено.

**Comment by TerVel76** [comment]
Опять зависло. 
Версия 0.18.3 (26.01.2016) Ревизия 3659

16.02.2016 14:37:29.680 WARNING: DirectShowPlayerService::doSetUrlSource: Unresolved error code 80004005

**Comment by Funcy-dcm** [comment]
А попробовали версию 0.17.7?

**Comment by TerVel76** [comment]
Вернулся к 0.17.7 
Зависания нету.
