### ISSUE TITLE
Не загружаются изображения с некоторых сайтов

### ISSUE THREAD

**Issue by Vladimir-Vl** [QuiteRSS/quiterss#880]
Здравствуйте!

Сегодня первый раз познакомился с Вашей программой.
RSS читаю через Opera с плагином Smart RSS.
Но, в силу определённых неудобств, подумываю перейти на другое (возможно, Ваше) приложение.
Столкнулся с тем, что на некоторых сайтах не загружаются изображения вместе с RSS новостями.
Вот эти ленты:
http://www.mrsk-sib.ru/index.php?option=com_content&view=category&layout=blog&id=1111&Itemid=2476&lang=ru22&format=feed&type=atom
http://www.mrsk-sib.ru/index.php?option=com_content&view=category&layout=blog&id=1111&Itemid=2476&lang=ru22&format=feed&type=rss

Также Ваша программа не хочет подхватывать ленту
http://www.nalog.ru/rn22/rss/

А в Opera этих проблем нет.
Не поможете с их решением?

**Comment by Funcy-dcm** [comment]
Первые две ленты с ошибкой (не соответствуют стандартам), необходимо обратится к администратору сайта. Ссылки на ленты с ошибкой.
Последняя лента в следующей версии будет работать.

**Comment by Vladimir-Vl** [comment]
Администратор сайта однозначно делать ничего не будет (уже имел опыт общения с ними - либо отмалчиваются, либо пишут - политика компании). Тем более что с загрузкой изображений нет проблем ни у Opera, ни у Microsoft Outlook, ни, наверное, и у других RSS-ридеров. Да, когда пробуешь перейти по ссылке новости, то браузер выдаёт ошибку. Так как они в ссылке указывают внутренний сервер http://basite02 (для внутри корпоративной сети) вместо www.mrsk-sib.ru. И если в ссылке на новость вручную заменить basite02 на www.mrsk-sib.ru, то можно перейти на новость и из общедоступной сети.
Может Вы поможете мне решить эту проблему? Хотелось бы читать новости вышеуказанных "проблемных" ресурсов и видеть прилагаемые к ним изображения именно через Ваш RSS-ридер избавившись от необходимости работать одновременно и с другими RSS-ридерами.
В любом случае - спасибо.

**Comment by Funcy-dcm** [comment]
Я сначала хотел сделать такой хак, но из-за одной проблемной ленты подумал лучше не стоит перегружать программу (обычно делаю, если несколько лент с одинаковыми проблемами).
По поводу изображений, я могу починить, но переход по ссылкам работать не будет.

**Comment by Vladimir-Vl** [comment]
Да, мне хотя бы только изображения, а переход по кривой ссылке я сам в случае необходимости сделаю вручную.
Кстати.
После запуска Updater.exe (для скачивания MSVCR120.dll) проблемы с лентой http://www.nalog.ru/rn22/rss/ решились сами.

**Comment by Funcy-dcm** [comment]
Я в первом комментарии писал что в следующей версии работать будет, это как раз из-за отсутствия этого файла.
