### ISSUE TITLE
Can no longer double click to open an article in external browser

### ISSUE THREAD

**Issue by vzjrz** [QuiteRSS/quiterss#881]
I used to be able to just double click a link and it would open it in the external browser. Now I have to right-click then select "Open in External Browser" or press Enter.
Is there a way to bring this feature back?

**Comment by Funcy-dcm** [comment]
https://quiterss.org/ru/forums/bugs/external-browser

**Comment by vzjrz** [comment]
@Funcy-dcm Thanks!
