### ISSUE TITLE
v18.3 doesn't load the webpage but shows news description

### ISSUE THREAD

**Issue by WSpu** [QuiteRSS/quiterss#882]
The latest version doesn't show the webpage (all the time) anymore when you click on a news item although the settings in the feed and the general options are correct. I noticed when you click on the feed the first unread news item is selected and the webpage is loaded once. When I click on a other news item from the same feed the news description is shown and also when I click again on the previous selecten news item. 

P.S. issue [800](https://github.com/QuiteRSS/quiterss/issues/800) also isn't fixed in this version.

**Comment by bearburger** [comment]
Interesting fact. If you use arrows to navigate between news it opens webpage but if you click on them it shows only description.

Proof http://i.imgur.com/JXlHSSF.gifv

**Comment by Funcy-dcm** [comment]
https://quiterss.org/ru/forums/bugs/external-browser

**Comment by bearburger** [comment]
Речь о встроенном браузере. Если переключаться между новостями не мышкой, а стрелками, все работает, как в прежних версиях, а с мышкой показывается только то, что отдается РССом. Вот с этими настройками в прошлой версии все работало, как надо.

![settings](http://i.imgur.com/St7Uo8s.png)

К слову, настройка "Ленты -> Показывать описание новости вместо загрузки веб-страницы" снята.

**Comment by bearburger** [comment]
Вот, сделал видео, вроде понятно, в чем проблема https://youtu.be/MAo5PAoDwlk . Если бы было дело в настройках, полагаю поведение не менялось бы от изменения способа навигации с мыши на клавиатуру и обратно.

**Comment by Funcy-dcm** [comment]
Tools>Options>Feeds>Reading>Single Click: Load Web Page

**Comment by WSpu** [comment]
The option "Tools>Options>Feeds>Reading>Single Click: Load Web Page" doesn't honor the setting "Show news' description instead of loading webpage" which can be set by changing the property of the feed itself. Probably you must overwrite the general reading setting by setting the display option of the feed.

The display and reading settings of the feed and general options are confusing!

**Comment by Funcy-dcm** [comment]
I agree! New features added to other developers. I do not know how to do better.
