### ISSUE TITLE
Приложение зависает

### ISSUE THREAD

**Issue by evgen-eao** [QuiteRSS/quiterss#885]
Зависает полностью после просмотра некоторых новостей с этой ленты http://feed.exileed.com/vk/feed/livebir?img_size=xbig

**Comment by Funcy-dcm** [comment]
Какая у вас ОС?
Попробуйте отключить опцию "Настройки - Браузер - Общие - Включить JavaScript"

**Comment by evgen-eao** [comment]
Windows 7 x64.
Отключил Javascript, всеравно зависает. Потом еще пробовал отключить плагины. Похоже зависает из-за аудиоплеера в новости.

**Comment by Funcy-dcm** [comment]
Попробуйте версию 0.17.7

**Comment by TerVel76** [comment]
ВО время зависания посмотрите debug.log (возле программы)
Возможно там моя ошибка: https://github.com/QuiteRSS/quiterss/issues/878

**Comment by evgen-eao** [comment]
Да, ошибка в логе такая WARNING: DirectShowPlayerService::doSetUrlSource: Unresolved error code 800c0006

**Comment by Funcy-dcm** [comment]
Версию 0.17.7 пробовали? Надо понять это из-за нового движка браузера или нет

**Comment by evgen-eao** [comment]
Да, пробовал. В ней все отлично.

**Comment by Funcy-dcm** [comment]
Отлично, значит проблема в Webkit, буду уходить обратно к Qt4. Рекомендую пока использовать 0.17.7, она более стабильна

**Comment by online** [comment]
@Funcy-dcm, спасибо. То же попробую вернутся к версии 0.17.7.

**Comment by Funcy-dcm** [comment]
#756
