### ISSUE TITLE
Системная ошибка (MSVCR120.dll)

### ISSUE THREAD

**Issue by Vladimir-Vl** [QuiteRSS/quiterss#886]
![2016-01-31_180025](https://cloud.githubusercontent.com/assets/16913785/12702032/d0b16564-c845-11e5-8862-c05d32332c08.png)
При запуске программы выдаётся системная ошибка (см. скриншот).
Это я скачал дистрибутив Вашей программы со стороннего сервера?
Или надо что-то доустановить?
В будущем новые версии программы планирую скачивать только с Вашего сайта.
Windows 7 Максимальная (64-разрядная)

**Comment by Funcy-dcm** [comment]
Запустите Updater.exe, он должен скачать необходимый файл

**Comment by Vladimir-Vl** [comment]
Спасибо!
Всё получилось.
