### ISSUE TITLE
News Items no longer open in external browser (0.18.3)

### ISSUE THREAD

**Issue by qcybb** [QuiteRSS/quiterss#888]
The latest update broke the "open links in external browser" setting (Browser / General / Use External Browser).

I adjusted the new settings for single and double click, and it still wants to open news items internally, not in my external browser.

Reverting back to version 0.18.2 fixes the issue.

**Comment by ghost** [comment]
Workaround:

1. Move all of your feeds under a new, common folder
2. Right click on that folder
3. Click properties
4. Click Reading tab
5. Set Single Click = Nothing
6. Set Double Click = Open in External browser
7. Click OK
