### ISSUE TITLE
local qt theme not supported

### ISSUE THREAD

**Issue by ghost** [QuiteRSS/quiterss#889]
quiterss doesn't support local qt theme settings.

Version 0.18.3 (26.01.2016) Qt5 (5.3.2). Debian jessie. Qt theme: QtCurve

Selecting application style from menu doen't have effect. Only for colors.

**Comment by sojusnik** [comment]
Same here on Ubuntu Gnome 15.10 64-bit. It is also mentioned in the [forum](https://quiterss.org/en/forums/oshibki-zamechaniya/tema-qt).

**Comment by ghost** [comment]
The same on Qt4 (4.8.6)

**Comment by ghost** [comment]
Fixed using qt5ct. When qt theme set by qt5ct instead of QT_STYLE_OVERRIDE theme works well in quiterss. So, I think it is not quiterss bug and this issue can be closed.

**Comment by sojusnik** [comment]
Curiously, QuiteRSS started to theme properly after the installation of the 0.18.3 version from the [launchpad ppa](https://launchpad.net/~quiterss/+archive/ubuntu/quiterss), while installing from the main Ubuntu repository did not apply the proper theme.

В чем может быть причина?

**Comment by ghost** [comment]
qt5?

**Comment by sojusnik** [comment]
I don't know if the version from the main Ubuntu repository used qt5, but the current one is using qt4 and works without any problems: [about screenshot](http://i.imgur.com/akIEJej.png).
