### ISSUE TITLE
Поддержка QtWebEngine в сборке для Qt5

### ISSUE THREAD

**Issue by Katarn** [QuiteRSS/quiterss#893]
По моим впечатлениям от демок, работает намного быстрее, стабильнее и плавнее чем QtWebKit. Последний время от времени любит сегфолтиться, ну и постоянные подвисания приложения при открытии нового таба напрягают.

**Comment by Funcy-dcm** [comment]
Согласен, что QtWebEngine лучше, но мы не можем портировать все используемые функции с QtWebKit на новый движок. Пока планируем откатится обратно на Qt4, там QtWebKit более стабилен. У вас какая ОС?

**Comment by Katarn** [comment]
> У вас какая ОС?

Gentoo Linux. И, собственно, скомпилирован с Qt4, на котором он себя так и ведёт. А что именно не хватает в QtWebEngine?

**Comment by Funcy-dcm** [comment]
Ох, что-то давно не разбирал Issues, вот понемногу пытаюсь отвечать.
В общем в начале 2017 года пытался перейти на QtWebEngine, но из-за того что архитектура проекта очень завязана на QtWebKit ничего не вышло.
Сейчас начал разработку QuiteRSS2 с нуля. Хочу сделать архитектуру нового проекта более гибкой.
Кстати, спасибо вам за помощь! Я видел как вы отвечаете на некоторые Issue ;)
Думаю что есть смысл закрыть этот Issue, т.к. переходим на реализацию QuiteRSS2 с QtWebEngine (https://github.com/QuiteRSS/quiterss2)

**Comment by Funcy-dcm** [comment]
Ещё хотел вас добавить в список помощников. Если есть желание, то присылайте на почту ник или имя, как вам удобнее, и адрес почты если надо его показать. Вот пример: https://github.com/QuiteRSS/quiterss/blob/master/AUTHORS

**Comment by Katarn** [comment]
Привет, у меня много обязательств, не уверен что буду заглядывать регулярно. За предложение спасибо, как и за прекрасную программу. :)

А насчёт темы обсуждения, есть такой проект - http://qtwebkit.blogspot.ru/2016/08/qtwebkit-im-back.html и его страница на GitHub - https://github.com/annulen/webkit, может быть он поможет малой кровью обновить QtWebKit до актуальной версии, в ожидании QuiteRSS2, и сделать его стабильным и быстрым.

**Comment by Funcy-dcm** [comment]
Спасибо за ссылки, посмотрел, там не так всё просто, я уже весь в разработке QuiteRSS2, так что просто не хочу отвлекаться и тратить время

**Comment by Katarn** [comment]
В общем, у меня получилось собрать annulen'овский QtWebKit под Linux безо всяких танцев с бубном и ничего не меняя в коде QuiteRSS, после чего видосики на ютубе стали отлично играть, никаких крэшей и в целом отзывчивость стала выше.

**Comment by Funcy-dcm** [comment]
Круто! Я тут, к сожалению, выпал из разработки.
Можешь дать инструкцию, что да как? Ты прямо исходники QtWebKit добавил в проект?
Я нашёл, попробую в ближайшее время

**Comment by Katarn** [comment]
Я этим ебилдом устанавливал, предварительно удалив оригинальный qtwebkit, потому что annulen'овский ставится вместо него: https://gist.github.com/annulen/309569fb61e5d64a703c055c1e726f71
Собирал с USE="multimedia"
Потом просто пересобрал quiterss-9999 из портежа, ничего никуда не добавляя.

**Comment by Funcy-dcm** [comment]
Понял, но так получается что quiterss подхватит библиотеки, которые у вас собрались. Как быть обычным пользователям? Для Windows я попробую сделать, непонятно что делать с Linux

**Comment by Katarn** [comment]
В случае Linux в описании сборки можно указать возможность работы с annulen-webkit. По функциям ничего не меняется, только стабильность повышается. У меня сайты лучше стали отображаться ещё, но это другое, к функциям приложения непосредственно не относится.

**Comment by Funcy-dcm** [comment]
Для сборки под Linux это понятно, я имею ввиду тех кто пользуется готовыми пакетами

**Comment by Katarn** [comment]
Может, статичную линковку заюзать, так вроде принято на винде - и попробовать сначала под ней, а потом уже под линем?

**Comment by Funcy-dcm** [comment]
Я под виндой просто хотел нужную библиотеку собрать в виде dll, я так и делал прежде, когда ошибки правил в webkit-e. А как её слинковать с приложением даже и не представляю пока )

**Comment by Katarn** [comment]
Так вроде под линуксом тоже так можно. Я не специалист по C++, но вижу часто, что в /opt стоят проги с собранными библиотеками, та же Opera на вебките тащит с собой ffmpeg отдельным .so-файлом.

**Comment by Funcy-dcm** [comment]
Ааа, ну надо попробовать. Да и C++ думаю здесь не причём

**Comment by Funcy-dcm** [comment]
Собрал с Qt 5.6.3, но есть проблема - Для QtWebkit требуется версия Qt не ниже 5.6.3, а в Qt выше версии 5.5 удалён совсем QtWebkit и я не могу собрать QuiteRSS ))

**Comment by Funcy-dcm** [comment]
Сейчас для QuiteRSS я использую 5.4.2, с ней QtWebkit собрать скорее всего совсем не получится: нужен минимум Qt 5.6.3 и msvc2015, а для 5.4.2 используется msvc2013

**Comment by Katarn** [comment]
Имеется в виду форк QtWebkit? Я его с Qt 5.9 собирал и приложение тоже. Кстати, я с emerge-флагом `--nodeps` собирал, чисто для теста, и на удивление собралось нормально. Флаг этот отключает слежение за зависимостями при установке, следовательно сборка была в том же окружении что требовалась для сборки QtWebEngine 5.9 и прочих модулей Qt этой же версии.

**Comment by Funcy-dcm** [comment]
В моей версии Qt под виндовс совсем отсутствуют какие-то следы о Webkit, следовательно нужна будет либо полная пересборка Qt с добавлением исходников QtWebkit либо собрать QtWebkit с версией 5.4.2

**Comment by Katarn** [comment]
Смотри, у меня Qt был собран отдельными модулями, я в конце сборки Qt отдельно скомпилил вот этот пакет: http://www.calculate-linux.ru/packages/dev-qt/qtwebkit

Потом я начал компилировать annulen (давай называть его так, чтобы не путаться с оригинальным qtwebkit), но он не захотел устанавливаться, так как были коллизии с пакетом выше. Тогда я удалил qtwebkit, и компиляция и установка annulen успешно завершилась. После того как он скомпилировался, он занял место qtwebkit в системе.

Итого, вывод 1: qtcore, qtgui и остальные модули изначально ничего о qtwebkit не знали, после установки annulen мне их перекомпилировать не приходилось. Вывод 2 (и возможно он только Linux-специфичный): скомпилированный и установленный в систему annulen успешно определился при выполнении ./configure от QuiteRSS (или что там было вместо него?), и дальнейший make прошёл успешно.

**Comment by Funcy-dcm** [comment]
Либо я что-то не правильно делаю, но скрип сборки не делает install - я так думал что после сборки annulen доложен был инсталироваться в каталог Qt, который я указал в "-DCMAKE_PREFIX_PATH=c:\Qt\Qt5.6.3\5.6.3\msvc2015". Даже пробовал делать отдельно **cmake install** - выдаёт какую-то непонятную ошибку. 
В общем скопировал ручками то что собрал, пересобрал приложение и запустил. Попросило icuuc57.dll - хотя я собирал annulen с флагом "-DENABLE_INTL=OFF", после добавления этих dll всё заработало. Теперь надо как-то отучить annulen от icu и научиться делать install, хотя возможно один раз ручками сделал и больше не понадобиться

**Comment by Katarn** [comment]
Вообще, эта либа нужна для поддержки Unicode, и в ебилдах что оригинального qtwebkit, что annulen, прописана как обязательная, не отключаемая.

**Comment by Funcy-dcm** [comment]
Можешь проверить у себя эту ленту: http://www.yaplakal.com/news.xml
В описании новости не отображается видео, это с annulen. А в старом всё норм

**Comment by Funcy-dcm** [comment]
Как оказалось, qtwebkit можно было самому не собирать, у него на сайте есть готовые сборки под разные версии Qt

**Comment by Katarn** [comment]
YouTube - играет. Другие нет. Но они и в QtWebEngine не играют. Наверняка связано с выпилом из Chromium поддержки формата плагинов на котором работает Flash.
