### ISSUE TITLE
Предложение, добавить фичу: синхронизация ленты 

### ISSUE THREAD

**Issue by chebevara** [QuiteRSS/quiterss#897]
Разработчики, спасибо за ваш труд. Приложение супер.
Но не хватает киллер-фичи.
Например, было бы очень удобно, синхронизировать ленту между приложениями, запущенными на разных компьютерах.
Спасибо.

**Comment by Katarn** [comment]
Поддерживаю. Можно сделать серверный движок для синхронизации с возможностью установки на свои серверы.

**Comment by Funcy-dcm** [comment]
https://github.com/QuiteRSS/quiterss/issues/128
