### ISSUE TITLE
Security Issue  "Insecure Cipher Suites"

### ISSUE THREAD

**Issue by damascene** [QuiteRSS/quiterss#898]
I've tested Quiterss 0.18.3 on Ubuntu 16.04 with some security checks and it failed with number of them:
You can add this feed to test:
https://raw.githubusercontent.com/damascene/s-check/master/rss.xml

Most remarkably How's My SSL test:
https://www.howsmyssl.com/

Quiterss 0.18.3 on Ubuntu 16.04
Includes: Qt-5.5.1, SQLite-3.10.2, WebKit-538.1

**Comment by Funcy-dcm** [comment]
Unfortunately, this problem Qt

**Comment by damascene** [comment]
I think it's because of old webkit1 engine

**Comment by Funcy-dcm** [comment]
#756

**Comment by damascene** [comment]
If webkit have advised about not using that version. then whose fault is that?

**Comment by Funcy-dcm** [comment]
https://quiterss.org/en/article/1153
