### ISSUE TITLE
Невозможно задать нужные колонки после обновления до 0.18.3

### ISSUE THREAD

**Issue by turbodude** [QuiteRSS/quiterss#900]
До обновления можно было в свойствах задавать определённые колонны для папки или отдельных подписок. Сейчас - пропал таб с колонками в свойствах для групп, а для индивидуальных подписок он остался, но эти параметры не сохраняются после переключения на другие подписки.

**Comment by online** [comment]
Да, поддерживаю @turbodude. То же заметил их отсутствие. Прошу @Funcy-dcm вернуть, если это возможно.

**Comment by Funcy-dcm** [comment]
В ближайшее время исправлю. К сожалению, не всё усмотрел после добавления функционала сторонним разработчиком.
