### ISSUE TITLE
Tab Focus changes on selecting new feed

### ISSUE THREAD

**Issue by Cynyster** [QuiteRSS/quiterss#903]
When I alternate click a feed in the feed tree and select "open in a new tab" that feed opens in a new tab that is selected an becomes the active tab. This leaves the original tab as I would expect. 

When I select another feed with the 2nd tab active,  the new choice displays in the first tab that is not selected.

What I am trying to accomplish is basically this: 
I would like to continue to browse through articles in one tab while the original tab is still playing the media in an article that I selected in another tab.

**Comment by alex1a** [comment]
+1

**Comment by Funcy-dcm** [comment]
Try version: 0.18.10
