### ISSUE TITLE
System Tray Icon Doesn't Retain Unread Count When Minimizing

### ISSUE THREAD

**Issue by Brainstem** [QuiteRSS/quiterss#905]
When I minimize QuiteRSS to system tray, it "clear out" the unread count.  I would like an option to keep the current unread count after minimizing.  

Otherwise...Great product.

**Comment by Funcy-dcm** [comment]
Menu - Tools - Options - System tray - Clear new status when minimize to
tray

2016-03-08 21:38 GMT+05:00 Benjamin Bartels notifications@github.com:
