### ISSUE TITLE
Update to latest version (0.18.4) completely erased my feed list

### ISSUE THREAD

**Issue by twain28** [QuiteRSS/quiterss#906]
Hello!
I just ran the auto-updater, and now all my feeds are gone, I'm left with only QuiteRSS's default one...
I had a look inside the main folder, and I found out that the "feeds.db" file is still there. AFAIK, it should still contain all my feeds and preferences thereof (it's around 10mb, so somethins must be in there).
I copied it somewhere safe, and I also tried restoring an old version, yet the application seems not to read anything from it.
I'll provide logs, if needed. Just give the word and let me know how to generate them.
In the meantime, I'll try rolling back to the previous version...
Regards,

Twain28

**\* EDIT: I tried restoring both a previous version and previous backups... same results with 0.18.3...help....

**Comment by Funcy-dcm** [comment]
You have a portable version?
Install the new version and copy the old files (Quiterss.ini, feeds.db) on new paths.
The path to the directory: "Menu - Help - About - Information"

**Comment by Funcy-dcm** [comment]
Perhaps you have used the portable version, and you have lost the file portable.dat
