### ISSUE TITLE
Keeps crashing on video play

### ISSUE THREAD

**Issue by BGMcoder** [QuiteRSS/quiterss#907]
Every time I try to play a video, QuiteRSS crashes.  And then I have to go and mark "read" again any feeds I read before it crashed (QRSS doesn't seem to save the feed-read state until it closes).

Whenever QRSS crashes I also lose any open tabs (and there is no history).

Any video, really, but by way of an example, [any of the videos in this page](http://feedproxy.google.com/~r/Twistedsifter/~3/B03eQmOupwk/).

So I tried to update to the latest version which was published a couple days ago (I was already on the currently current version) and it is the same thing.

I wish there was an error console or something.

**Comment by Funcy-dcm** [comment]
The problem webkit. What is your operating system?
Try version 0.17.7

**Comment by BGMcoder** [comment]
I'm sorry - I really meant to report the platform...
Windows 7 x64 Pro with QuiteRSS 0.18.4 r3674
I'll downgrade; thanks for the tip.

**Comment by BGMcoder** [comment]
Is this *still* not-our-bug?  Really?  I am still having this problem now in December - that's a whole year.  Every time I click to play a video in the viewing pane OR in a new tab, QSS crashes - every single time - especially on you-tube video links.  I'm running Windows 7 with 20GB RAM and an i7.

**Comment by Funcy-dcm** [comment]
In version 0.17.7 does not work?
Unfortunately this is a problem embedded browser engine. I try to switch to another browser engine.

**Comment by BGMcoder** [comment]
Thanks for considering!  I love QuiteRSS quite a bit.  I've tried a dozen other RSS readers and have been with QuiteRSS for several years now.

**Comment by BGMcoder** [comment]
whoops - I pushed the wrong button.

**Comment by BGMcoder** [comment]
Any news?  Maybe this is not a bug in your component, but it's a bug in QuiteRSS.  When I play videos it crashes, and it has been doing this for a long time;  surely the underlying components have been updated since the last version was released.

**Comment by Funcy-dcm** [comment]
Problem in browser engine

**Comment by Funcy-dcm** [comment]
#756
