### ISSUE TITLE
[Security] Port to WebEngine due to many known security vulnerabilities in QtWebKit

### ISSUE THREAD

**Issue by genodeftest** [QuiteRSS/quiterss#909]
There are probably more than 100 know security-relevant bugs (vulnerabilities) in QtWebKit ([Source](https://blogs.gnome.org/mcatanzaro/2016/02/01/on-webkit-security-updates/)) which is why it is [deprecated](https://doc.qt.io/qt-5/qtmodules.html). Use WebEngine (based on Chromium's blink engine) instead.

See also: #893

**Comment by Funcy-dcm** [comment]
We want to develop a new QuiteRSS2, but try https://yadi.sk/d/-mL1zh4gMHXwt (Windows)

**Comment by a17r** [comment]
How's progress wrt QtWebEngine?

**Comment by Funcy-dcm** [comment]
Unfortunately I don't have time to deal with the new version.
