### ISSUE TITLE
Настройка "автоматическое обновление" папки не распространяется на ленты

### ISSUE THREAD

**Issue by sojusnik** [QuiteRSS/quiterss#910]
В версии 0.18.4 (08.03.2016) настройка "автоматическое обновление каждые x часов" в свойствах папки не переносится на ленты внутри нее. Попробуйте, к примеру, отключить автообновление папки и загляните в свойства ленты - там оно будет отключено, но опять не включится, если заново включить автообновление в папке, где находится та самая лента. Приходится у всех лент включать автообновление вручную.

**Comment by Funcy-dcm** [comment]
Try version: 0.18.10

**Comment by sojusnik** [comment]
До сих пор (v0.19.2) работает ненадёжно: для примера, настройте в папке с несколькими лентами авт. обновление на 3 часа (с 1 часа) — ленты в папке теперь тоже будут обновляться каждые 3 часа, но если опять папку переставить на 1 час или вообще убрать автообновление, то ленты не перенимут эти настройки.
По умолчанию у меня все ленты обновляются каждый час.
