### ISSUE TITLE
Crash on some views

### ISSUE THREAD

**Issue by kucherenko-m** [QuiteRSS/quiterss#912]
Somtimes crash appears when viewing some previews on specified rss (http://www.ixbt.com/export/news.rss) (ixbt-news). Maybe it depends with previews cache size (specified site load full news bodies into rss previewes): after application relaunch preview which cause crash opens successfully.

UPD. Maybe this issye can be linked with jumping to next preview in list while content of previous preview is loading to be shown in preview area.

**Comment by Katarn** [comment]
Try new version - problem still reproduce? This may be due to the presence of flash video on page?
