### ISSUE TITLE
Persistent Crashes

### ISSUE THREAD

**Issue by alanhodges** [QuiteRSS/quiterss#914]
I've been using QuiteRSS for about a year and have had no problems until yesterday. Suddenly, whenever I start the program, I get the message that the program has stopped working and will close. This appears to come from Windows 10 because it says Microsoft will look for a solution (some hopes!).

I uninstalled and reverted to version 0.18.2 but the problem persists.

Any suggestions whereby I might get my feeds back will be very much appreciated.

Alan Hodges

**Comment by Katarn** [comment]
Try new version - problem still reproduce?
