### ISSUE TITLE
Обновлять элемент фида вместо добавления нового

### ISSUE THREAD

**Issue by kapsh** [QuiteRSS/quiterss#918]
Если уже существующая новость была обновлена, то она добавляется как новая. Хотелось бы, чтобы вместо этого обновлялась существующая: отмечалась непрочитанной и изменялось содержимое (при этом время публикации оставалось бы старым).

**Comment by Funcy-dcm** [comment]
К сожалению, этого мы не будем делать, т.к. наша архитектура не позволяет это реализовать
