### ISSUE TITLE
Bugs in Newspaper view

### ISSUE THREAD

**Issue by ZeMaB** [QuiteRSS/quiterss#924]
Hi,

First i wish to thank you for your great reader
I have two bugs to report, both related to newspaper view:
- The delete duplicate messages option is not working in this view
- Since version 0.18.3, "Set focus at the top of the news list" is broken. I had to rollback to 0.18.2 to have it working again

I hope you will fix these in the next version

Regards,

MaB

**Comment by Funcy-dcm** [comment]
Try version: 0.18.10
