### ISSUE TITLE
Expired certificate on quiterss.org

### ISSUE THREAD

**Issue by anlar** [QuiteRSS/quiterss#929]
> quiterss.org uses an invalid security certificate. 
> The certificate expired on 06/24/2016 11:17 AM. The current time is 06/25/2016 03:33 PM. 
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by Fixer-007** [comment]
Confirmed.

**Comment by genodeftest** [comment]
If you need free certificates, you might want to use letsencrypt [1] with a very small client called acme-tiny [2].

[1] https://letsencrypt.org/
[2] https://github.com/diafygi/acme-tiny
