### ISSUE TITLE
QuiteRSS does not delete excessive news items on Windows 7 shutdown

### ISSUE THREAD

**Issue by Fixer-007** [QuiteRSS/quiterss#930]
I have a setting to remove news items older than 60 days or if they exceed 300 items per feed, however, QuiteRSS does not delete them on windows shutdown, so it slowly bloats to huge sizes (20000 news and more).
If I shutdown QuiteRSS manually - it clears up old news properly.

QuiteRSS 0.18.2 (14.07.2015)
Win 7 sp1 (updated)

**Comment by Funcy-dcm** [comment]
Try version 0.18.6
I checked, everything works
