### ISSUE TITLE
Update deleted all RSS Feeds (Linux)

### ISSUE THREAD

**Issue by BCOH** [QuiteRSS/quiterss#932]
I added the PPA and updated to the newest version. After the update all the feeds I've accumulated are gone. Will this be a regular feature of the upgrade process?

**Comment by DMexico** [comment]
![screenshot - 22 07 2016 - 16 01 07](https://cloud.githubusercontent.com/assets/16545667/17057843/90757194-5025-11e6-9073-2213bfecd474.png)
Same. After the update all the feeds I've accumulated are gone.

**Comment by Xaphiosis** [comment]
Great fortitude! They are not lost, merely buried. It appears the storage has moved from `~/.local/share/QuiteRss/QuiteRss` to `~/.local/share/data/QuiteRss`.

You can clobber the new settings with your old settings like so:

```
cd ~/.local/share/data/QuiteRss
cp -a ~/.local/share/QuiteRss/QuiteRss/* .
```

If you are wondering how I discovered this:

```
strace -f -e trace=file quiterss 2>&1|grep feed 
```

**Comment by Funcy-dcm** [comment]
This feature of the transition from the 0.17.x version to version 0.18.x
