### ISSUE TITLE
All content updating under Win10 not working

### ISSUE THREAD

**Issue by thravis** [QuiteRSS/quiterss#937]
Under QuiteRSS version 0.18.4 (install version) channel synchronisation with requested time doesn't work. Also after first start software (option is set) channel synchronisation doesn't work. If it is any workaround please inform me.

**Comment by mailinglists35** [comment]
For me it only updates when I add the feed. Then it no longer updates, neither automatically nor manually.
log and config files pasted in comment on issue https://github.com/QuiteRSS/quiterss/issues/934#issuecomment-333815622

**Comment by Funcy-dcm** [comment]
Try version 0.18.10
