### ISSUE TITLE
CNET business Tech rss sudden page loading freezes and crashes quiterss

### ISSUE THREAD

**Issue by ghost** [QuiteRSS/quiterss#941]
I only started experiencing this lately, when loading the full page on CNET rss for example, it loads until 90% and then the QuiteRSS freezes and you have to kill the process, Ubuntu 14.04.
The moment of 90% loaded of the page, a flash window pops up below in the right hand corner.

**Comment by Katarn** [comment]
I checked, on version 0.18.9 everything works stably.
