### ISSUE TITLE
Feature request: filters

### ISSUE THREAD

**Issue by greenaar** [QuiteRSS/quiterss#943]
Can you add a filter rule to either allow 'launch in browser' or 'trigger external command' ?

I like your product, but I'm still using RSSowl currently as it has the former of those 2 features, which i use heavily.  Having the latter (ie output the url to an external command, potentially allowing for some additional options to be passed) would convince me to make the switch for real.

Best.

**Comment by nonamethanks** [comment]
Seconding this. I tried to migrate from RSSowl but the lack of a "launch in browser" option for filters is what's stopping me from fully switching over.
