### ISSUE TITLE
Close notifications after main window is opened.

### ISSUE THREAD

**Issue by one727876** [QuiteRSS/quiterss#945]
Hello.
I don't want to miss notifications, so I've set to "Close after" = 0 seconds.
After I click on a notification, the main window opens, but the notification will not close... So, I have to close it manually every time.
Thank you!

**Comment by one727876** [comment]
PS: If you click on the top of notification window it closes with no problem; if you click on an item (which is inside the window) it stays open. And notification window stays open even after all items in the main window are marked as read.

**Comment by one727876** [comment]
Извиняюсь, случайно закрыл этот тикит. Продублирую еще на русском. 
Чтобы не пропускать оповещения, я установил параметр "Close after" = 0 seconds. Соответственно всплывающие оповещения не исчезают сами, а жду когда я на них кликну.
Если кликнуть на верх такого оповещения (заголовок Incoming News: 1), то оно нормально закрывается и вместо него открывается основное окно приложения. Если же кликнуть на пост внутри, то основное окно открывается, о оповещение так и остается висеть. Даже если внутри основного окна пометить все как прочитанное. Соответственно, приходится оповещения каждый раз закрывать вручную.
Спасибо!

**Comment by Funcy-dcm** [comment]
Это сделано специально
Хотя можно и переход сделать
