### ISSUE TITLE
Ещё 2 действия для горячих клавиш

### ISSUE THREAD

**Issue by Vladimir-Vl** [QuiteRSS/quiterss#946]
Здравствуйте!

В настройках горячих клавиш есть действия "Предыдущая лента" (Ctrl+Up) и "Следующая лента" (Ctrl+Down).
Хотелось бы чтобы там были ещё 2 действия: "Предыдущая непрочитанная лента" и "Следующая непрочитанная лента".
Это нужно для того, чтобы можно было с помощью горячих клавиш быстро переходить между непрочитанными лентами, пропуская кучу лент не имеющих не прочитанных новостей.

Спасибо!

**Comment by Funcy-dcm** [comment]
Для этих целей есть "Предыдущая непрочитанная новость" и "Следующая непрочитанная новость"
