### ISSUE TITLE
FILTER SUGGESTION:  [+] (New Conditional), New Item Should match the [+] Conditional (not always TITLE CONTAINS)

### ISSUE THREAD

**Issue by dbareis** [QuiteRSS/quiterss#947]
The subject pretty much says it. I always have to correct the default "TITLE CONTAINS", this is fine for the first entry but after that it should duplicate the condition (less value) of the line containing the "+" button used.

It would also be handy to import and export conditionals.

**Comment by Funcy-dcm** [comment]
Unfortunately, we will not do this

**Comment by dbareis** [comment]
OK, but that sucks big time, as does the lack of "does NOT begin with" etc
