### ISSUE TITLE
HSTS

### ISSUE THREAD

**Issue by fate14** [QuiteRSS/quiterss#948]
Hello,

Does QuiteRSS v0.18.4 have HSTS support?

cheers

**Comment by fate14** [comment]
And why do feeds that use HTTPS appear as HTTP?

![quiterss-http](https://cloud.githubusercontent.com/assets/22940100/19526758/04af7bd8-9615-11e6-8188-13c6ebdaed2b.png)

**Comment by Katarn** [comment]
Hello. No, HSTS is not currently supported because this is QtWebKit limitations. It may be supported in QuiteRSS 2 with QtWebEngine, but before its released it is still far.

On the second question - check the feed URL and its contents.
