### ISSUE TITLE
Feature Request: Shift+Del to Bypass "Deleted" Folder & to Delete Protected News

### ISSUE THREAD

**Issue by ghost** [QuiteRSS/quiterss#951]
I'd like to request that a keyboard shortcut be added: **Shift+Del** to directly delete news, bypassing the "trash", and to allow the user to delete feed items which are otherwise protected from deletion (i.e. labelled and starred news).

Thanks!

**Comment by Funcy-dcm** [comment]
Unfortunately this is not possible
