### ISSUE TITLE
constant crashing on Win 10 x64

### ISSUE THREAD

**Issue by havrancek** [QuiteRSS/quiterss#953]
dont know where´s the problem, but QuiteRSS is still crashing, when i click on any article, or it stops responding totally, so i have to close it and open again with all those old news i´ve already read.. it´s driving me nuts, can you please do something about it?

**Comment by Funcy-dcm** [comment]
Try version 0.17.7

**Comment by havrancek** [comment]
still crashing - also with version 0.17.7 (after complete uninstall and reinstall)

**Comment by qcybb** [comment]
You should check your startup tab (ctrl + alt + del > Task Manager > Startup ) and see if something being loaded in there that is interfering with QuiteRSS.

I'm running Windows 10 x64 as well and have no issues whatsoever.

**Comment by martinki** [comment]
Same problem here on Win 10 Pro x64. It's so bad that I have finally given up on QuiteRSS and started using Thunderbird. It's sad as QuiteRSS is the best reader I found in a long time.

**Comment by qcybb** [comment]
Are you guys using the latest version 0.18.4 (Revision 3674)? If not, you can download it from MajorGeeks (until the QuiteRSS website is back up).

http://www.majorgeeks.com/files/details/quiterss.html

I have it running on (4) Win 10 x64 machines here without issues.

**Comment by martinki** [comment]
version 0.18.4. Updated because 0.17.7 was crashing when trying to play videos.

**Comment by DanaMW** [comment]
With your website unreachable where else might someone download the update?

**Comment by Funcy-dcm** [comment]
https://github.com/QuiteRSS/quiterss/releases/tag/0.18.4

2017-04-18 3:34 GMT+05:00 Dana MW Chester <notifications@github.com>:

**Comment by Funcy-dcm** [comment]
Try version 0.18.6
