### ISSUE TITLE
Attempting to play video from internal browser crashes the program

### ISSUE THREAD

**Issue by Ribel78** [QuiteRSS/quiterss#958]
Attempting to play video from Youtube, Vimeo inside  in the Browser window, crashes the application.
The crash is often, but sometimes it manages to play the video without crashing.

**Comment by martinki** [comment]
I can confirm this happens

**Comment by Katarn** [comment]
Most likely the problem is in a very old WebKit. He has not been supported for several years.

**Comment by Funcy-dcm** [comment]
#756
