### ISSUE TITLE
No longer respects the "show news description instead of web pages" setting

### ISSUE THREAD

**Issue by ZzZombo** [QuiteRSS/quiterss#961]
I use the Portable Apps distribution of QuiteRSS on Windows 10 x64. Since some unknown point of time, it no longer respects the said setting, always opening web pages of news instead of their plain-text descriptions.

**Comment by ZzZombo** [comment]
Bump?

**Comment by Funcy-dcm** [comment]
Yes, there really is a problem, I'll try to decide.
Just in case: https://quiterss.org/en/node/1153

**Comment by Funcy-dcm** [comment]
fix: 243d40f63080339b3babe067e2484e3e55853e3c
I corrected the error, but you need to manually disable this option in the ribbon or folder properties.
