### ISSUE TITLE
"Access Denied" error when opening item in build-in browser

### ISSUE THREAD

**Issue by pamtbaau** [QuiteRSS/quiterss#962]
When opening an item from feeds from https://www.sciencedaily.com (e.g. [See this one](https://www.sciencedaily.com/releases/2017/04/170406121607.htm)) an "Access Denied" error is shown in the internal browser. When opening the item's url in an external browser everything works fine.

This happens since about a few months.

**Comment by Funcy-dcm** [comment]
Try disabling AdBlock

**Comment by pamtbaau** [comment]
Couldn't get it resolved and in the meantime I created a simple email based reader using Electron.

To re-investigate the above issue, I reinstalled QuiteRss but cannot reproduce the issue. Adblocker on/off makes no difference. All seems well...

**Comment by Funcy-dcm** [comment]
Strange, but it's good that everything was decided )
