### ISSUE TITLE
Not working with some feeds

### ISSUE THREAD

**Issue by peter099** [QuiteRSS/quiterss#963]
QuiteRSS doesn't work with feeds like these:
```
https://www.blackhatworld.com/forums/making-money.12/index.rss
http://feeds.feedburner.com/foxnews/latest
```

It doesn't fetch the correct feeds, it doesn't display the correct author and publish time. 
There are also other feeds with this problem.

**Comment by Katarn** [comment]
What do you consider an incorrect author? Can you give an example? If you open the first link in the browser, you can see next XML:

```XML
...
<author>invalid@example.com (SickeM)</author>
...
```

And can conclude that the feed itself is incorrectly generated.
