### ISSUE TITLE
Links that use '//' can not be opened with an external browser

### ISSUE THREAD

**Issue by z-z-k** [QuiteRSS/quiterss#964]
Some rss source links do not use 'http: //' nor use 'https: //' instead of '//' as the beginning

**Comment by Funcy-dcm** [comment]
Can you give a link to the feed?

**Comment by z-z-k** [comment]
http://ask.dcloud.net.cn/feed/

**Comment by Funcy-dcm** [comment]
This is a feed error. But I did a bypass of this error.
