### ISSUE TITLE
quiterss.org website down?

### ISSUE THREAD

**Issue by qcybb** [QuiteRSS/quiterss#965]
I've been unable to access quiterss.org website for over a week now. 

All I keep getting is : Error 502: Bad Gateway

**Comment by Funcy-dcm** [comment]
Sorry, website moves to a new server

**Comment by qcybb** [comment]
Do you know when it will be back up?

**Comment by ViennaMike** [comment]
As of 6:18 Eastern Daylight Time on 19 April, it's giving a 522 Error (Connection Timed Out).
