### ISSUE TITLE
[Feature request]: Better support for external browser

### ISSUE THREAD

**Issue by lgbaldoni** [QuiteRSS/quiterss#966]
In my case xdg-open.

Right now external links are prepended with the page source hostname so that they all end up being opened with the web browser.
That makes sense when said links are local in respect to the rss page, but if the link contains a specific protocol (e.g. ftp: news: magnet: ...), wouldn't it make sense to pass it directly to the external browser so that xdg-open could do its work?

Unless there's already a setting for such a thing, but I couldn't find it.

**Comment by Funcy-dcm** [comment]
Send screenshots

**Comment by lgbaldoni** [comment]
Sorry, it was months ago and I can't remember how to reproduce it.

**Comment by Funcy-dcm** [comment]
I then close this issue. If you remember, I'll reopen it.
