### ISSUE TITLE
Memory consumption on QuiteRSS 0.18.4

### ISSUE THREAD

**Issue by V-ctor** [QuiteRSS/quiterss#967]
It starts with ~180 Mb but after several hours usage it demands ~700-800Mb. Sad.
Linux victor-PC 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

==31035== HEAP SUMMARY:
==31035==     in use at exit: 9,673,710 bytes in 79,045 blocks
==31035==   total heap usage: 15,180,767 allocs, 15,101,722 frees, 3,564,371,778 bytes allocated
==31035== 
==31035== Searching for pointers to 78,434 not-freed blocks
==31035== Checked 186,028,368 bytes

==31035== HEAP SUMMARY:
==31035==     in use at exit: 9,673,710 bytes in 79,045 blocks
==31035==   total heap usage: 15,180,767 allocs, 15,101,722 frees, 3,564,371,778 bytes allocated
==31035== 
==31035== Searching for pointers to 78,434 not-freed blocks
==31035== Checked 186,028,368 bytes

ran as

G_SLICE=always-malloc G_DEBUG=gc-friendly  valgrind -v --tool=memcheck --leak-check=full --num-callers=40 --log-file=valgrind.log $(which quiterss) 
[valgrind.zip](https://github.com/QuiteRSS/quiterss/files/927830/valgrind.zip)

**Comment by Funcy-dcm** [comment]
Do you use the built-in browser?
