### ISSUE TITLE
Notification doesn't close if mouse pointer located within notification window

### ISSUE THREAD

**Issue by yfrolov** [QuiteRSS/quiterss#968]
Steps to reproduce
1. Locate mouse cursor to a screen area where notifications suppose to pop up.
2. Wait until notification message pops up.
3. Notification doesn't close as long as cursor is over it.

Expected behavior:
Notification close after specified in settings amount of time.

**Comment by Funcy-dcm** [comment]
This is done specially. While the user is working with the notification, it is displayed

**Comment by yfrolov** [comment]
My use case: I watch full screen video and if mouse pointer was left in the area where notifications suppose to pop up, it's very annoying always closing it, because it's not going to close itself.
