### ISSUE TITLE
Fetch only posts from the last 60 minutes?

### ISSUE THREAD

**Issue by kylescousin** [QuiteRSS/quiterss#969]
Been using QuiteRSS for a while and there's only 1 feature that I'm missing. When you have a few 100 feeds, and you open QuiteRSS in the morning, you get 1000s of articles because it fetches everything since your last fetch. Is there a way to add a feature to fetch only the content from the last x minutes?

**Comment by Funcy-dcm** [comment]
Unfortunately no. But you can turn on the option "Menu - News - Filter News  - Show last day"
