### ISSUE TITLE
зависает и отваливается сразу 

### ISSUE THREAD

**Issue by rdbox** [QuiteRSS/quiterss#970]
с чем это может быть связанно, читаешь читаешь ленту и бац записло а потом вообще завершается программа сама по себе почему так?

**Comment by Funcy-dcm** [comment]
Какая версия приложения?

**Comment by rdbox** [comment]
сейчас другая проблема версия QuiteRSS-0.17.7 
отваливается через какое-то время от 2-3 минут и вылетает из tray

**Comment by Funcy-dcm** [comment]
Попробуйте версию 0.18.5

**Comment by rdbox** [comment]
А как скачать ? 
Вижу толька сорсы  у меня win

**Comment by Katarn** [comment]
https://quiterss.org/ru/download

**Comment by Funcy-dcm** [comment]
Заработало?

**Comment by rdbox** [comment]
с пунто свичер еще плохо работает отваливается.
И когда ролик включаешь с ютуба тоже падает

**Comment by Funcy-dcm** [comment]
> И когда ролик включаешь с ютуба тоже падает

Похоже всё-таки проблема в движке браузера. Попробуйте отключить JavaScript в настройках.
Или ждать QuiteRSS2

**Comment by rdbox** [comment]
Если отключать js то падает верстка сейчас многое работает на ui.js jquery.js bootstarap и т.д
Это значит когда открываешь страницы в во внутреннем браузере  с отключенным  js то просматривать страницы не удобно

**Comment by Funcy-dcm** [comment]
Это понятно, интересно перестаёт падать или нет?

**Comment by rdbox** [comment]
не проверял, так как слежу за rss лентой и это связанно в плотную с работой.

**Comment by rdbox** [comment]
такой вопрос, а вы планируете реализовать  такую возможность  что бы можно было удалять дубли?
Например пришло 100 новостей из них 5-10 только самые важные остальное дубли удалить в ручную нудно как-то.

А вот если бы была кнопка при удаление новостей, удалять дубли.

**Comment by Funcy-dcm** [comment]
В свойствах ленты есть опция

**Comment by rdbox** [comment]
Нет не работает.
Все равно дубли есть,  дубли по заголовку 

P.S. версия стоит последняя

**Comment by Funcy-dcm** [comment]
Это будет работать только для новых новостей. Дайте ссылку на ленту

**Comment by rdbox** [comment]
вот.
https://nnm-club.name/forum/rss.php?f=756,697,144,745,723,42,45,928,44,48,752,1191,72,29,30,77,747 

Когда отвечают участники то появляются дубли, а мне бывает нужным просто почитать  саму новость но не ответу участников из-за этого много дублированных новостей.

**Comment by Funcy-dcm** [comment]
Ааа, дак это форум, тут пока ничем помочь не могу, попробую добавить опцию в QuiteRSS2

**Comment by rdbox** [comment]
ну да у меня 80% новостей из форума или топиков так оперативней я получаю данные.
Вот  и прошу вас придумать что-то, что бы можно было удалять дубли все а 1 новость оставлять это будет нереальное экономия времени

**Comment by Funcy-dcm** [comment]
Закрываю
