### ISSUE TITLE
QuiteRSS Build Improvements?

### ISSUE THREAD

**Issue by JLChamberlain** [QuiteRSS/quiterss#971]
So over the past couple of weeks I have been searching up and down the internet for the best RSS reader than I can find. After my research I found two good RSS readers (RSSOwl & QuiteRSS) but RSSOwl is definitely superior in aesthetics and certain functions (Filtering & Notifications) compared to QuiteRSS. While I think RSSOwl is better designed it seems the software doesn't work with all feeds (SSL Issue) but QuiteRSS does. To make QuiteRSS better than RSSOwl I believe in my opinion some things needed to be improved which are:

- A Filter Option to Move the items that match the rule to a new a folder or bin (Like in RSSOwl) instead of staring them or labeling them. This would make filtered content a lot clearer and stand out from the unfiltered content.

- A notification option to allow notifications to stay on the screen forever until the user gets rid of them manually instead of setting a time of seconds for how long for it to remain on the screen.

- Maybe a notification setting to inform the user that the feed is not working or no longer available incase the feed is in a folder and the user doesn’t see the X mark on the icon.

- Added share options such as Reddit & Pinterest. Also option to remove options that the user wouldn't use.

- A way to connect Feedly so that the feeds in QuiteRSS since to Feedly and when feeds have been read on Feedly they would then be marked read when you next start QuiteRSS.

- A cleaner displayed internal browser. I say this because of RSS readers like RSSOwl & Feedly seem to display the media in the external browser a lot more neater and cleaner. The title in other readers is generally more bolder and stands out more from the page text.

Except for that I really like QuiteRSS and I'm looking forward to future updates.

**Comment by martinrotter** [comment]
RSS Guard supports two internal browser (text-based cleaner & simpler & less hungry one OR webengine based viewer with Bootstrap theme in default skin).

**Comment by JLChamberlain** [comment]
I just tried out RSS Guard and it's missing alot of basic stuff like filtering and notifications setting adjustments. I also dont like how you have to know what type of feed it is to add it to the reader. RSS Guard in my opinion is more lacking than QuiteRSS.

**Comment by martinrotter** [comment]
Filtering is on the way. I do not hurry with it.

You surely do not have to know what kind of feed you want to add to rssguard. It detects this.

**Comment by JLChamberlain** [comment]
I added a feed and it didnt respond in the software.

**Comment by martinrotter** [comment]
Link?

**Comment by JLChamberlain** [comment]
https://jaiminisbox.com/reader/feeds/rss

**Comment by martinrotter** [comment]
It works here fine. That feed server is very slow and returns feed's file after several seconds. This is not fault of RSS Guard but shitty feed. You can increase the max feed timeout in rssguard settings to 15 sec or something like that, and it will work for you too.

**Comment by JLChamberlain** [comment]
What about a move news action so that you can only get notifications from the items that are move to the new folder? (Like RSSOwl)

**Comment by Funcy-dcm** [comment]
https://quiterss.org/en/node/1153
