### ISSUE TITLE
Отображение интерфейса на мониторах высокого разрешения (4K)

### ISSUE THREAD

**Issue by chebevara** [QuiteRSS/quiterss#976]
На 4к мониторе интерфейс данной программы не располагает к пользованию

**Comment by Funcy-dcm** [comment]
Можно скриншот с заметками, что не так?

**Comment by akrus** [comment]
Вот скриншот:
http://jpegshare.net/1c/c1/1cc137cf5fb4aef16d93cf3f5aebf94d.png.html

PS> через QT_AUTO_SCREEN_SCALE_FACTOR можно сделать скейл, но тогда иконки становятся размытыми, да и в целом интерфейс выглядит не очень (скроллбар, например, все равно остается мелким)

**Comment by Funcy-dcm** [comment]
Что за ОС?

**Comment by akrus** [comment]
Ubuntu GNOME.

**Comment by Funcy-dcm** [comment]
У вас будет возможность собрать и проверить? Если я конечно найду решение

**Comment by akrus** [comment]
Да, без проблем.

**Comment by Funcy-dcm** [comment]
Проверьте версию 0.18.5

**Comment by chebevara** [comment]
![2018-06-05_08-33-55](https://user-images.githubusercontent.com/5576862/40956899-40c3a784-689b-11e8-9d3d-5c92a19a37b8.png)

Тяжело работать с программой на 4к мониторах.
