### ISSUE TITLE
Feature Request: Ability to copy all links in a feed at once

### ISSUE THREAD

**Issue by hkBattousai** [QuiteRSS/quiterss#980]
If a need to copy a link in a news, I have to right click on it and choose "Copy Link" item in the context menu. However, if I need to copy link(s) in every news in a feed, I have to right click every news and choose "Copy Link" one by one which is a very tedious work to do. Why can't we just simply right click the feed and choose an item like "Copy All Links" or "Copy All Links From Unread News"? This would make it very much easier if there is a download manager software in the background waiting for the links to batch process them.

**Comment by Funcy-dcm** [comment]
Sorry, all links cannot be copied.
For a separate news, you can use the hotkey
