### ISSUE TITLE
News on the Future of QuiteRSS

### ISSUE THREAD

**Issue by BGMcoder** [QuiteRSS/quiterss#982]
This isn't really an issue; but the main website is down at quiterss.org (which I see from this git home page that you are aware of), so I'm writing here to find news about QuiteRSS.

- When will there be an update?  (I'm hoping that [this issue](url=https://github.com/QuiteRSS/quiterss/issues/907) can be squashed)
- When will the website be back up?

Thanks for your time!

**Comment by Funcy-dcm** [comment]
The site works

**Comment by BGMcoder** [comment]
Maybe it's my router; I asked my friend to try the site and he can access it, so I guess it really isn't down, but it DOES say here](url=https://github.com/QuiteRSS/quiterss), right at the top of the page:  "Free news feeds reader (Website temporarily unavailable) http://quiterss.org"

**Comment by Funcy-dcm** [comment]
aaa, сorrected
