### ISSUE TITLE
Language files are not installed

### ISSUE THREAD

**Issue by willemw12** [QuiteRSS/quiterss#985]
Quiterss 0.18.5.
(Arch) Linux.

Language files are not installed in /usr/share/quiterss/lang:

    Error: this qinstall command requires exactly three arguments (type, source, destination)
    make[1]: [Makefile.Release:3377: install_translations] Error 3 (ignored)

Error is in Makefile.Release:

    install_translations: first FORCE
    ...
        -$(QINSTALL_FILE) /tmp/makepkg/quiterss/src/quiterss-0.18.5/_build/release/target/lang/*.qm $(INSTALL_ROOT)/usr/share/quiterss/lang/*.qm

Suggested fix: copy the directory instead of files:

    -$(QINSTALL_DIR) /tmp/makepkg/quiterss/src/quiterss-0.18.5/_build/release/target/lang $(INSTALL_ROOT)/usr/share/quiterss/lang

**Comment by Funcy-dcm** [comment]
What is your OS?

**Comment by willemw12** [comment]
See updated description.

**Comment by willemw12** [comment]
Fixed in 0.18.6. Issue can be closed.

**Comment by mmetak** [comment]
Still present on latest -git  243d40f . (archlinux)

**Comment by willemw12** [comment]
Yes, not fixed. I thought it was fixed, but the language files were from a previous install.

See the suggestion in the first comment for the fix.
