### ISSUE TITLE
Show New in Filter Feeds does not hide the last viewed feed

### ISSUE THREAD

**Issue by karim** [QuiteRSS/quiterss#987]
After upgrading from 0.18.4 to 0.18.5 the behavior of Filter Feeds has changed.

In "Filter Feeds" I select the option to "Show New" feeds to show only the feeds with new posts. After reading the posts from a feed and switching away from it to another feed, it hides itself (cause Filter Feeds is set to Show New) and that is the desired behavior.

However, after upgrading to 0.18.5 and whenever I switch to another feed, the older one doesn't hide and still visible. It does not hide automatically like in version 0.18.4.

**Comment by mmetak** [comment]
Still present for me on latest -git build. (archlinux)

Edit: it seems that after a while they do hide, but not right away?
