### ISSUE TITLE
On crash, open tabs and read feeds are lost

### ISSUE THREAD

**Issue by BGMcoder** [QuiteRSS/quiterss#988]
When [QuiteRSS crashes](https://github.com/QuiteRSS/quiterss/issues/907l), any open tabs are closed (lost) and any recently read news gets marked back to unread.  Then when you open QRSS again, you have to re-mark the unread news as read; and try to re-open the tabs you lost.  Open tabs are also lost when you quit (nicely) QRSS and start it again.

I'm running QRSS 1.8.5 on Windows 7x64 - but I've had this problem for years.

**Comment by PiotrKolobrzeg** [comment]
I have the same problem in 18.6.......

I don't see my tabs.

**Comment by Funcy-dcm** [comment]
Your OS?

**Comment by BGMcoder** [comment]
I updated my post; sorry about that.

**Comment by Funcy-dcm** [comment]
QuiteRSS does not save open tabs when closed - this is normal work.
Crash are most likely due to the built-in Webkit browser.
Try to disable the Javascript option.
In connection with the problem of the built-in browser, we decided to make a new application: https://quiterss.org/ru/article/1153

**Comment by BGMcoder** [comment]
Yeah, I know why it crashes - I was just saying that I lose my tabs when it does, and I wish that it would remember the tabs I had open last when I quit the application.  Since you're making a new application, maybe that is a feature that could be included.  I've even got my Mom using QRSS.

**Comment by Funcy-dcm** [comment]
I agree with you, I think it's worth adding such a function.
To open a feed in a separate tab at startup, there is an option in the properties of the feed. To save the marked news during a crash - disable the option "Store database in memory".

**Comment by BGMcoder** [comment]
Thanks for the tips - I'll try out unchecking the store db in memory (although it's good for me, as I have 24GB RAM).

**Comment by Funcy-dcm** [comment]
#756

**Comment by chrisretusn** [comment]
Having similar issue with some web sites such as https://arstechnica.com/?p=1211121. Good to hear a new version is on the way. The suggestion to turn off javascript is working okay, unfortunately it prevents a few sites from displaying with the internal browser. Example: https://www.forbes.com/sites/sleasca/2017/11/27/part-time-jobs-high-pay-part-time-work/. I can live with that. Turning off the store DB in memory work as you said. Very happy with that. I also seems, perhaps it's just me that the program takes less time to close and no real noticeable impact on performance. I have a fair number of feeds. Not sure how many, not motivated enough to count them. :) 

By the way, I am a switch over from RSSOwl, which seem to have been abandoned. Sure glad I found QuiteRSS!. Thanks.
