### ISSUE TITLE
Cannot display webpage

### ISSUE THREAD

**Issue by PaulHarder2** [QuiteRSS/quiterss#990]
When I double-click the Title of a post that goes to the address, the page does not fully display in the internal browser: http://www.motherjones.com/kevin-drum/2017/06/new-study-suggests-police-stop-minorities-at-moderately-higher-rates-than-whites/

The problem appears to be that the program is still trying to download the page. But the progress indicator stays constant at the same percentage value, without changing.

Other pages of the same blog are giving similar results, though not identical and not all the time.  For example: http://www.motherjones.com/kevin-drum/2017/06/cnn-trump-asked-intel-chiefs-to-publicly-exonerate-his-campaign/  That page froze the program after I double-clicked and then tried to scroll down the page. Unlike the previous example, this one does not have large graphic objects to display. It's nearly all text.

I am using Version 0.18.5 (15.06.2017) Revision 3701, the version available in the PortableApps tool set.

**Comment by Katarn** [comment]
Try to restart the app. Maybe somewhere in the memory someone element from this website is freeze during the loading.

**Comment by PaulHarder2** [comment]
No, restarting does not help. And it is not only the one blog that I reported. The internal browser appears to have a bug that freezes the entire program. I have not yet detected a pattern. I will report if I do detect a pattern.

**Comment by Funcy-dcm** [comment]
This is a problem kernel webkit.
#756
