### ISSUE TITLE
Crashes on workspace switch

### ISSUE THREAD

**Issue by ghost** [QuiteRSS/quiterss#991]
Hi everyone, new user here after recently switching from OSX (where I used ReadKit) to Linux. I really like the program, but...

I've been encountering an issue where whenever I switch workspaces, QuiteRss crashes / quits. I have very little idea how to diagnose how this is happening. No error message is given; it simply closes. I'm using the Gnome desktop on Antergos Linux. Has anybody seen something like this before, and, if not, how can I help to figure out what's going on and ensure it's corrected in a future version?

**Comment by Funcy-dcm** [comment]
Send video

**Comment by ghost** [comment]
Errrm, never mind; I figured it out - a bit embarrassing. Still, I'd consider it undesirable behavior (though not a bug in the strict sense) and maybe something that should be adjusted.

What was happening seems to be (in case anyone else encounters and is bothered by this behavior): The default options seem to result in the program minimizing itself to the system tray upon workspace switching (I'd consider this a pretty undesirable default behavior, but individual opinions may vary). I had, however, disabled my system tray icons as I found them distracting, so QuiteRSS appeared to vanish (and unlike other programs I use, when minimized, it also vanished from the Gnome Favorites Bar / Dock). Re-enabling the system tray confirmed that this was the case, and disabling "Show System Tray Icon" in the program seems to resolve the issue.
