### ISSUE TITLE
Rendering engine for embedded browser and GUI tweaks.

### ISSUE THREAD

**Issue by duytrung** [QuiteRSS/quiterss#993]
Hello,

I have an idea about the rendering for the webpage when double click to the news. Why don't we use the engine of Google Chrome' engine as embedded browser instead. It is fast, secured, regularly updated, implemented and more popular compared to the Webkit. Sometime, user needed to catch link to download clips. It does not support by popular download managers such as IDM.

There is no need to show the Tab "FEEDS". Instead, show the below icons including "add", "refresh", etc. The minimized menu icon can be put in the same toolbar with "add". Apply vertically. Tabs for reading news can be aligned horizontally as usual.

Thanks

**Comment by Funcy-dcm** [comment]
https://quiterss.org/en/article/1153

The tab "Feeds" can not be removed. For some actions you may need to go to the tree of news feeds.
