### ISSUE TITLE
QuiteRSS does not updates the database when feeds are getting any updates

### ISSUE THREAD

**Issue by petzre** [QuiteRSS/quiterss#995]
Hi all,

I saw the QuiteRSS does not updates the database when an existing feed gets some additional updates on his website.
For example if a news has been downloaded by the QuitteRSS app and after a while the news gets updated, the application does not downloads and show the updates. Is there a workaround to get the updates as well?

**Comment by Funcy-dcm** [comment]
Send screenshots

**Comment by petzre** [comment]
1. News was published on the website
![rss feed source - initial news](https://user-images.githubusercontent.com/29769844/27675868-5137e2ae-5cb4-11e7-8faa-c42efb72a624.JPG)

2. The QuiteRSS gets the news and downloads is locally
![first feed](https://user-images.githubusercontent.com/29769844/27675879-6494fec2-5cb4-11e7-99ce-c80cff9d5445.JPG)

3. The news was updated on the website
![rss feed source - updated news](https://user-images.githubusercontent.com/29769844/27675892-73d554ae-5cb4-11e7-92b0-dad10e37b273.JPG)

4. The QuiteRSS does not get the updates 
![no update](https://user-images.githubusercontent.com/29769844/27675930-997f2b30-5cb4-11e7-98f7-897e3aa8cee1.JPG)

**Comment by Funcy-dcm** [comment]
In the screenshots, the date and time are the same everywhere. How do you understand that the news has refreshed?
Give a link to the news feed.

**Comment by petzre** [comment]
Indeed the date is the same but the hour is different. But I've tried under Win10 and at the beginning it worked. But after a while its stopped.
Exp:
1. I have an action list in Microsoft SharePoint with lots of items inside.
2. I add a new action inside this list and after saving the RSS feed app updates the local DB correctly
3. The above action is edited later and save again (for example the Due date was changed). Thie update is not visible in the RSS app. It only keeps the initial version, like not having right the update the information in the DB.
4. If I am deleting the RSS feed from the app and synchronize again the action is imported with all the news inside.

Is there a setting to update the DB? 
Is there a user manual to explain all the settings and all the advanced setting from QuiteRss.ini file?

**Comment by petzre** [comment]
Any ideas?

**Comment by Funcy-dcm** [comment]
Unfortunately, no one developed the documentation.
You may have the option in the ribbon properties: "Automatic delete duplicate news"

**Comment by petzre** [comment]
Do you know how this feature works? It deletes the initial feed or the new one?:)

**Comment by Funcy-dcm** [comment]
This feature does not add news with the same time and title
