### ISSUE TITLE
Tumblr posts incorrectly marked as duplicated

### ISSUE THREAD

**Issue by rgamici** [QuiteRSS/quiterss#996]
I noticed that quiterss doesn't display some posts from tumblr. As far as I noticed, it does not display the items that contain _only_ images and no text.
ex.: http://owlturd.com/rss
I tried importing again the feed as I updated it to the latest version (0.18.6 on Debian) and then noticed that it showed "Unread:8 All:20" on the bottom right corner. When I change the filter to "Show All" instead of "Show Unread", those items appear. As far as I can tell, Quiterss is marking those items as duplicate. 
I have no idea how it determines if a post is a duplicate, but it is incorrectly marking those that have no text on their body, but only images.

ps.: If I disable the global option to mark duplicate items as read, I can avoid this problem. But then it might impact on the other news feeds.

**Comment by Funcy-dcm** [comment]
This option includes a function that finds news with the same title in other tapes and if it is, then the received news is marked as read.
