### ISSUE TITLE
Posts without title are fetched again every time the feed is updated

### ISSUE THREAD

**Issue by rgamici** [QuiteRSS/quiterss#997]
After disabling the option to mark identical items as duplicate one of my feeds begin to get new items every time I updated it. They are exactly the same posts (as the last update on the blog was on June 1st). Every time I update it, I get the same 25 news items.
Feed: http://hanzismatter.blogspot.com/feeds/posts/default
This doesn't happen to any other feed, even with the option to mark duplicates disabled. I think they were being fetched every time and then marked as duplicate. However, I cannot remember if it correctly displayed a new post.

**Comment by Funcy-dcm** [comment]
This is a very unusual tape. I will try to solve the problem.
