### ISSUE TITLE
Thunderbird connect not work... :(

### ISSUE THREAD

**Issue by csola48** [QuiteRSS/quiterss#998]
See you:
http://quiterss.org/en/article/1153%0A%0AQuiteRSS2 developing is
started!%0AThe application will be completely rewrited.%0AUI will be
redesigned. Special thanks to Bozhevarsky Dmitry.%0AWebkit engine of
internal browser will be replaced by Chromium.%0AThere will be special
release without internal browser.%0AThe appliction release date is
undefined.%0AFrom now update for current v0-version will fix critical
bugs only.%0A

URL would be needed only!
All of the summary comes instead... :(

**Comment by Funcy-dcm** [comment]
What is it??
